---
# Shared ConfigMap for all LMF services
apiVersion: v1
kind: ConfigMap
metadata:
  name: lmf-common-config
  namespace: lmf
data:
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  REDIS_ADDR: "redis-cluster:6379"
  KAFKA_BROKERS: "kafka-0.kafka:9092,kafka-1.kafka:9092,kafka-2.kafka:9092"
  CASSANDRA_HOSTS: "cassandra-0.cassandra:9042,cassandra-1.cassandra:9042,cassandra-2.cassandra:9042"
  AMF_BASE_URL: "http://amf-service.core.svc.cluster.local:8080"
  UDM_BASE_URL: "http://udm-service.core.svc.cluster.local:8080"


#Updated NRF BASE URL to my open5gs NRF running in my VM
  NRF_BASE_URL: "http://192.168.138.23:7777"


  #MY CHANGES - update service endpoints to match new service names and ports
  LMF_SERVICES_LOCATIONREQUEST: "location-request.lmf.svc.cluster.local:9001"
  LMF_SERVICES_SESSIONMANAGER:  "session-manager.lmf.svc.cluster.local:9002"
  LMF_SERVICES_METHODSELECTOR:  "method-selector.lmf.svc.cluster.local:9004"
  LMF_SERVICES_PROTOCOLHANDLER: "protocol-handler.lmf.svc.cluster.local:9003"
  LMF_SERVICES_GNSSENGINE:      "gnss-engine.lmf.svc.cluster.local:9005"
  LMF_SERVICES_TDOAENGINE:      "tdoa-engine.lmf.svc.cluster.local:9006"
  LMF_SERVICES_ECIDENGINE:      "ecid-engine.lmf.svc.cluster.local:9007"
  LMF_SERVICES_RTTENGINE:       "rtt-engine.lmf.svc.cluster.local:9008"
  LMF_SERVICES_FUSIONENGINE:    "fusion-engine.lmf.svc.cluster.local:9009"
  LMF_SERVICES_QOSMANAGER:      "qos-manager.lmf.svc.cluster.local:9013"
  LMF_SERVICES_PRIVACYAUTH:     "privacy-auth.lmf.svc.cluster.local:9012"
  LMF_SERVICES_ASSISTANCEDATA:  "assistance-data.lmf.svc.cluster.local:9010"
  LMF_SERVICES_EVENTMANAGER:    "event-manager.lmf.svc.cluster.local:9011"

  # Server config
  LMF_SBI_IPV4: "172.21.0.2" # this should match the ClusterIP of the sbi-gateway service
  LMF_SBI_PORT: "3000" # this should match the NodePort of the sbi-gateway service
  LMF_SERVER_PORT: "8000"
  LMF_GRPC_PORT:   "9000"


  LMF_NF_INSTANCE_ID: "a1b2c3d4-0000-0000-0000-lmf000000001"
  LMF_MCC: "404" 
  LMF_MNC: "30"