// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: lmf_protocol.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LppMessageType per TS 36.355
type LppMessageType int32

const (
	LppMessageType_LPP_MSG_UNSPECIFIED                  LppMessageType = 0
	LppMessageType_LPP_MSG_REQUEST_CAPABILITIES         LppMessageType = 1
	LppMessageType_LPP_MSG_PROVIDE_CAPABILITIES         LppMessageType = 2
	LppMessageType_LPP_MSG_REQUEST_ASSISTANCE_DATA      LppMessageType = 3
	LppMessageType_LPP_MSG_PROVIDE_ASSISTANCE_DATA      LppMessageType = 4
	LppMessageType_LPP_MSG_REQUEST_LOCATION_INFORMATION LppMessageType = 5
	LppMessageType_LPP_MSG_PROVIDE_LOCATION_INFORMATION LppMessageType = 6
	LppMessageType_LPP_MSG_ABORT                        LppMessageType = 7
)

// Enum value maps for LppMessageType.
var (
	LppMessageType_name = map[int32]string{
		0: "LPP_MSG_UNSPECIFIED",
		1: "LPP_MSG_REQUEST_CAPABILITIES",
		2: "LPP_MSG_PROVIDE_CAPABILITIES",
		3: "LPP_MSG_REQUEST_ASSISTANCE_DATA",
		4: "LPP_MSG_PROVIDE_ASSISTANCE_DATA",
		5: "LPP_MSG_REQUEST_LOCATION_INFORMATION",
		6: "LPP_MSG_PROVIDE_LOCATION_INFORMATION",
		7: "LPP_MSG_ABORT",
	}
	LppMessageType_value = map[string]int32{
		"LPP_MSG_UNSPECIFIED":                  0,
		"LPP_MSG_REQUEST_CAPABILITIES":         1,
		"LPP_MSG_PROVIDE_CAPABILITIES":         2,
		"LPP_MSG_REQUEST_ASSISTANCE_DATA":      3,
		"LPP_MSG_PROVIDE_ASSISTANCE_DATA":      4,
		"LPP_MSG_REQUEST_LOCATION_INFORMATION": 5,
		"LPP_MSG_PROVIDE_LOCATION_INFORMATION": 6,
		"LPP_MSG_ABORT":                        7,
	}
)

func (x LppMessageType) Enum() *LppMessageType {
	p := new(LppMessageType)
	*p = x
	return p
}

func (x LppMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LppMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_lmf_protocol_proto_enumTypes[0].Descriptor()
}

func (LppMessageType) Type() protoreflect.EnumType {
	return &file_lmf_protocol_proto_enumTypes[0]
}

func (x LppMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LppMessageType.Descriptor instead.
func (LppMessageType) EnumDescriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{0}
}

// NrppaProcedure per TS 38.455
type NrppaProcedure int32

const (
	NrppaProcedure_NRPPA_PROCEDURE_UNSPECIFIED                      NrppaProcedure = 0
	NrppaProcedure_NRPPA_PROCEDURE_ECID_MEASUREMENT_INITIATION      NrppaProcedure = 1
	NrppaProcedure_NRPPA_PROCEDURE_POSITIONING_INFORMATION_EXCHANGE NrppaProcedure = 2
	NrppaProcedure_NRPPA_PROCEDURE_MEASUREMENT_REPORTING            NrppaProcedure = 3
	NrppaProcedure_NRPPA_PROCEDURE_TRP_INFORMATION_EXCHANGE         NrppaProcedure = 4
	NrppaProcedure_NRPPA_PROCEDURE_POSITIONING_ACTIVATION           NrppaProcedure = 5
	NrppaProcedure_NRPPA_PROCEDURE_SRS_CONFIGURATION_EXCHANGE       NrppaProcedure = 6
)

// Enum value maps for NrppaProcedure.
var (
	NrppaProcedure_name = map[int32]string{
		0: "NRPPA_PROCEDURE_UNSPECIFIED",
		1: "NRPPA_PROCEDURE_ECID_MEASUREMENT_INITIATION",
		2: "NRPPA_PROCEDURE_POSITIONING_INFORMATION_EXCHANGE",
		3: "NRPPA_PROCEDURE_MEASUREMENT_REPORTING",
		4: "NRPPA_PROCEDURE_TRP_INFORMATION_EXCHANGE",
		5: "NRPPA_PROCEDURE_POSITIONING_ACTIVATION",
		6: "NRPPA_PROCEDURE_SRS_CONFIGURATION_EXCHANGE",
	}
	NrppaProcedure_value = map[string]int32{
		"NRPPA_PROCEDURE_UNSPECIFIED":                      0,
		"NRPPA_PROCEDURE_ECID_MEASUREMENT_INITIATION":      1,
		"NRPPA_PROCEDURE_POSITIONING_INFORMATION_EXCHANGE": 2,
		"NRPPA_PROCEDURE_MEASUREMENT_REPORTING":            3,
		"NRPPA_PROCEDURE_TRP_INFORMATION_EXCHANGE":         4,
		"NRPPA_PROCEDURE_POSITIONING_ACTIVATION":           5,
		"NRPPA_PROCEDURE_SRS_CONFIGURATION_EXCHANGE":       6,
	}
)

func (x NrppaProcedure) Enum() *NrppaProcedure {
	p := new(NrppaProcedure)
	*p = x
	return p
}

func (x NrppaProcedure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NrppaProcedure) Descriptor() protoreflect.EnumDescriptor {
	return file_lmf_protocol_proto_enumTypes[1].Descriptor()
}

func (NrppaProcedure) Type() protoreflect.EnumType {
	return &file_lmf_protocol_proto_enumTypes[1]
}

func (x NrppaProcedure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NrppaProcedure.Descriptor instead.
func (NrppaProcedure) EnumDescriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{1}
}

// LppCapabilities from UE ProvideCapabilities
type LppCapabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GnssSupported       bool                   `protobuf:"varint,1,opt,name=gnss_supported,json=gnssSupported,proto3" json:"gnss_supported,omitempty"`
	GnssConstellations  []string               `protobuf:"bytes,2,rep,name=gnss_constellations,json=gnssConstellations,proto3" json:"gnss_constellations,omitempty"`
	DlTdoaSupported     bool                   `protobuf:"varint,3,opt,name=dl_tdoa_supported,json=dlTdoaSupported,proto3" json:"dl_tdoa_supported,omitempty"`
	PrsTimingSupported  bool                   `protobuf:"varint,4,opt,name=prs_timing_supported,json=prsTimingSupported,proto3" json:"prs_timing_supported,omitempty"`
	MultiRttSupported   bool                   `protobuf:"varint,5,opt,name=multi_rtt_supported,json=multiRttSupported,proto3" json:"multi_rtt_supported,omitempty"`
	WlanSupported       bool                   `protobuf:"varint,6,opt,name=wlan_supported,json=wlanSupported,proto3" json:"wlan_supported,omitempty"`
	BluetoothSupported  bool                   `protobuf:"varint,7,opt,name=bluetooth_supported,json=bluetoothSupported,proto3" json:"bluetooth_supported,omitempty"`
	BarometricSupported bool                   `protobuf:"varint,8,opt,name=barometric_supported,json=barometricSupported,proto3" json:"barometric_supported,omitempty"`
	EcidSupported       bool                   `protobuf:"varint,9,opt,name=ecid_supported,json=ecidSupported,proto3" json:"ecid_supported,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LppCapabilities) Reset() {
	*x = LppCapabilities{}
	mi := &file_lmf_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LppCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LppCapabilities) ProtoMessage() {}

func (x *LppCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LppCapabilities.ProtoReflect.Descriptor instead.
func (*LppCapabilities) Descriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *LppCapabilities) GetGnssSupported() bool {
	if x != nil {
		return x.GnssSupported
	}
	return false
}

func (x *LppCapabilities) GetGnssConstellations() []string {
	if x != nil {
		return x.GnssConstellations
	}
	return nil
}

func (x *LppCapabilities) GetDlTdoaSupported() bool {
	if x != nil {
		return x.DlTdoaSupported
	}
	return false
}

func (x *LppCapabilities) GetPrsTimingSupported() bool {
	if x != nil {
		return x.PrsTimingSupported
	}
	return false
}

func (x *LppCapabilities) GetMultiRttSupported() bool {
	if x != nil {
		return x.MultiRttSupported
	}
	return false
}

func (x *LppCapabilities) GetWlanSupported() bool {
	if x != nil {
		return x.WlanSupported
	}
	return false
}

func (x *LppCapabilities) GetBluetoothSupported() bool {
	if x != nil {
		return x.BluetoothSupported
	}
	return false
}

func (x *LppCapabilities) GetBarometricSupported() bool {
	if x != nil {
		return x.BarometricSupported
	}
	return false
}

func (x *LppCapabilities) GetEcidSupported() bool {
	if x != nil {
		return x.EcidSupported
	}
	return false
}

// SendLppRequest sends an LPP message to a UE via AMF
type SendLppRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Supi           string                 `protobuf:"bytes,1,opt,name=supi,proto3" json:"supi,omitempty"`
	AmfInstanceId  string                 `protobuf:"bytes,2,opt,name=amf_instance_id,json=amfInstanceId,proto3" json:"amf_instance_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageType    LppMessageType         `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=lmf.v1.LppMessageType" json:"message_type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // Encoded LPP message body
	SequenceNumber int32                  `protobuf:"varint,6,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	AckRequested   bool                   `protobuf:"varint,7,opt,name=ack_requested,json=ackRequested,proto3" json:"ack_requested,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendLppRequest) Reset() {
	*x = SendLppRequest{}
	mi := &file_lmf_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLppRequest) ProtoMessage() {}

func (x *SendLppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLppRequest.ProtoReflect.Descriptor instead.
func (*SendLppRequest) Descriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *SendLppRequest) GetSupi() string {
	if x != nil {
		return x.Supi
	}
	return ""
}

func (x *SendLppRequest) GetAmfInstanceId() string {
	if x != nil {
		return x.AmfInstanceId
	}
	return ""
}

func (x *SendLppRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendLppRequest) GetMessageType() LppMessageType {
	if x != nil {
		return x.MessageType
	}
	return LppMessageType_LPP_MSG_UNSPECIFIED
}

func (x *SendLppRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendLppRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *SendLppRequest) GetAckRequested() bool {
	if x != nil {
		return x.AckRequested
	}
	return false
}

// SendLppResponse carries the UE's LPP response
type SendLppResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResponseType   LppMessageType         `protobuf:"varint,1,opt,name=response_type,json=responseType,proto3,enum=lmf.v1.LppMessageType" json:"response_type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendLppResponse) Reset() {
	*x = SendLppResponse{}
	mi := &file_lmf_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLppResponse) ProtoMessage() {}

func (x *SendLppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLppResponse.ProtoReflect.Descriptor instead.
func (*SendLppResponse) Descriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *SendLppResponse) GetResponseType() LppMessageType {
	if x != nil {
		return x.ResponseType
	}
	return LppMessageType_LPP_MSG_UNSPECIFIED
}

func (x *SendLppResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendLppResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *SendLppResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SendNrppaRequest sends an NRPPa message to a gNB via AMF
type SendNrppaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellNci       string                 `protobuf:"bytes,1,opt,name=cell_nci,json=cellNci,proto3" json:"cell_nci,omitempty"`
	AmfInstanceId string                 `protobuf:"bytes,2,opt,name=amf_instance_id,json=amfInstanceId,proto3" json:"amf_instance_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Procedure     NrppaProcedure         `protobuf:"varint,4,opt,name=procedure,proto3,enum=lmf.v1.NrppaProcedure" json:"procedure,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNrppaRequest) Reset() {
	*x = SendNrppaRequest{}
	mi := &file_lmf_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNrppaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNrppaRequest) ProtoMessage() {}

func (x *SendNrppaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNrppaRequest.ProtoReflect.Descriptor instead.
func (*SendNrppaRequest) Descriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *SendNrppaRequest) GetCellNci() string {
	if x != nil {
		return x.CellNci
	}
	return ""
}

func (x *SendNrppaRequest) GetAmfInstanceId() string {
	if x != nil {
		return x.AmfInstanceId
	}
	return ""
}

func (x *SendNrppaRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendNrppaRequest) GetProcedure() NrppaProcedure {
	if x != nil {
		return x.Procedure
	}
	return NrppaProcedure_NRPPA_PROCEDURE_UNSPECIFIED
}

func (x *SendNrppaRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SendNrppaResponse carries the gNB's NRPPa response
type SendNrppaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Procedure     NrppaProcedure         `protobuf:"varint,1,opt,name=procedure,proto3,enum=lmf.v1.NrppaProcedure" json:"procedure,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNrppaResponse) Reset() {
	*x = SendNrppaResponse{}
	mi := &file_lmf_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNrppaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNrppaResponse) ProtoMessage() {}

func (x *SendNrppaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNrppaResponse.ProtoReflect.Descriptor instead.
func (*SendNrppaResponse) Descriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *SendNrppaResponse) GetProcedure() NrppaProcedure {
	if x != nil {
		return x.Procedure
	}
	return NrppaProcedure_NRPPA_PROCEDURE_UNSPECIFIED
}

func (x *SendNrppaResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendNrppaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetUeCapabilitiesRequest retrieves cached UE caps
type GetUeCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supi          string                 `protobuf:"bytes,1,opt,name=supi,proto3" json:"supi,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUeCapabilitiesRequest) Reset() {
	*x = GetUeCapabilitiesRequest{}
	mi := &file_lmf_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUeCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUeCapabilitiesRequest) ProtoMessage() {}

func (x *GetUeCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUeCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetUeCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *GetUeCapabilitiesRequest) GetSupi() string {
	if x != nil {
		return x.Supi
	}
	return ""
}

func (x *GetUeCapabilitiesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GetUeCapabilitiesResponse carries capabilities
type GetUeCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *UeCapabilities        `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	FromCache     bool                   `protobuf:"varint,2,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUeCapabilitiesResponse) Reset() {
	*x = GetUeCapabilitiesResponse{}
	mi := &file_lmf_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUeCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUeCapabilitiesResponse) ProtoMessage() {}

func (x *GetUeCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUeCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetUeCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *GetUeCapabilitiesResponse) GetCapabilities() *UeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetUeCapabilitiesResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

func (x *GetUeCapabilitiesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TrpInfo describes a Transmission Reception Point
type TrpInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrpId         string                 `protobuf:"bytes,1,opt,name=trp_id,json=trpId,proto3" json:"trp_id,omitempty"`
	Nci           string                 `protobuf:"bytes,2,opt,name=nci,proto3" json:"nci,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      float64                `protobuf:"fixed64,5,opt,name=altitude,proto3" json:"altitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrpInfo) Reset() {
	*x = TrpInfo{}
	mi := &file_lmf_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrpInfo) ProtoMessage() {}

func (x *TrpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrpInfo.ProtoReflect.Descriptor instead.
func (*TrpInfo) Descriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *TrpInfo) GetTrpId() string {
	if x != nil {
		return x.TrpId
	}
	return ""
}

func (x *TrpInfo) GetNci() string {
	if x != nil {
		return x.Nci
	}
	return ""
}

func (x *TrpInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TrpInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TrpInfo) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

// NrppaMeasurementResult holds NRPPa E-CID measurement results
type NrppaMeasurementResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServingCellNci   string                 `protobuf:"bytes,1,opt,name=serving_cell_nci,json=servingCellNci,proto3" json:"serving_cell_nci,omitempty"`
	UeRxTxTimeDiff   float64                `protobuf:"fixed64,2,opt,name=ue_rx_tx_time_diff,json=ueRxTxTimeDiff,proto3" json:"ue_rx_tx_time_diff,omitempty"`
	GnbRxTxTimeDiff  float64                `protobuf:"fixed64,3,opt,name=gnb_rx_tx_time_diff,json=gnbRxTxTimeDiff,proto3" json:"gnb_rx_tx_time_diff,omitempty"`
	TimingAdvance    int32                  `protobuf:"varint,4,opt,name=timing_advance,json=timingAdvance,proto3" json:"timing_advance,omitempty"`
	RsrpMeasurements []*RsrpEntry           `protobuf:"bytes,5,rep,name=rsrp_measurements,json=rsrpMeasurements,proto3" json:"rsrp_measurements,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NrppaMeasurementResult) Reset() {
	*x = NrppaMeasurementResult{}
	mi := &file_lmf_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NrppaMeasurementResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NrppaMeasurementResult) ProtoMessage() {}

func (x *NrppaMeasurementResult) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NrppaMeasurementResult.ProtoReflect.Descriptor instead.
func (*NrppaMeasurementResult) Descriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *NrppaMeasurementResult) GetServingCellNci() string {
	if x != nil {
		return x.ServingCellNci
	}
	return ""
}

func (x *NrppaMeasurementResult) GetUeRxTxTimeDiff() float64 {
	if x != nil {
		return x.UeRxTxTimeDiff
	}
	return 0
}

func (x *NrppaMeasurementResult) GetGnbRxTxTimeDiff() float64 {
	if x != nil {
		return x.GnbRxTxTimeDiff
	}
	return 0
}

func (x *NrppaMeasurementResult) GetTimingAdvance() int32 {
	if x != nil {
		return x.TimingAdvance
	}
	return 0
}

func (x *NrppaMeasurementResult) GetRsrpMeasurements() []*RsrpEntry {
	if x != nil {
		return x.RsrpMeasurements
	}
	return nil
}

// RsrpEntry (reused here for proto clarity)
type RsrpEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellNci       string                 `protobuf:"bytes,1,opt,name=cell_nci,json=cellNci,proto3" json:"cell_nci,omitempty"`
	RsrpDbm       float64                `protobuf:"fixed64,2,opt,name=rsrp_dbm,json=rsrpDbm,proto3" json:"rsrp_dbm,omitempty"`
	RsrqDb        float64                `protobuf:"fixed64,3,opt,name=rsrq_db,json=rsrqDb,proto3" json:"rsrq_db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RsrpEntry) Reset() {
	*x = RsrpEntry{}
	mi := &file_lmf_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RsrpEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsrpEntry) ProtoMessage() {}

func (x *RsrpEntry) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsrpEntry.ProtoReflect.Descriptor instead.
func (*RsrpEntry) Descriptor() ([]byte, []int) {
	return file_lmf_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *RsrpEntry) GetCellNci() string {
	if x != nil {
		return x.CellNci
	}
	return ""
}

func (x *RsrpEntry) GetRsrpDbm() float64 {
	if x != nil {
		return x.RsrpDbm
	}
	return 0
}

func (x *RsrpEntry) GetRsrqDb() float64 {
	if x != nil {
		return x.RsrqDb
	}
	return 0
}

var File_lmf_protocol_proto protoreflect.FileDescriptor

const file_lmf_protocol_proto_rawDesc = "" +
	"\n" +
	"\x12lmf_protocol.proto\x12\x06lmf.v1\x1a\x10lmf_common.proto\"\xa9\x03\n" +
	"\x0fLppCapabilities\x12%\n" +
	"\x0egnss_supported\x18\x01 \x01(\bR\rgnssSupported\x12/\n" +
	"\x13gnss_constellations\x18\x02 \x03(\tR\x12gnssConstellations\x12*\n" +
	"\x11dl_tdoa_supported\x18\x03 \x01(\bR\x0fdlTdoaSupported\x120\n" +
	"\x14prs_timing_supported\x18\x04 \x01(\bR\x12prsTimingSupported\x12.\n" +
	"\x13multi_rtt_supported\x18\x05 \x01(\bR\x11multiRttSupported\x12%\n" +
	"\x0ewlan_supported\x18\x06 \x01(\bR\rwlanSupported\x12/\n" +
	"\x13bluetooth_supported\x18\a \x01(\bR\x12bluetoothSupported\x121\n" +
	"\x14barometric_supported\x18\b \x01(\bR\x13barometricSupported\x12%\n" +
	"\x0eecid_supported\x18\t \x01(\bR\recidSupported\"\x8e\x02\n" +
	"\x0eSendLppRequest\x12\x12\n" +
	"\x04supi\x18\x01 \x01(\tR\x04supi\x12&\n" +
	"\x0famf_instance_id\x18\x02 \x01(\tR\ramfInstanceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x129\n" +
	"\fmessage_type\x18\x04 \x01(\x0e2\x16.lmf.v1.LppMessageTypeR\vmessageType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12'\n" +
	"\x0fsequence_number\x18\x06 \x01(\x05R\x0esequenceNumber\x12#\n" +
	"\rack_requested\x18\a \x01(\bR\fackRequested\"\xa7\x01\n" +
	"\x0fSendLppResponse\x12;\n" +
	"\rresponse_type\x18\x01 \x01(\x0e2\x16.lmf.v1.LppMessageTypeR\fresponseType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x05R\x0esequenceNumber\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xc4\x01\n" +
	"\x10SendNrppaRequest\x12\x19\n" +
	"\bcell_nci\x18\x01 \x01(\tR\acellNci\x12&\n" +
	"\x0famf_instance_id\x18\x02 \x01(\tR\ramfInstanceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x124\n" +
	"\tprocedure\x18\x04 \x01(\x0e2\x16.lmf.v1.NrppaProcedureR\tprocedure\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"y\n" +
	"\x11SendNrppaResponse\x124\n" +
	"\tprocedure\x18\x01 \x01(\x0e2\x16.lmf.v1.NrppaProcedureR\tprocedure\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"M\n" +
	"\x18GetUeCapabilitiesRequest\x12\x12\n" +
	"\x04supi\x18\x01 \x01(\tR\x04supi\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x8c\x01\n" +
	"\x19GetUeCapabilitiesResponse\x12:\n" +
	"\fcapabilities\x18\x01 \x01(\v2\x16.lmf.v1.UeCapabilitiesR\fcapabilities\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x02 \x01(\bR\tfromCache\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x88\x01\n" +
	"\aTrpInfo\x12\x15\n" +
	"\x06trp_id\x18\x01 \x01(\tR\x05trpId\x12\x10\n" +
	"\x03nci\x18\x02 \x01(\tR\x03nci\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x05 \x01(\x01R\baltitude\"\x83\x02\n" +
	"\x16NrppaMeasurementResult\x12(\n" +
	"\x10serving_cell_nci\x18\x01 \x01(\tR\x0eservingCellNci\x12*\n" +
	"\x12ue_rx_tx_time_diff\x18\x02 \x01(\x01R\x0eueRxTxTimeDiff\x12,\n" +
	"\x13gnb_rx_tx_time_diff\x18\x03 \x01(\x01R\x0fgnbRxTxTimeDiff\x12%\n" +
	"\x0etiming_advance\x18\x04 \x01(\x05R\rtimingAdvance\x12>\n" +
	"\x11rsrp_measurements\x18\x05 \x03(\v2\x11.lmf.v1.RsrpEntryR\x10rsrpMeasurements\"Z\n" +
	"\tRsrpEntry\x12\x19\n" +
	"\bcell_nci\x18\x01 \x01(\tR\acellNci\x12\x19\n" +
	"\brsrp_dbm\x18\x02 \x01(\x01R\arsrpDbm\x12\x17\n" +
	"\arsrq_db\x18\x03 \x01(\x01R\x06rsrqDb*\x9e\x02\n" +
	"\x0eLppMessageType\x12\x17\n" +
	"\x13LPP_MSG_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cLPP_MSG_REQUEST_CAPABILITIES\x10\x01\x12 \n" +
	"\x1cLPP_MSG_PROVIDE_CAPABILITIES\x10\x02\x12#\n" +
	"\x1fLPP_MSG_REQUEST_ASSISTANCE_DATA\x10\x03\x12#\n" +
	"\x1fLPP_MSG_PROVIDE_ASSISTANCE_DATA\x10\x04\x12(\n" +
	"$LPP_MSG_REQUEST_LOCATION_INFORMATION\x10\x05\x12(\n" +
	"$LPP_MSG_PROVIDE_LOCATION_INFORMATION\x10\x06\x12\x11\n" +
	"\rLPP_MSG_ABORT\x10\a*\xcd\x02\n" +
	"\x0eNrppaProcedure\x12\x1f\n" +
	"\x1bNRPPA_PROCEDURE_UNSPECIFIED\x10\x00\x12/\n" +
	"+NRPPA_PROCEDURE_ECID_MEASUREMENT_INITIATION\x10\x01\x124\n" +
	"0NRPPA_PROCEDURE_POSITIONING_INFORMATION_EXCHANGE\x10\x02\x12)\n" +
	"%NRPPA_PROCEDURE_MEASUREMENT_REPORTING\x10\x03\x12,\n" +
	"(NRPPA_PROCEDURE_TRP_INFORMATION_EXCHANGE\x10\x04\x12*\n" +
	"&NRPPA_PROCEDURE_POSITIONING_ACTIVATION\x10\x05\x12.\n" +
	"*NRPPA_PROCEDURE_SRS_CONFIGURATION_EXCHANGE\x10\x062\xf0\x01\n" +
	"\x16ProtocolHandlerService\x12:\n" +
	"\aSendLpp\x12\x16.lmf.v1.SendLppRequest\x1a\x17.lmf.v1.SendLppResponse\x12@\n" +
	"\tSendNrppa\x12\x18.lmf.v1.SendNrppaRequest\x1a\x19.lmf.v1.SendNrppaResponse\x12X\n" +
	"\x11GetUeCapabilities\x12 .lmf.v1.GetUeCapabilitiesRequest\x1a!.lmf.v1.GetUeCapabilitiesResponseB Z\x1egithub.com/5g-lmf/common/pb;pbb\x06proto3"

var (
	file_lmf_protocol_proto_rawDescOnce sync.Once
	file_lmf_protocol_proto_rawDescData []byte
)

func file_lmf_protocol_proto_rawDescGZIP() []byte {
	file_lmf_protocol_proto_rawDescOnce.Do(func() {
		file_lmf_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lmf_protocol_proto_rawDesc), len(file_lmf_protocol_proto_rawDesc)))
	})
	return file_lmf_protocol_proto_rawDescData
}

var file_lmf_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_lmf_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_lmf_protocol_proto_goTypes = []any{
	(LppMessageType)(0),               // 0: lmf.v1.LppMessageType
	(NrppaProcedure)(0),               // 1: lmf.v1.NrppaProcedure
	(*LppCapabilities)(nil),           // 2: lmf.v1.LppCapabilities
	(*SendLppRequest)(nil),            // 3: lmf.v1.SendLppRequest
	(*SendLppResponse)(nil),           // 4: lmf.v1.SendLppResponse
	(*SendNrppaRequest)(nil),          // 5: lmf.v1.SendNrppaRequest
	(*SendNrppaResponse)(nil),         // 6: lmf.v1.SendNrppaResponse
	(*GetUeCapabilitiesRequest)(nil),  // 7: lmf.v1.GetUeCapabilitiesRequest
	(*GetUeCapabilitiesResponse)(nil), // 8: lmf.v1.GetUeCapabilitiesResponse
	(*TrpInfo)(nil),                   // 9: lmf.v1.TrpInfo
	(*NrppaMeasurementResult)(nil),    // 10: lmf.v1.NrppaMeasurementResult
	(*RsrpEntry)(nil),                 // 11: lmf.v1.RsrpEntry
	(*UeCapabilities)(nil),            // 12: lmf.v1.UeCapabilities
}
var file_lmf_protocol_proto_depIdxs = []int32{
	0,  // 0: lmf.v1.SendLppRequest.message_type:type_name -> lmf.v1.LppMessageType
	0,  // 1: lmf.v1.SendLppResponse.response_type:type_name -> lmf.v1.LppMessageType
	1,  // 2: lmf.v1.SendNrppaRequest.procedure:type_name -> lmf.v1.NrppaProcedure
	1,  // 3: lmf.v1.SendNrppaResponse.procedure:type_name -> lmf.v1.NrppaProcedure
	12, // 4: lmf.v1.GetUeCapabilitiesResponse.capabilities:type_name -> lmf.v1.UeCapabilities
	11, // 5: lmf.v1.NrppaMeasurementResult.rsrp_measurements:type_name -> lmf.v1.RsrpEntry
	3,  // 6: lmf.v1.ProtocolHandlerService.SendLpp:input_type -> lmf.v1.SendLppRequest
	5,  // 7: lmf.v1.ProtocolHandlerService.SendNrppa:input_type -> lmf.v1.SendNrppaRequest
	7,  // 8: lmf.v1.ProtocolHandlerService.GetUeCapabilities:input_type -> lmf.v1.GetUeCapabilitiesRequest
	4,  // 9: lmf.v1.ProtocolHandlerService.SendLpp:output_type -> lmf.v1.SendLppResponse
	6,  // 10: lmf.v1.ProtocolHandlerService.SendNrppa:output_type -> lmf.v1.SendNrppaResponse
	8,  // 11: lmf.v1.ProtocolHandlerService.GetUeCapabilities:output_type -> lmf.v1.GetUeCapabilitiesResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_lmf_protocol_proto_init() }
func file_lmf_protocol_proto_init() {
	if File_lmf_protocol_proto != nil {
		return
	}
	file_lmf_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lmf_protocol_proto_rawDesc), len(file_lmf_protocol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lmf_protocol_proto_goTypes,
		DependencyIndexes: file_lmf_protocol_proto_depIdxs,
		EnumInfos:         file_lmf_protocol_proto_enumTypes,
		MessageInfos:      file_lmf_protocol_proto_msgTypes,
	}.Build()
	File_lmf_protocol_proto = out.File
	file_lmf_protocol_proto_goTypes = nil
	file_lmf_protocol_proto_depIdxs = nil
}
