// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: lmf_location.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LocationRequest for gRPC internal location determination
type LocationRequestMsg struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Supi              string                 `protobuf:"bytes,2,opt,name=supi,proto3" json:"supi,omitempty"`
	Pei               string                 `protobuf:"bytes,3,opt,name=pei,proto3" json:"pei,omitempty"`
	Gpsi              string                 `protobuf:"bytes,4,opt,name=gpsi,proto3" json:"gpsi,omitempty"`
	LcsQos            *LcsQoS                `protobuf:"bytes,5,opt,name=lcs_qos,json=lcsQos,proto3" json:"lcs_qos,omitempty"`
	PreferredMethod   PositioningMethod      `protobuf:"varint,6,opt,name=preferred_method,json=preferredMethod,proto3,enum=lmf.v1.PositioningMethod" json:"preferred_method,omitempty"`
	AdditionalMethods []PositioningMethod    `protobuf:"varint,7,rep,packed,name=additional_methods,json=additionalMethods,proto3,enum=lmf.v1.PositioningMethod" json:"additional_methods,omitempty"`
	AmfInstanceId     string                 `protobuf:"bytes,8,opt,name=amf_instance_id,json=amfInstanceId,proto3" json:"amf_instance_id,omitempty"`
	LcsClientType     LcsClientType          `protobuf:"varint,9,opt,name=lcs_client_type,json=lcsClientType,proto3,enum=lmf.v1.LcsClientType" json:"lcs_client_type,omitempty"`
	HgmlcCallbackUri  string                 `protobuf:"bytes,10,opt,name=hgmlc_callback_uri,json=hgmlcCallbackUri,proto3" json:"hgmlc_callback_uri,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LocationRequestMsg) Reset() {
	*x = LocationRequestMsg{}
	mi := &file_lmf_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationRequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationRequestMsg) ProtoMessage() {}

func (x *LocationRequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationRequestMsg.ProtoReflect.Descriptor instead.
func (*LocationRequestMsg) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{0}
}

func (x *LocationRequestMsg) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LocationRequestMsg) GetSupi() string {
	if x != nil {
		return x.Supi
	}
	return ""
}

func (x *LocationRequestMsg) GetPei() string {
	if x != nil {
		return x.Pei
	}
	return ""
}

func (x *LocationRequestMsg) GetGpsi() string {
	if x != nil {
		return x.Gpsi
	}
	return ""
}

func (x *LocationRequestMsg) GetLcsQos() *LcsQoS {
	if x != nil {
		return x.LcsQos
	}
	return nil
}

func (x *LocationRequestMsg) GetPreferredMethod() PositioningMethod {
	if x != nil {
		return x.PreferredMethod
	}
	return PositioningMethod_POSITIONING_METHOD_UNSPECIFIED
}

func (x *LocationRequestMsg) GetAdditionalMethods() []PositioningMethod {
	if x != nil {
		return x.AdditionalMethods
	}
	return nil
}

func (x *LocationRequestMsg) GetAmfInstanceId() string {
	if x != nil {
		return x.AmfInstanceId
	}
	return ""
}

func (x *LocationRequestMsg) GetLcsClientType() LcsClientType {
	if x != nil {
		return x.LcsClientType
	}
	return LcsClientType_LCS_CLIENT_TYPE_UNSPECIFIED
}

func (x *LocationRequestMsg) GetHgmlcCallbackUri() string {
	if x != nil {
		return x.HgmlcCallbackUri
	}
	return ""
}

// LocationResponse for gRPC internal result
type LocationResponseMsg struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	SessionId         string                      `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LocationEstimate  *LocationEstimate           `protobuf:"bytes,2,opt,name=location_estimate,json=locationEstimate,proto3" json:"location_estimate,omitempty"`
	AccuracyIndicator AccuracyFulfilmentIndicator `protobuf:"varint,3,opt,name=accuracy_indicator,json=accuracyIndicator,proto3,enum=lmf.v1.AccuracyFulfilmentIndicator" json:"accuracy_indicator,omitempty"`
	VelocityEstimate  *VelocityEstimate           `protobuf:"bytes,4,opt,name=velocity_estimate,json=velocityEstimate,proto3" json:"velocity_estimate,omitempty"`
	PositioningData   []*PositioningDataEntry     `protobuf:"bytes,5,rep,name=positioning_data,json=positioningData,proto3" json:"positioning_data,omitempty"`
	TimestampUnixMs   int64                       `protobuf:"varint,6,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	ErrorCode         string                      `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorDetail       string                      `protobuf:"bytes,8,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LocationResponseMsg) Reset() {
	*x = LocationResponseMsg{}
	mi := &file_lmf_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationResponseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationResponseMsg) ProtoMessage() {}

func (x *LocationResponseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationResponseMsg.ProtoReflect.Descriptor instead.
func (*LocationResponseMsg) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{1}
}

func (x *LocationResponseMsg) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LocationResponseMsg) GetLocationEstimate() *LocationEstimate {
	if x != nil {
		return x.LocationEstimate
	}
	return nil
}

func (x *LocationResponseMsg) GetAccuracyIndicator() AccuracyFulfilmentIndicator {
	if x != nil {
		return x.AccuracyIndicator
	}
	return AccuracyFulfilmentIndicator_ACCURACY_FULFILMENT_UNSPECIFIED
}

func (x *LocationResponseMsg) GetVelocityEstimate() *VelocityEstimate {
	if x != nil {
		return x.VelocityEstimate
	}
	return nil
}

func (x *LocationResponseMsg) GetPositioningData() []*PositioningDataEntry {
	if x != nil {
		return x.PositioningData
	}
	return nil
}

func (x *LocationResponseMsg) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *LocationResponseMsg) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *LocationResponseMsg) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

// PositioningDataEntry records method usage
type PositioningDataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PosMethod     PositioningMethod      `protobuf:"varint,1,opt,name=pos_method,json=posMethod,proto3,enum=lmf.v1.PositioningMethod" json:"pos_method,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositioningDataEntry) Reset() {
	*x = PositioningDataEntry{}
	mi := &file_lmf_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositioningDataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositioningDataEntry) ProtoMessage() {}

func (x *PositioningDataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositioningDataEntry.ProtoReflect.Descriptor instead.
func (*PositioningDataEntry) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{2}
}

func (x *PositioningDataEntry) GetPosMethod() PositioningMethod {
	if x != nil {
		return x.PosMethod
	}
	return PositioningMethod_POSITIONING_METHOD_UNSPECIFIED
}

func (x *PositioningDataEntry) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// CancelRequest for cancelling a location session
type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Supi          string                 `protobuf:"bytes,2,opt,name=supi,proto3" json:"supi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_lmf_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{3}
}

func (x *CancelRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CancelRequest) GetSupi() string {
	if x != nil {
		return x.Supi
	}
	return ""
}

// CancelResponse confirms cancellation
type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_lmf_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{4}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SessionStatusRequest for status polling
type SessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusRequest) Reset() {
	*x = SessionStatusRequest{}
	mi := &file_lmf_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusRequest) ProtoMessage() {}

func (x *SessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusRequest.ProtoReflect.Descriptor instead.
func (*SessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{5}
}

func (x *SessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// SessionStatusResponse carries session status
type SessionStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status          SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=lmf.v1.SessionStatus" json:"status,omitempty"`
	StartedAtUnixMs int64                  `protobuf:"varint,3,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionStatusResponse) Reset() {
	*x = SessionStatusResponse{}
	mi := &file_lmf_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusResponse) ProtoMessage() {}

func (x *SessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusResponse.ProtoReflect.Descriptor instead.
func (*SessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{6}
}

func (x *SessionStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStatusResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *SessionStatusResponse) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

// Session CRUD messages
type SessionCreateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Supi              string                 `protobuf:"bytes,1,opt,name=supi,proto3" json:"supi,omitempty"`
	Pei               string                 `protobuf:"bytes,2,opt,name=pei,proto3" json:"pei,omitempty"`
	Gpsi              string                 `protobuf:"bytes,3,opt,name=gpsi,proto3" json:"gpsi,omitempty"`
	AmfInstanceId     string                 `protobuf:"bytes,4,opt,name=amf_instance_id,json=amfInstanceId,proto3" json:"amf_instance_id,omitempty"`
	LcsQos            *LcsQoS                `protobuf:"bytes,5,opt,name=lcs_qos,json=lcsQos,proto3" json:"lcs_qos,omitempty"`
	LcsClientType     LcsClientType          `protobuf:"varint,6,opt,name=lcs_client_type,json=lcsClientType,proto3,enum=lmf.v1.LcsClientType" json:"lcs_client_type,omitempty"`
	PositioningMethod PositioningMethod      `protobuf:"varint,7,opt,name=positioning_method,json=positioningMethod,proto3,enum=lmf.v1.PositioningMethod" json:"positioning_method,omitempty"`
	TtlSeconds        int64                  `protobuf:"varint,8,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionCreateRequest) Reset() {
	*x = SessionCreateRequest{}
	mi := &file_lmf_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreateRequest) ProtoMessage() {}

func (x *SessionCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreateRequest.ProtoReflect.Descriptor instead.
func (*SessionCreateRequest) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{7}
}

func (x *SessionCreateRequest) GetSupi() string {
	if x != nil {
		return x.Supi
	}
	return ""
}

func (x *SessionCreateRequest) GetPei() string {
	if x != nil {
		return x.Pei
	}
	return ""
}

func (x *SessionCreateRequest) GetGpsi() string {
	if x != nil {
		return x.Gpsi
	}
	return ""
}

func (x *SessionCreateRequest) GetAmfInstanceId() string {
	if x != nil {
		return x.AmfInstanceId
	}
	return ""
}

func (x *SessionCreateRequest) GetLcsQos() *LcsQoS {
	if x != nil {
		return x.LcsQos
	}
	return nil
}

func (x *SessionCreateRequest) GetLcsClientType() LcsClientType {
	if x != nil {
		return x.LcsClientType
	}
	return LcsClientType_LCS_CLIENT_TYPE_UNSPECIFIED
}

func (x *SessionCreateRequest) GetPositioningMethod() PositioningMethod {
	if x != nil {
		return x.PositioningMethod
	}
	return PositioningMethod_POSITIONING_METHOD_UNSPECIFIED
}

func (x *SessionCreateRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SessionCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreateResponse) Reset() {
	*x = SessionCreateResponse{}
	mi := &file_lmf_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreateResponse) ProtoMessage() {}

func (x *SessionCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreateResponse.ProtoReflect.Descriptor instead.
func (*SessionCreateResponse) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{8}
}

func (x *SessionCreateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionGetRequest) Reset() {
	*x = SessionGetRequest{}
	mi := &file_lmf_location_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionGetRequest) ProtoMessage() {}

func (x *SessionGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionGetRequest.ProtoReflect.Descriptor instead.
func (*SessionGetRequest) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{9}
}

func (x *SessionGetRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionGetResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Supi            string                 `protobuf:"bytes,2,opt,name=supi,proto3" json:"supi,omitempty"`
	Pei             string                 `protobuf:"bytes,3,opt,name=pei,proto3" json:"pei,omitempty"`
	AmfInstanceId   string                 `protobuf:"bytes,4,opt,name=amf_instance_id,json=amfInstanceId,proto3" json:"amf_instance_id,omitempty"`
	Status          SessionStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=lmf.v1.SessionStatus" json:"status,omitempty"`
	LcsQos          *LcsQoS                `protobuf:"bytes,6,opt,name=lcs_qos,json=lcsQos,proto3" json:"lcs_qos,omitempty"`
	LcsClientType   LcsClientType          `protobuf:"varint,7,opt,name=lcs_client_type,json=lcsClientType,proto3,enum=lmf.v1.LcsClientType" json:"lcs_client_type,omitempty"`
	StartedAtUnixMs int64                  `protobuf:"varint,8,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,9,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	Error           string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionGetResponse) Reset() {
	*x = SessionGetResponse{}
	mi := &file_lmf_location_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionGetResponse) ProtoMessage() {}

func (x *SessionGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionGetResponse.ProtoReflect.Descriptor instead.
func (*SessionGetResponse) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{10}
}

func (x *SessionGetResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionGetResponse) GetSupi() string {
	if x != nil {
		return x.Supi
	}
	return ""
}

func (x *SessionGetResponse) GetPei() string {
	if x != nil {
		return x.Pei
	}
	return ""
}

func (x *SessionGetResponse) GetAmfInstanceId() string {
	if x != nil {
		return x.AmfInstanceId
	}
	return ""
}

func (x *SessionGetResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *SessionGetResponse) GetLcsQos() *LcsQoS {
	if x != nil {
		return x.LcsQos
	}
	return nil
}

func (x *SessionGetResponse) GetLcsClientType() LcsClientType {
	if x != nil {
		return x.LcsClientType
	}
	return LcsClientType_LCS_CLIENT_TYPE_UNSPECIFIED
}

func (x *SessionGetResponse) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *SessionGetResponse) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *SessionGetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SessionUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NewStatus     SessionStatus          `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=lmf.v1.SessionStatus" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionUpdateRequest) Reset() {
	*x = SessionUpdateRequest{}
	mi := &file_lmf_location_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUpdateRequest) ProtoMessage() {}

func (x *SessionUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUpdateRequest.ProtoReflect.Descriptor instead.
func (*SessionUpdateRequest) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{11}
}

func (x *SessionUpdateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionUpdateRequest) GetNewStatus() SessionStatus {
	if x != nil {
		return x.NewStatus
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

type SessionUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionUpdateResponse) Reset() {
	*x = SessionUpdateResponse{}
	mi := &file_lmf_location_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUpdateResponse) ProtoMessage() {}

func (x *SessionUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUpdateResponse.ProtoReflect.Descriptor instead.
func (*SessionUpdateResponse) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{12}
}

func (x *SessionUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SessionDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionDeleteRequest) Reset() {
	*x = SessionDeleteRequest{}
	mi := &file_lmf_location_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDeleteRequest) ProtoMessage() {}

func (x *SessionDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDeleteRequest.ProtoReflect.Descriptor instead.
func (*SessionDeleteRequest) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{13}
}

func (x *SessionDeleteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionDeleteResponse) Reset() {
	*x = SessionDeleteResponse{}
	mi := &file_lmf_location_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDeleteResponse) ProtoMessage() {}

func (x *SessionDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDeleteResponse.ProtoReflect.Descriptor instead.
func (*SessionDeleteResponse) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{14}
}

func (x *SessionDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Method selection messages
type MethodSelectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UeCapabilities *UeCapabilities        `protobuf:"bytes,1,opt,name=ue_capabilities,json=ueCapabilities,proto3" json:"ue_capabilities,omitempty"`
	LcsQos         *LcsQoS                `protobuf:"bytes,2,opt,name=lcs_qos,json=lcsQos,proto3" json:"lcs_qos,omitempty"`
	IndoorHint     bool                   `protobuf:"varint,3,opt,name=indoor_hint,json=indoorHint,proto3" json:"indoor_hint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MethodSelectionRequest) Reset() {
	*x = MethodSelectionRequest{}
	mi := &file_lmf_location_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodSelectionRequest) ProtoMessage() {}

func (x *MethodSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodSelectionRequest.ProtoReflect.Descriptor instead.
func (*MethodSelectionRequest) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{15}
}

func (x *MethodSelectionRequest) GetUeCapabilities() *UeCapabilities {
	if x != nil {
		return x.UeCapabilities
	}
	return nil
}

func (x *MethodSelectionRequest) GetLcsQos() *LcsQoS {
	if x != nil {
		return x.LcsQos
	}
	return nil
}

func (x *MethodSelectionRequest) GetIndoorHint() bool {
	if x != nil {
		return x.IndoorHint
	}
	return false
}

type MethodSelectionResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SelectedMethod          PositioningMethod      `protobuf:"varint,1,opt,name=selected_method,json=selectedMethod,proto3,enum=lmf.v1.PositioningMethod" json:"selected_method,omitempty"`
	FallbackMethods         []PositioningMethod    `protobuf:"varint,2,rep,packed,name=fallback_methods,json=fallbackMethods,proto3,enum=lmf.v1.PositioningMethod" json:"fallback_methods,omitempty"`
	EstimatedAccuracyMeters float64                `protobuf:"fixed64,3,opt,name=estimated_accuracy_meters,json=estimatedAccuracyMeters,proto3" json:"estimated_accuracy_meters,omitempty"`
	EstimatedResponseMs     int32                  `protobuf:"varint,4,opt,name=estimated_response_ms,json=estimatedResponseMs,proto3" json:"estimated_response_ms,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MethodSelectionResponse) Reset() {
	*x = MethodSelectionResponse{}
	mi := &file_lmf_location_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodSelectionResponse) ProtoMessage() {}

func (x *MethodSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodSelectionResponse.ProtoReflect.Descriptor instead.
func (*MethodSelectionResponse) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{16}
}

func (x *MethodSelectionResponse) GetSelectedMethod() PositioningMethod {
	if x != nil {
		return x.SelectedMethod
	}
	return PositioningMethod_POSITIONING_METHOD_UNSPECIFIED
}

func (x *MethodSelectionResponse) GetFallbackMethods() []PositioningMethod {
	if x != nil {
		return x.FallbackMethods
	}
	return nil
}

func (x *MethodSelectionResponse) GetEstimatedAccuracyMeters() float64 {
	if x != nil {
		return x.EstimatedAccuracyMeters
	}
	return 0
}

func (x *MethodSelectionResponse) GetEstimatedResponseMs() int32 {
	if x != nil {
		return x.EstimatedResponseMs
	}
	return 0
}

// QoS evaluation messages
type QosEvaluateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestedQos     *LcsQoS                `protobuf:"bytes,1,opt,name=requested_qos,json=requestedQos,proto3" json:"requested_qos,omitempty"`
	AchievedEstimate *PositionEstimate      `protobuf:"bytes,2,opt,name=achieved_estimate,json=achievedEstimate,proto3" json:"achieved_estimate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QosEvaluateRequest) Reset() {
	*x = QosEvaluateRequest{}
	mi := &file_lmf_location_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QosEvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosEvaluateRequest) ProtoMessage() {}

func (x *QosEvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosEvaluateRequest.ProtoReflect.Descriptor instead.
func (*QosEvaluateRequest) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{17}
}

func (x *QosEvaluateRequest) GetRequestedQos() *LcsQoS {
	if x != nil {
		return x.RequestedQos
	}
	return nil
}

func (x *QosEvaluateRequest) GetAchievedEstimate() *PositionEstimate {
	if x != nil {
		return x.AchievedEstimate
	}
	return nil
}

type QosEvaluateResponse struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	Indicator            AccuracyFulfilmentIndicator `protobuf:"varint,1,opt,name=indicator,proto3,enum=lmf.v1.AccuracyFulfilmentIndicator" json:"indicator,omitempty"`
	ResponseTimeBreached bool                        `protobuf:"varint,2,opt,name=response_time_breached,json=responseTimeBreached,proto3" json:"response_time_breached,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QosEvaluateResponse) Reset() {
	*x = QosEvaluateResponse{}
	mi := &file_lmf_location_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QosEvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosEvaluateResponse) ProtoMessage() {}

func (x *QosEvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_location_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosEvaluateResponse.ProtoReflect.Descriptor instead.
func (*QosEvaluateResponse) Descriptor() ([]byte, []int) {
	return file_lmf_location_proto_rawDescGZIP(), []int{18}
}

func (x *QosEvaluateResponse) GetIndicator() AccuracyFulfilmentIndicator {
	if x != nil {
		return x.Indicator
	}
	return AccuracyFulfilmentIndicator_ACCURACY_FULFILMENT_UNSPECIFIED
}

func (x *QosEvaluateResponse) GetResponseTimeBreached() bool {
	if x != nil {
		return x.ResponseTimeBreached
	}
	return false
}

var File_lmf_location_proto protoreflect.FileDescriptor

const file_lmf_location_proto_rawDesc = "" +
	"\n" +
	"\x12lmf_location.proto\x12\x06lmf.v1\x1a\x10lmf_common.proto\"\xbb\x03\n" +
	"\x12LocationRequestMsg\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04supi\x18\x02 \x01(\tR\x04supi\x12\x10\n" +
	"\x03pei\x18\x03 \x01(\tR\x03pei\x12\x12\n" +
	"\x04gpsi\x18\x04 \x01(\tR\x04gpsi\x12'\n" +
	"\alcs_qos\x18\x05 \x01(\v2\x0e.lmf.v1.LcsQoSR\x06lcsQos\x12D\n" +
	"\x10preferred_method\x18\x06 \x01(\x0e2\x19.lmf.v1.PositioningMethodR\x0fpreferredMethod\x12H\n" +
	"\x12additional_methods\x18\a \x03(\x0e2\x19.lmf.v1.PositioningMethodR\x11additionalMethods\x12&\n" +
	"\x0famf_instance_id\x18\b \x01(\tR\ramfInstanceId\x12=\n" +
	"\x0flcs_client_type\x18\t \x01(\x0e2\x15.lmf.v1.LcsClientTypeR\rlcsClientType\x12,\n" +
	"\x12hgmlc_callback_uri\x18\n" +
	" \x01(\tR\x10hgmlcCallbackUri\"\xcd\x03\n" +
	"\x13LocationResponseMsg\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12E\n" +
	"\x11location_estimate\x18\x02 \x01(\v2\x18.lmf.v1.LocationEstimateR\x10locationEstimate\x12R\n" +
	"\x12accuracy_indicator\x18\x03 \x01(\x0e2#.lmf.v1.AccuracyFulfilmentIndicatorR\x11accuracyIndicator\x12E\n" +
	"\x11velocity_estimate\x18\x04 \x01(\v2\x18.lmf.v1.VelocityEstimateR\x10velocityEstimate\x12G\n" +
	"\x10positioning_data\x18\x05 \x03(\v2\x1c.lmf.v1.PositioningDataEntryR\x0fpositioningData\x12*\n" +
	"\x11timestamp_unix_ms\x18\x06 \x01(\x03R\x0ftimestampUnixMs\x12\x1d\n" +
	"\n" +
	"error_code\x18\a \x01(\tR\terrorCode\x12!\n" +
	"\ferror_detail\x18\b \x01(\tR\verrorDetail\"j\n" +
	"\x14PositioningDataEntry\x128\n" +
	"\n" +
	"pos_method\x18\x01 \x01(\x0e2\x19.lmf.v1.PositioningMethodR\tposMethod\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"B\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04supi\x18\x02 \x01(\tR\x04supi\"@\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\x14SessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x92\x01\n" +
	"\x15SessionStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.lmf.v1.SessionStatusR\x06status\x12+\n" +
	"\x12started_at_unix_ms\x18\x03 \x01(\x03R\x0fstartedAtUnixMs\"\xcb\x02\n" +
	"\x14SessionCreateRequest\x12\x12\n" +
	"\x04supi\x18\x01 \x01(\tR\x04supi\x12\x10\n" +
	"\x03pei\x18\x02 \x01(\tR\x03pei\x12\x12\n" +
	"\x04gpsi\x18\x03 \x01(\tR\x04gpsi\x12&\n" +
	"\x0famf_instance_id\x18\x04 \x01(\tR\ramfInstanceId\x12'\n" +
	"\alcs_qos\x18\x05 \x01(\v2\x0e.lmf.v1.LcsQoSR\x06lcsQos\x12=\n" +
	"\x0flcs_client_type\x18\x06 \x01(\x0e2\x15.lmf.v1.LcsClientTypeR\rlcsClientType\x12H\n" +
	"\x12positioning_method\x18\a \x01(\x0e2\x19.lmf.v1.PositioningMethodR\x11positioningMethod\x12\x1f\n" +
	"\vttl_seconds\x18\b \x01(\x03R\n" +
	"ttlSeconds\"6\n" +
	"\x15SessionCreateResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x11SessionGetRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x88\x03\n" +
	"\x12SessionGetResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04supi\x18\x02 \x01(\tR\x04supi\x12\x10\n" +
	"\x03pei\x18\x03 \x01(\tR\x03pei\x12&\n" +
	"\x0famf_instance_id\x18\x04 \x01(\tR\ramfInstanceId\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.lmf.v1.SessionStatusR\x06status\x12'\n" +
	"\alcs_qos\x18\x06 \x01(\v2\x0e.lmf.v1.LcsQoSR\x06lcsQos\x12=\n" +
	"\x0flcs_client_type\x18\a \x01(\x0e2\x15.lmf.v1.LcsClientTypeR\rlcsClientType\x12+\n" +
	"\x12started_at_unix_ms\x18\b \x01(\x03R\x0fstartedAtUnixMs\x12+\n" +
	"\x12expires_at_unix_ms\x18\t \x01(\x03R\x0fexpiresAtUnixMs\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"k\n" +
	"\x14SessionUpdateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x124\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x15.lmf.v1.SessionStatusR\tnewStatus\"1\n" +
	"\x15SessionUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x14SessionDeleteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"1\n" +
	"\x15SessionDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa3\x01\n" +
	"\x16MethodSelectionRequest\x12?\n" +
	"\x0fue_capabilities\x18\x01 \x01(\v2\x16.lmf.v1.UeCapabilitiesR\x0eueCapabilities\x12'\n" +
	"\alcs_qos\x18\x02 \x01(\v2\x0e.lmf.v1.LcsQoSR\x06lcsQos\x12\x1f\n" +
	"\vindoor_hint\x18\x03 \x01(\bR\n" +
	"indoorHint\"\x93\x02\n" +
	"\x17MethodSelectionResponse\x12B\n" +
	"\x0fselected_method\x18\x01 \x01(\x0e2\x19.lmf.v1.PositioningMethodR\x0eselectedMethod\x12D\n" +
	"\x10fallback_methods\x18\x02 \x03(\x0e2\x19.lmf.v1.PositioningMethodR\x0ffallbackMethods\x12:\n" +
	"\x19estimated_accuracy_meters\x18\x03 \x01(\x01R\x17estimatedAccuracyMeters\x122\n" +
	"\x15estimated_response_ms\x18\x04 \x01(\x05R\x13estimatedResponseMs\"\x90\x01\n" +
	"\x12QosEvaluateRequest\x123\n" +
	"\rrequested_qos\x18\x01 \x01(\v2\x0e.lmf.v1.LcsQoSR\frequestedQos\x12E\n" +
	"\x11achieved_estimate\x18\x02 \x01(\v2\x18.lmf.v1.PositionEstimateR\x10achievedEstimate\"\x8e\x01\n" +
	"\x13QosEvaluateResponse\x12A\n" +
	"\tindicator\x18\x01 \x01(\x0e2#.lmf.v1.AccuracyFulfilmentIndicatorR\tindicator\x124\n" +
	"\x16response_time_breached\x18\x02 \x01(\bR\x14responseTimeBreached2\xf8\x01\n" +
	"\x16LocationRequestService\x12L\n" +
	"\x11DetermineLocation\x12\x1a.lmf.v1.LocationRequestMsg\x1a\x1b.lmf.v1.LocationResponseMsg\x12?\n" +
	"\x0eCancelLocation\x12\x15.lmf.v1.CancelRequest\x1a\x16.lmf.v1.CancelResponse\x12O\n" +
	"\x10GetSessionStatus\x12\x1c.lmf.v1.SessionStatusRequest\x1a\x1d.lmf.v1.SessionStatusResponse2\xcc\x02\n" +
	"\x15SessionManagerService\x12L\n" +
	"\rCreateSession\x12\x1c.lmf.v1.SessionCreateRequest\x1a\x1d.lmf.v1.SessionCreateResponse\x12C\n" +
	"\n" +
	"GetSession\x12\x19.lmf.v1.SessionGetRequest\x1a\x1a.lmf.v1.SessionGetResponse\x12R\n" +
	"\x13UpdateSessionStatus\x12\x1c.lmf.v1.SessionUpdateRequest\x1a\x1d.lmf.v1.SessionUpdateResponse\x12L\n" +
	"\rDeleteSession\x12\x1c.lmf.v1.SessionDeleteRequest\x1a\x1d.lmf.v1.SessionDeleteResponse2h\n" +
	"\x15MethodSelectorService\x12O\n" +
	"\fSelectMethod\x12\x1e.lmf.v1.MethodSelectionRequest\x1a\x1f.lmf.v1.MethodSelectionResponse2[\n" +
	"\x11QosManagerService\x12F\n" +
	"\vEvaluateQoS\x12\x1a.lmf.v1.QosEvaluateRequest\x1a\x1b.lmf.v1.QosEvaluateResponseB Z\x1egithub.com/5g-lmf/common/pb;pbb\x06proto3"

var (
	file_lmf_location_proto_rawDescOnce sync.Once
	file_lmf_location_proto_rawDescData []byte
)

func file_lmf_location_proto_rawDescGZIP() []byte {
	file_lmf_location_proto_rawDescOnce.Do(func() {
		file_lmf_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lmf_location_proto_rawDesc), len(file_lmf_location_proto_rawDesc)))
	})
	return file_lmf_location_proto_rawDescData
}

var file_lmf_location_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_lmf_location_proto_goTypes = []any{
	(*LocationRequestMsg)(nil),       // 0: lmf.v1.LocationRequestMsg
	(*LocationResponseMsg)(nil),      // 1: lmf.v1.LocationResponseMsg
	(*PositioningDataEntry)(nil),     // 2: lmf.v1.PositioningDataEntry
	(*CancelRequest)(nil),            // 3: lmf.v1.CancelRequest
	(*CancelResponse)(nil),           // 4: lmf.v1.CancelResponse
	(*SessionStatusRequest)(nil),     // 5: lmf.v1.SessionStatusRequest
	(*SessionStatusResponse)(nil),    // 6: lmf.v1.SessionStatusResponse
	(*SessionCreateRequest)(nil),     // 7: lmf.v1.SessionCreateRequest
	(*SessionCreateResponse)(nil),    // 8: lmf.v1.SessionCreateResponse
	(*SessionGetRequest)(nil),        // 9: lmf.v1.SessionGetRequest
	(*SessionGetResponse)(nil),       // 10: lmf.v1.SessionGetResponse
	(*SessionUpdateRequest)(nil),     // 11: lmf.v1.SessionUpdateRequest
	(*SessionUpdateResponse)(nil),    // 12: lmf.v1.SessionUpdateResponse
	(*SessionDeleteRequest)(nil),     // 13: lmf.v1.SessionDeleteRequest
	(*SessionDeleteResponse)(nil),    // 14: lmf.v1.SessionDeleteResponse
	(*MethodSelectionRequest)(nil),   // 15: lmf.v1.MethodSelectionRequest
	(*MethodSelectionResponse)(nil),  // 16: lmf.v1.MethodSelectionResponse
	(*QosEvaluateRequest)(nil),       // 17: lmf.v1.QosEvaluateRequest
	(*QosEvaluateResponse)(nil),      // 18: lmf.v1.QosEvaluateResponse
	(*LcsQoS)(nil),                   // 19: lmf.v1.LcsQoS
	(PositioningMethod)(0),           // 20: lmf.v1.PositioningMethod
	(LcsClientType)(0),               // 21: lmf.v1.LcsClientType
	(*LocationEstimate)(nil),         // 22: lmf.v1.LocationEstimate
	(AccuracyFulfilmentIndicator)(0), // 23: lmf.v1.AccuracyFulfilmentIndicator
	(*VelocityEstimate)(nil),         // 24: lmf.v1.VelocityEstimate
	(SessionStatus)(0),               // 25: lmf.v1.SessionStatus
	(*UeCapabilities)(nil),           // 26: lmf.v1.UeCapabilities
	(*PositionEstimate)(nil),         // 27: lmf.v1.PositionEstimate
}
var file_lmf_location_proto_depIdxs = []int32{
	19, // 0: lmf.v1.LocationRequestMsg.lcs_qos:type_name -> lmf.v1.LcsQoS
	20, // 1: lmf.v1.LocationRequestMsg.preferred_method:type_name -> lmf.v1.PositioningMethod
	20, // 2: lmf.v1.LocationRequestMsg.additional_methods:type_name -> lmf.v1.PositioningMethod
	21, // 3: lmf.v1.LocationRequestMsg.lcs_client_type:type_name -> lmf.v1.LcsClientType
	22, // 4: lmf.v1.LocationResponseMsg.location_estimate:type_name -> lmf.v1.LocationEstimate
	23, // 5: lmf.v1.LocationResponseMsg.accuracy_indicator:type_name -> lmf.v1.AccuracyFulfilmentIndicator
	24, // 6: lmf.v1.LocationResponseMsg.velocity_estimate:type_name -> lmf.v1.VelocityEstimate
	2,  // 7: lmf.v1.LocationResponseMsg.positioning_data:type_name -> lmf.v1.PositioningDataEntry
	20, // 8: lmf.v1.PositioningDataEntry.pos_method:type_name -> lmf.v1.PositioningMethod
	25, // 9: lmf.v1.SessionStatusResponse.status:type_name -> lmf.v1.SessionStatus
	19, // 10: lmf.v1.SessionCreateRequest.lcs_qos:type_name -> lmf.v1.LcsQoS
	21, // 11: lmf.v1.SessionCreateRequest.lcs_client_type:type_name -> lmf.v1.LcsClientType
	20, // 12: lmf.v1.SessionCreateRequest.positioning_method:type_name -> lmf.v1.PositioningMethod
	25, // 13: lmf.v1.SessionGetResponse.status:type_name -> lmf.v1.SessionStatus
	19, // 14: lmf.v1.SessionGetResponse.lcs_qos:type_name -> lmf.v1.LcsQoS
	21, // 15: lmf.v1.SessionGetResponse.lcs_client_type:type_name -> lmf.v1.LcsClientType
	25, // 16: lmf.v1.SessionUpdateRequest.new_status:type_name -> lmf.v1.SessionStatus
	26, // 17: lmf.v1.MethodSelectionRequest.ue_capabilities:type_name -> lmf.v1.UeCapabilities
	19, // 18: lmf.v1.MethodSelectionRequest.lcs_qos:type_name -> lmf.v1.LcsQoS
	20, // 19: lmf.v1.MethodSelectionResponse.selected_method:type_name -> lmf.v1.PositioningMethod
	20, // 20: lmf.v1.MethodSelectionResponse.fallback_methods:type_name -> lmf.v1.PositioningMethod
	19, // 21: lmf.v1.QosEvaluateRequest.requested_qos:type_name -> lmf.v1.LcsQoS
	27, // 22: lmf.v1.QosEvaluateRequest.achieved_estimate:type_name -> lmf.v1.PositionEstimate
	23, // 23: lmf.v1.QosEvaluateResponse.indicator:type_name -> lmf.v1.AccuracyFulfilmentIndicator
	0,  // 24: lmf.v1.LocationRequestService.DetermineLocation:input_type -> lmf.v1.LocationRequestMsg
	3,  // 25: lmf.v1.LocationRequestService.CancelLocation:input_type -> lmf.v1.CancelRequest
	5,  // 26: lmf.v1.LocationRequestService.GetSessionStatus:input_type -> lmf.v1.SessionStatusRequest
	7,  // 27: lmf.v1.SessionManagerService.CreateSession:input_type -> lmf.v1.SessionCreateRequest
	9,  // 28: lmf.v1.SessionManagerService.GetSession:input_type -> lmf.v1.SessionGetRequest
	11, // 29: lmf.v1.SessionManagerService.UpdateSessionStatus:input_type -> lmf.v1.SessionUpdateRequest
	13, // 30: lmf.v1.SessionManagerService.DeleteSession:input_type -> lmf.v1.SessionDeleteRequest
	15, // 31: lmf.v1.MethodSelectorService.SelectMethod:input_type -> lmf.v1.MethodSelectionRequest
	17, // 32: lmf.v1.QosManagerService.EvaluateQoS:input_type -> lmf.v1.QosEvaluateRequest
	1,  // 33: lmf.v1.LocationRequestService.DetermineLocation:output_type -> lmf.v1.LocationResponseMsg
	4,  // 34: lmf.v1.LocationRequestService.CancelLocation:output_type -> lmf.v1.CancelResponse
	6,  // 35: lmf.v1.LocationRequestService.GetSessionStatus:output_type -> lmf.v1.SessionStatusResponse
	8,  // 36: lmf.v1.SessionManagerService.CreateSession:output_type -> lmf.v1.SessionCreateResponse
	10, // 37: lmf.v1.SessionManagerService.GetSession:output_type -> lmf.v1.SessionGetResponse
	12, // 38: lmf.v1.SessionManagerService.UpdateSessionStatus:output_type -> lmf.v1.SessionUpdateResponse
	14, // 39: lmf.v1.SessionManagerService.DeleteSession:output_type -> lmf.v1.SessionDeleteResponse
	16, // 40: lmf.v1.MethodSelectorService.SelectMethod:output_type -> lmf.v1.MethodSelectionResponse
	18, // 41: lmf.v1.QosManagerService.EvaluateQoS:output_type -> lmf.v1.QosEvaluateResponse
	33, // [33:42] is the sub-list for method output_type
	24, // [24:33] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_lmf_location_proto_init() }
func file_lmf_location_proto_init() {
	if File_lmf_location_proto != nil {
		return
	}
	file_lmf_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lmf_location_proto_rawDesc), len(file_lmf_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_lmf_location_proto_goTypes,
		DependencyIndexes: file_lmf_location_proto_depIdxs,
		MessageInfos:      file_lmf_location_proto_msgTypes,
	}.Build()
	File_lmf_location_proto = out.File
	file_lmf_location_proto_goTypes = nil
	file_lmf_location_proto_depIdxs = nil
}
