// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: lmf_positioning.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GnssEngineService_GetAssistanceData_FullMethodName = "/lmf.v1.GnssEngineService/GetAssistanceData"
	GnssEngineService_ComputePosition_FullMethodName   = "/lmf.v1.GnssEngineService/ComputePosition"
)

// GnssEngineServiceClient is the client API for GnssEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definitions
type GnssEngineServiceClient interface {
	GetAssistanceData(ctx context.Context, in *GnssAssistanceRequest, opts ...grpc.CallOption) (*GnssAssistanceResponse, error)
	ComputePosition(ctx context.Context, in *GnssComputeRequest, opts ...grpc.CallOption) (*GnssComputeResponse, error)
}

type gnssEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGnssEngineServiceClient(cc grpc.ClientConnInterface) GnssEngineServiceClient {
	return &gnssEngineServiceClient{cc}
}

func (c *gnssEngineServiceClient) GetAssistanceData(ctx context.Context, in *GnssAssistanceRequest, opts ...grpc.CallOption) (*GnssAssistanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GnssAssistanceResponse)
	err := c.cc.Invoke(ctx, GnssEngineService_GetAssistanceData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gnssEngineServiceClient) ComputePosition(ctx context.Context, in *GnssComputeRequest, opts ...grpc.CallOption) (*GnssComputeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GnssComputeResponse)
	err := c.cc.Invoke(ctx, GnssEngineService_ComputePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GnssEngineServiceServer is the server API for GnssEngineService service.
// All implementations must embed UnimplementedGnssEngineServiceServer
// for forward compatibility.
//
// Service definitions
type GnssEngineServiceServer interface {
	GetAssistanceData(context.Context, *GnssAssistanceRequest) (*GnssAssistanceResponse, error)
	ComputePosition(context.Context, *GnssComputeRequest) (*GnssComputeResponse, error)
	mustEmbedUnimplementedGnssEngineServiceServer()
}

// UnimplementedGnssEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGnssEngineServiceServer struct{}

func (UnimplementedGnssEngineServiceServer) GetAssistanceData(context.Context, *GnssAssistanceRequest) (*GnssAssistanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssistanceData not implemented")
}
func (UnimplementedGnssEngineServiceServer) ComputePosition(context.Context, *GnssComputeRequest) (*GnssComputeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputePosition not implemented")
}
func (UnimplementedGnssEngineServiceServer) mustEmbedUnimplementedGnssEngineServiceServer() {}
func (UnimplementedGnssEngineServiceServer) testEmbeddedByValue()                           {}

// UnsafeGnssEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GnssEngineServiceServer will
// result in compilation errors.
type UnsafeGnssEngineServiceServer interface {
	mustEmbedUnimplementedGnssEngineServiceServer()
}

func RegisterGnssEngineServiceServer(s grpc.ServiceRegistrar, srv GnssEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedGnssEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GnssEngineService_ServiceDesc, srv)
}

func _GnssEngineService_GetAssistanceData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GnssAssistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GnssEngineServiceServer).GetAssistanceData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GnssEngineService_GetAssistanceData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GnssEngineServiceServer).GetAssistanceData(ctx, req.(*GnssAssistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GnssEngineService_ComputePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GnssComputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GnssEngineServiceServer).ComputePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GnssEngineService_ComputePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GnssEngineServiceServer).ComputePosition(ctx, req.(*GnssComputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GnssEngineService_ServiceDesc is the grpc.ServiceDesc for GnssEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GnssEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.GnssEngineService",
	HandlerType: (*GnssEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAssistanceData",
			Handler:    _GnssEngineService_GetAssistanceData_Handler,
		},
		{
			MethodName: "ComputePosition",
			Handler:    _GnssEngineService_ComputePosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_positioning.proto",
}

const (
	TdoaEngineService_ComputePosition_FullMethodName = "/lmf.v1.TdoaEngineService/ComputePosition"
)

// TdoaEngineServiceClient is the client API for TdoaEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TdoaEngineServiceClient interface {
	ComputePosition(ctx context.Context, in *DlTdoaRequest, opts ...grpc.CallOption) (*DlTdoaResponse, error)
}

type tdoaEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTdoaEngineServiceClient(cc grpc.ClientConnInterface) TdoaEngineServiceClient {
	return &tdoaEngineServiceClient{cc}
}

func (c *tdoaEngineServiceClient) ComputePosition(ctx context.Context, in *DlTdoaRequest, opts ...grpc.CallOption) (*DlTdoaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DlTdoaResponse)
	err := c.cc.Invoke(ctx, TdoaEngineService_ComputePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TdoaEngineServiceServer is the server API for TdoaEngineService service.
// All implementations must embed UnimplementedTdoaEngineServiceServer
// for forward compatibility.
type TdoaEngineServiceServer interface {
	ComputePosition(context.Context, *DlTdoaRequest) (*DlTdoaResponse, error)
	mustEmbedUnimplementedTdoaEngineServiceServer()
}

// UnimplementedTdoaEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTdoaEngineServiceServer struct{}

func (UnimplementedTdoaEngineServiceServer) ComputePosition(context.Context, *DlTdoaRequest) (*DlTdoaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputePosition not implemented")
}
func (UnimplementedTdoaEngineServiceServer) mustEmbedUnimplementedTdoaEngineServiceServer() {}
func (UnimplementedTdoaEngineServiceServer) testEmbeddedByValue()                           {}

// UnsafeTdoaEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TdoaEngineServiceServer will
// result in compilation errors.
type UnsafeTdoaEngineServiceServer interface {
	mustEmbedUnimplementedTdoaEngineServiceServer()
}

func RegisterTdoaEngineServiceServer(s grpc.ServiceRegistrar, srv TdoaEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedTdoaEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TdoaEngineService_ServiceDesc, srv)
}

func _TdoaEngineService_ComputePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DlTdoaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TdoaEngineServiceServer).ComputePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TdoaEngineService_ComputePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TdoaEngineServiceServer).ComputePosition(ctx, req.(*DlTdoaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TdoaEngineService_ServiceDesc is the grpc.ServiceDesc for TdoaEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TdoaEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.TdoaEngineService",
	HandlerType: (*TdoaEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputePosition",
			Handler:    _TdoaEngineService_ComputePosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_positioning.proto",
}

const (
	EcidEngineService_ComputePosition_FullMethodName = "/lmf.v1.EcidEngineService/ComputePosition"
)

// EcidEngineServiceClient is the client API for EcidEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EcidEngineServiceClient interface {
	ComputePosition(ctx context.Context, in *EcidRequest, opts ...grpc.CallOption) (*EcidResponse, error)
}

type ecidEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEcidEngineServiceClient(cc grpc.ClientConnInterface) EcidEngineServiceClient {
	return &ecidEngineServiceClient{cc}
}

func (c *ecidEngineServiceClient) ComputePosition(ctx context.Context, in *EcidRequest, opts ...grpc.CallOption) (*EcidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EcidResponse)
	err := c.cc.Invoke(ctx, EcidEngineService_ComputePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EcidEngineServiceServer is the server API for EcidEngineService service.
// All implementations must embed UnimplementedEcidEngineServiceServer
// for forward compatibility.
type EcidEngineServiceServer interface {
	ComputePosition(context.Context, *EcidRequest) (*EcidResponse, error)
	mustEmbedUnimplementedEcidEngineServiceServer()
}

// UnimplementedEcidEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEcidEngineServiceServer struct{}

func (UnimplementedEcidEngineServiceServer) ComputePosition(context.Context, *EcidRequest) (*EcidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputePosition not implemented")
}
func (UnimplementedEcidEngineServiceServer) mustEmbedUnimplementedEcidEngineServiceServer() {}
func (UnimplementedEcidEngineServiceServer) testEmbeddedByValue()                           {}

// UnsafeEcidEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EcidEngineServiceServer will
// result in compilation errors.
type UnsafeEcidEngineServiceServer interface {
	mustEmbedUnimplementedEcidEngineServiceServer()
}

func RegisterEcidEngineServiceServer(s grpc.ServiceRegistrar, srv EcidEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedEcidEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EcidEngineService_ServiceDesc, srv)
}

func _EcidEngineService_ComputePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EcidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcidEngineServiceServer).ComputePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcidEngineService_ComputePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcidEngineServiceServer).ComputePosition(ctx, req.(*EcidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EcidEngineService_ServiceDesc is the grpc.ServiceDesc for EcidEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EcidEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.EcidEngineService",
	HandlerType: (*EcidEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputePosition",
			Handler:    _EcidEngineService_ComputePosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_positioning.proto",
}

const (
	RttEngineService_ComputePosition_FullMethodName = "/lmf.v1.RttEngineService/ComputePosition"
)

// RttEngineServiceClient is the client API for RttEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RttEngineServiceClient interface {
	ComputePosition(ctx context.Context, in *MultiRttRequest, opts ...grpc.CallOption) (*MultiRttResponse, error)
}

type rttEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRttEngineServiceClient(cc grpc.ClientConnInterface) RttEngineServiceClient {
	return &rttEngineServiceClient{cc}
}

func (c *rttEngineServiceClient) ComputePosition(ctx context.Context, in *MultiRttRequest, opts ...grpc.CallOption) (*MultiRttResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiRttResponse)
	err := c.cc.Invoke(ctx, RttEngineService_ComputePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RttEngineServiceServer is the server API for RttEngineService service.
// All implementations must embed UnimplementedRttEngineServiceServer
// for forward compatibility.
type RttEngineServiceServer interface {
	ComputePosition(context.Context, *MultiRttRequest) (*MultiRttResponse, error)
	mustEmbedUnimplementedRttEngineServiceServer()
}

// UnimplementedRttEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRttEngineServiceServer struct{}

func (UnimplementedRttEngineServiceServer) ComputePosition(context.Context, *MultiRttRequest) (*MultiRttResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputePosition not implemented")
}
func (UnimplementedRttEngineServiceServer) mustEmbedUnimplementedRttEngineServiceServer() {}
func (UnimplementedRttEngineServiceServer) testEmbeddedByValue()                          {}

// UnsafeRttEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RttEngineServiceServer will
// result in compilation errors.
type UnsafeRttEngineServiceServer interface {
	mustEmbedUnimplementedRttEngineServiceServer()
}

func RegisterRttEngineServiceServer(s grpc.ServiceRegistrar, srv RttEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedRttEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RttEngineService_ServiceDesc, srv)
}

func _RttEngineService_ComputePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiRttRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RttEngineServiceServer).ComputePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RttEngineService_ComputePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RttEngineServiceServer).ComputePosition(ctx, req.(*MultiRttRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RttEngineService_ServiceDesc is the grpc.ServiceDesc for RttEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RttEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.RttEngineService",
	HandlerType: (*RttEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputePosition",
			Handler:    _RttEngineService_ComputePosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_positioning.proto",
}

const (
	FusionEngineService_FusePositions_FullMethodName = "/lmf.v1.FusionEngineService/FusePositions"
)

// FusionEngineServiceClient is the client API for FusionEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FusionEngineServiceClient interface {
	FusePositions(ctx context.Context, in *FusionRequest, opts ...grpc.CallOption) (*FusionResponse, error)
}

type fusionEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFusionEngineServiceClient(cc grpc.ClientConnInterface) FusionEngineServiceClient {
	return &fusionEngineServiceClient{cc}
}

func (c *fusionEngineServiceClient) FusePositions(ctx context.Context, in *FusionRequest, opts ...grpc.CallOption) (*FusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FusionResponse)
	err := c.cc.Invoke(ctx, FusionEngineService_FusePositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FusionEngineServiceServer is the server API for FusionEngineService service.
// All implementations must embed UnimplementedFusionEngineServiceServer
// for forward compatibility.
type FusionEngineServiceServer interface {
	FusePositions(context.Context, *FusionRequest) (*FusionResponse, error)
	mustEmbedUnimplementedFusionEngineServiceServer()
}

// UnimplementedFusionEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFusionEngineServiceServer struct{}

func (UnimplementedFusionEngineServiceServer) FusePositions(context.Context, *FusionRequest) (*FusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FusePositions not implemented")
}
func (UnimplementedFusionEngineServiceServer) mustEmbedUnimplementedFusionEngineServiceServer() {}
func (UnimplementedFusionEngineServiceServer) testEmbeddedByValue()                             {}

// UnsafeFusionEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FusionEngineServiceServer will
// result in compilation errors.
type UnsafeFusionEngineServiceServer interface {
	mustEmbedUnimplementedFusionEngineServiceServer()
}

func RegisterFusionEngineServiceServer(s grpc.ServiceRegistrar, srv FusionEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedFusionEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FusionEngineService_ServiceDesc, srv)
}

func _FusionEngineService_FusePositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FusionEngineServiceServer).FusePositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FusionEngineService_FusePositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FusionEngineServiceServer).FusePositions(ctx, req.(*FusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FusionEngineService_ServiceDesc is the grpc.ServiceDesc for FusionEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FusionEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.FusionEngineService",
	HandlerType: (*FusionEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FusePositions",
			Handler:    _FusionEngineService_FusePositions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_positioning.proto",
}
