// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: lmf_events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType defines the category of location event
type EventTypeProto int32

const (
	EventTypeProto_EVENT_TYPE_UNSPECIFIED  EventTypeProto = 0
	EventTypeProto_EVENT_TYPE_PERIODIC     EventTypeProto = 1
	EventTypeProto_EVENT_TYPE_AREA         EventTypeProto = 2
	EventTypeProto_EVENT_TYPE_MOTION       EventTypeProto = 3
	EventTypeProto_EVENT_TYPE_MAX_INTERVAL EventTypeProto = 4
	EventTypeProto_EVENT_TYPE_CANCELLATION EventTypeProto = 5
)

// Enum value maps for EventTypeProto.
var (
	EventTypeProto_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_PERIODIC",
		2: "EVENT_TYPE_AREA",
		3: "EVENT_TYPE_MOTION",
		4: "EVENT_TYPE_MAX_INTERVAL",
		5: "EVENT_TYPE_CANCELLATION",
	}
	EventTypeProto_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":  0,
		"EVENT_TYPE_PERIODIC":     1,
		"EVENT_TYPE_AREA":         2,
		"EVENT_TYPE_MOTION":       3,
		"EVENT_TYPE_MAX_INTERVAL": 4,
		"EVENT_TYPE_CANCELLATION": 5,
	}
)

func (x EventTypeProto) Enum() *EventTypeProto {
	p := new(EventTypeProto)
	*p = x
	return p
}

func (x EventTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_lmf_events_proto_enumTypes[0].Descriptor()
}

func (EventTypeProto) Type() protoreflect.EnumType {
	return &file_lmf_events_proto_enumTypes[0]
}

func (x EventTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventTypeProto.Descriptor instead.
func (EventTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{0}
}

// AreaType defines what crossing triggers the event
type AreaTypeProto int32

const (
	AreaTypeProto_AREA_TYPE_UNSPECIFIED AreaTypeProto = 0
	AreaTypeProto_AREA_TYPE_ENTER       AreaTypeProto = 1
	AreaTypeProto_AREA_TYPE_LEAVE       AreaTypeProto = 2
	AreaTypeProto_AREA_TYPE_WITHIN      AreaTypeProto = 3
)

// Enum value maps for AreaTypeProto.
var (
	AreaTypeProto_name = map[int32]string{
		0: "AREA_TYPE_UNSPECIFIED",
		1: "AREA_TYPE_ENTER",
		2: "AREA_TYPE_LEAVE",
		3: "AREA_TYPE_WITHIN",
	}
	AreaTypeProto_value = map[string]int32{
		"AREA_TYPE_UNSPECIFIED": 0,
		"AREA_TYPE_ENTER":       1,
		"AREA_TYPE_LEAVE":       2,
		"AREA_TYPE_WITHIN":      3,
	}
)

func (x AreaTypeProto) Enum() *AreaTypeProto {
	p := new(AreaTypeProto)
	*p = x
	return p
}

func (x AreaTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AreaTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_lmf_events_proto_enumTypes[1].Descriptor()
}

func (AreaTypeProto) Type() protoreflect.EnumType {
	return &file_lmf_events_proto_enumTypes[1]
}

func (x AreaTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AreaTypeProto.Descriptor instead.
func (AreaTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{1}
}

// PrivacyClass per TS 23.273 §8
type PrivacyClass int32

const (
	PrivacyClass_PRIVACY_CLASS_UNSPECIFIED PrivacyClass = 0
	PrivacyClass_PRIVACY_CLASS_A           PrivacyClass = 1 // No privacy restriction (emergency)
	PrivacyClass_PRIVACY_CLASS_B           PrivacyClass = 2 // Notify only
	PrivacyClass_PRIVACY_CLASS_C           PrivacyClass = 3 // Notify + verify
	PrivacyClass_PRIVACY_CLASS_D           PrivacyClass = 4 // Blocked
)

// Enum value maps for PrivacyClass.
var (
	PrivacyClass_name = map[int32]string{
		0: "PRIVACY_CLASS_UNSPECIFIED",
		1: "PRIVACY_CLASS_A",
		2: "PRIVACY_CLASS_B",
		3: "PRIVACY_CLASS_C",
		4: "PRIVACY_CLASS_D",
	}
	PrivacyClass_value = map[string]int32{
		"PRIVACY_CLASS_UNSPECIFIED": 0,
		"PRIVACY_CLASS_A":           1,
		"PRIVACY_CLASS_B":           2,
		"PRIVACY_CLASS_C":           3,
		"PRIVACY_CLASS_D":           4,
	}
)

func (x PrivacyClass) Enum() *PrivacyClass {
	p := new(PrivacyClass)
	*p = x
	return p
}

func (x PrivacyClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivacyClass) Descriptor() protoreflect.EnumDescriptor {
	return file_lmf_events_proto_enumTypes[2].Descriptor()
}

func (PrivacyClass) Type() protoreflect.EnumType {
	return &file_lmf_events_proto_enumTypes[2]
}

func (x PrivacyClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrivacyClass.Descriptor instead.
func (PrivacyClass) EnumDescriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{2}
}

// LatLonMsg is a geographic coordinate
type LatLonMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLonMsg) Reset() {
	*x = LatLonMsg{}
	mi := &file_lmf_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLonMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLonMsg) ProtoMessage() {}

func (x *LatLonMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLonMsg.ProtoReflect.Descriptor instead.
func (*LatLonMsg) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{0}
}

func (x *LatLonMsg) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LatLonMsg) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

// GeographicArea defines a polygon or circle
type GeographicArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shape         string                 `protobuf:"bytes,1,opt,name=shape,proto3" json:"shape,omitempty"`
	Points        []*LatLonMsg           `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`                                   // For polygon
	Center        *LatLonMsg             `protobuf:"bytes,3,opt,name=center,proto3" json:"center,omitempty"`                                   // For circle
	RadiusMeters  float64                `protobuf:"fixed64,4,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"` // For circle
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeographicArea) Reset() {
	*x = GeographicArea{}
	mi := &file_lmf_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeographicArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeographicArea) ProtoMessage() {}

func (x *GeographicArea) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeographicArea.ProtoReflect.Descriptor instead.
func (*GeographicArea) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{1}
}

func (x *GeographicArea) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *GeographicArea) GetPoints() []*LatLonMsg {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *GeographicArea) GetCenter() *LatLonMsg {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *GeographicArea) GetRadiusMeters() float64 {
	if x != nil {
		return x.RadiusMeters
	}
	return 0
}

// AreaEventInfoMsg defines an area trigger
type AreaEventInfoMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaType      AreaTypeProto          `protobuf:"varint,1,opt,name=area_type,json=areaType,proto3,enum=lmf.v1.AreaTypeProto" json:"area_type,omitempty"`
	Areas         []*GeographicArea      `protobuf:"bytes,2,rep,name=areas,proto3" json:"areas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaEventInfoMsg) Reset() {
	*x = AreaEventInfoMsg{}
	mi := &file_lmf_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaEventInfoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaEventInfoMsg) ProtoMessage() {}

func (x *AreaEventInfoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaEventInfoMsg.ProtoReflect.Descriptor instead.
func (*AreaEventInfoMsg) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{2}
}

func (x *AreaEventInfoMsg) GetAreaType() AreaTypeProto {
	if x != nil {
		return x.AreaType
	}
	return AreaTypeProto_AREA_TYPE_UNSPECIFIED
}

func (x *AreaEventInfoMsg) GetAreas() []*GeographicArea {
	if x != nil {
		return x.Areas
	}
	return nil
}

// EventSubscriptionRequest to create a subscription
type EventSubscriptionRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Supi                    string                 `protobuf:"bytes,1,opt,name=supi,proto3" json:"supi,omitempty"`
	EventType               EventTypeProto         `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=lmf.v1.EventTypeProto" json:"event_type,omitempty"`
	NotifUri                string                 `protobuf:"bytes,3,opt,name=notif_uri,json=notifUri,proto3" json:"notif_uri,omitempty"`
	NotifId                 string                 `protobuf:"bytes,4,opt,name=notif_id,json=notifId,proto3" json:"notif_id,omitempty"`
	AreaEventInfo           *AreaEventInfoMsg      `protobuf:"bytes,5,opt,name=area_event_info,json=areaEventInfo,proto3" json:"area_event_info,omitempty"`
	LcsQos                  *LcsQoS                `protobuf:"bytes,6,opt,name=lcs_qos,json=lcsQos,proto3" json:"lcs_qos,omitempty"`
	PeriodicIntervalSeconds int32                  `protobuf:"varint,7,opt,name=periodic_interval_seconds,json=periodicIntervalSeconds,proto3" json:"periodic_interval_seconds,omitempty"`
	MaxReports              int32                  `protobuf:"varint,8,opt,name=max_reports,json=maxReports,proto3" json:"max_reports,omitempty"`
	MonitoringExpiryUnixMs  int64                  `protobuf:"varint,9,opt,name=monitoring_expiry_unix_ms,json=monitoringExpiryUnixMs,proto3" json:"monitoring_expiry_unix_ms,omitempty"`
	MotionThresholdMeters   float64                `protobuf:"fixed64,10,opt,name=motion_threshold_meters,json=motionThresholdMeters,proto3" json:"motion_threshold_meters,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *EventSubscriptionRequest) Reset() {
	*x = EventSubscriptionRequest{}
	mi := &file_lmf_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscriptionRequest) ProtoMessage() {}

func (x *EventSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*EventSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{3}
}

func (x *EventSubscriptionRequest) GetSupi() string {
	if x != nil {
		return x.Supi
	}
	return ""
}

func (x *EventSubscriptionRequest) GetEventType() EventTypeProto {
	if x != nil {
		return x.EventType
	}
	return EventTypeProto_EVENT_TYPE_UNSPECIFIED
}

func (x *EventSubscriptionRequest) GetNotifUri() string {
	if x != nil {
		return x.NotifUri
	}
	return ""
}

func (x *EventSubscriptionRequest) GetNotifId() string {
	if x != nil {
		return x.NotifId
	}
	return ""
}

func (x *EventSubscriptionRequest) GetAreaEventInfo() *AreaEventInfoMsg {
	if x != nil {
		return x.AreaEventInfo
	}
	return nil
}

func (x *EventSubscriptionRequest) GetLcsQos() *LcsQoS {
	if x != nil {
		return x.LcsQos
	}
	return nil
}

func (x *EventSubscriptionRequest) GetPeriodicIntervalSeconds() int32 {
	if x != nil {
		return x.PeriodicIntervalSeconds
	}
	return 0
}

func (x *EventSubscriptionRequest) GetMaxReports() int32 {
	if x != nil {
		return x.MaxReports
	}
	return 0
}

func (x *EventSubscriptionRequest) GetMonitoringExpiryUnixMs() int64 {
	if x != nil {
		return x.MonitoringExpiryUnixMs
	}
	return 0
}

func (x *EventSubscriptionRequest) GetMotionThresholdMeters() float64 {
	if x != nil {
		return x.MotionThresholdMeters
	}
	return 0
}

// EventSubscriptionResponse confirms subscription
type EventSubscriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventSubscriptionResponse) Reset() {
	*x = EventSubscriptionResponse{}
	mi := &file_lmf_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscriptionResponse) ProtoMessage() {}

func (x *EventSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*EventSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{4}
}

func (x *EventSubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *EventSubscriptionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UnsubscribeRequest to cancel a subscription
type UnsubscribeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_lmf_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{5}
}

func (x *UnsubscribeRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// UnsubscribeResponse confirms cancellation
type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_lmf_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{6}
}

func (x *UnsubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// EventNotification is sent to the subscriber callback
type EventNotification struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId   string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Supi             string                 `protobuf:"bytes,2,opt,name=supi,proto3" json:"supi,omitempty"`
	EventType        EventTypeProto         `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=lmf.v1.EventTypeProto" json:"event_type,omitempty"`
	LocationEstimate *LocationEstimate      `protobuf:"bytes,4,opt,name=location_estimate,json=locationEstimate,proto3" json:"location_estimate,omitempty"`
	TimestampUnixMs  int64                  `protobuf:"varint,5,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	ReportCount      int32                  `protobuf:"varint,6,opt,name=report_count,json=reportCount,proto3" json:"report_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventNotification) Reset() {
	*x = EventNotification{}
	mi := &file_lmf_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventNotification) ProtoMessage() {}

func (x *EventNotification) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventNotification.ProtoReflect.Descriptor instead.
func (*EventNotification) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{7}
}

func (x *EventNotification) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *EventNotification) GetSupi() string {
	if x != nil {
		return x.Supi
	}
	return ""
}

func (x *EventNotification) GetEventType() EventTypeProto {
	if x != nil {
		return x.EventType
	}
	return EventTypeProto_EVENT_TYPE_UNSPECIFIED
}

func (x *EventNotification) GetLocationEstimate() *LocationEstimate {
	if x != nil {
		return x.LocationEstimate
	}
	return nil
}

func (x *EventNotification) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *EventNotification) GetReportCount() int32 {
	if x != nil {
		return x.ReportCount
	}
	return 0
}

// LocationUpdateMsg sent internally when a position is determined
type LocationUpdateMsg struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Supi             string                 `protobuf:"bytes,1,opt,name=supi,proto3" json:"supi,omitempty"`
	LocationEstimate *LocationEstimate      `protobuf:"bytes,2,opt,name=location_estimate,json=locationEstimate,proto3" json:"location_estimate,omitempty"`
	TimestampUnixMs  int64                  `protobuf:"varint,3,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LocationUpdateMsg) Reset() {
	*x = LocationUpdateMsg{}
	mi := &file_lmf_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUpdateMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUpdateMsg) ProtoMessage() {}

func (x *LocationUpdateMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUpdateMsg.ProtoReflect.Descriptor instead.
func (*LocationUpdateMsg) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{8}
}

func (x *LocationUpdateMsg) GetSupi() string {
	if x != nil {
		return x.Supi
	}
	return ""
}

func (x *LocationUpdateMsg) GetLocationEstimate() *LocationEstimate {
	if x != nil {
		return x.LocationEstimate
	}
	return nil
}

func (x *LocationUpdateMsg) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// Privacy check messages
type PrivacyCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supi          string                 `protobuf:"bytes,1,opt,name=supi,proto3" json:"supi,omitempty"`
	LcsClientType LcsClientType          `protobuf:"varint,2,opt,name=lcs_client_type,json=lcsClientType,proto3,enum=lmf.v1.LcsClientType" json:"lcs_client_type,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivacyCheckRequest) Reset() {
	*x = PrivacyCheckRequest{}
	mi := &file_lmf_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivacyCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacyCheckRequest) ProtoMessage() {}

func (x *PrivacyCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivacyCheckRequest.ProtoReflect.Descriptor instead.
func (*PrivacyCheckRequest) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{9}
}

func (x *PrivacyCheckRequest) GetSupi() string {
	if x != nil {
		return x.Supi
	}
	return ""
}

func (x *PrivacyCheckRequest) GetLcsClientType() LcsClientType {
	if x != nil {
		return x.LcsClientType
	}
	return LcsClientType_LCS_CLIENT_TYPE_UNSPECIFIED
}

func (x *PrivacyCheckRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PrivacyCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Allowed          bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	PrivacyClass     PrivacyClass           `protobuf:"varint,2,opt,name=privacy_class,json=privacyClass,proto3,enum=lmf.v1.PrivacyClass" json:"privacy_class,omitempty"`
	NotificationSent bool                   `protobuf:"varint,3,opt,name=notification_sent,json=notificationSent,proto3" json:"notification_sent,omitempty"`
	DenialReason     string                 `protobuf:"bytes,4,opt,name=denial_reason,json=denialReason,proto3" json:"denial_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrivacyCheckResponse) Reset() {
	*x = PrivacyCheckResponse{}
	mi := &file_lmf_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivacyCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacyCheckResponse) ProtoMessage() {}

func (x *PrivacyCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivacyCheckResponse.ProtoReflect.Descriptor instead.
func (*PrivacyCheckResponse) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{10}
}

func (x *PrivacyCheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *PrivacyCheckResponse) GetPrivacyClass() PrivacyClass {
	if x != nil {
		return x.PrivacyClass
	}
	return PrivacyClass_PRIVACY_CLASS_UNSPECIFIED
}

func (x *PrivacyCheckResponse) GetNotificationSent() bool {
	if x != nil {
		return x.NotificationSent
	}
	return false
}

func (x *PrivacyCheckResponse) GetDenialReason() string {
	if x != nil {
		return x.DenialReason
	}
	return ""
}

// Token validation messages
type TokenValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RequiredScope string                 `protobuf:"bytes,2,opt,name=required_scope,json=requiredScope,proto3" json:"required_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValidateRequest) Reset() {
	*x = TokenValidateRequest{}
	mi := &file_lmf_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidateRequest) ProtoMessage() {}

func (x *TokenValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidateRequest.ProtoReflect.Descriptor instead.
func (*TokenValidateRequest) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{11}
}

func (x *TokenValidateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenValidateRequest) GetRequiredScope() string {
	if x != nil {
		return x.RequiredScope
	}
	return ""
}

type TokenValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	PlmnId        string                 `protobuf:"bytes,3,opt,name=plmn_id,json=plmnId,proto3" json:"plmn_id,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValidateResponse) Reset() {
	*x = TokenValidateResponse{}
	mi := &file_lmf_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidateResponse) ProtoMessage() {}

func (x *TokenValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidateResponse.ProtoReflect.Descriptor instead.
func (*TokenValidateResponse) Descriptor() ([]byte, []int) {
	return file_lmf_events_proto_rawDescGZIP(), []int{12}
}

func (x *TokenValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *TokenValidateResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TokenValidateResponse) GetPlmnId() string {
	if x != nil {
		return x.PlmnId
	}
	return ""
}

func (x *TokenValidateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_lmf_events_proto protoreflect.FileDescriptor

const file_lmf_events_proto_rawDesc = "" +
	"\n" +
	"\x10lmf_events.proto\x12\x06lmf.v1\x1a\x10lmf_common.proto\"/\n" +
	"\tLatLonMsg\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\"\xa1\x01\n" +
	"\x0eGeographicArea\x12\x14\n" +
	"\x05shape\x18\x01 \x01(\tR\x05shape\x12)\n" +
	"\x06points\x18\x02 \x03(\v2\x11.lmf.v1.LatLonMsgR\x06points\x12)\n" +
	"\x06center\x18\x03 \x01(\v2\x11.lmf.v1.LatLonMsgR\x06center\x12#\n" +
	"\rradius_meters\x18\x04 \x01(\x01R\fradiusMeters\"t\n" +
	"\x10AreaEventInfoMsg\x122\n" +
	"\tarea_type\x18\x01 \x01(\x0e2\x15.lmf.v1.AreaTypeProtoR\bareaType\x12,\n" +
	"\x05areas\x18\x02 \x03(\v2\x16.lmf.v1.GeographicAreaR\x05areas\"\xd8\x03\n" +
	"\x18EventSubscriptionRequest\x12\x12\n" +
	"\x04supi\x18\x01 \x01(\tR\x04supi\x125\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x16.lmf.v1.EventTypeProtoR\teventType\x12\x1b\n" +
	"\tnotif_uri\x18\x03 \x01(\tR\bnotifUri\x12\x19\n" +
	"\bnotif_id\x18\x04 \x01(\tR\anotifId\x12@\n" +
	"\x0farea_event_info\x18\x05 \x01(\v2\x18.lmf.v1.AreaEventInfoMsgR\rareaEventInfo\x12'\n" +
	"\alcs_qos\x18\x06 \x01(\v2\x0e.lmf.v1.LcsQoSR\x06lcsQos\x12:\n" +
	"\x19periodic_interval_seconds\x18\a \x01(\x05R\x17periodicIntervalSeconds\x12\x1f\n" +
	"\vmax_reports\x18\b \x01(\x05R\n" +
	"maxReports\x129\n" +
	"\x19monitoring_expiry_unix_ms\x18\t \x01(\x03R\x16monitoringExpiryUnixMs\x126\n" +
	"\x17motion_threshold_meters\x18\n" +
	" \x01(\x01R\x15motionThresholdMeters\"Z\n" +
	"\x19EventSubscriptionResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"=\n" +
	"\x12UnsubscribeRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"/\n" +
	"\x13UnsubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9d\x02\n" +
	"\x11EventNotification\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x12\n" +
	"\x04supi\x18\x02 \x01(\tR\x04supi\x125\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\x16.lmf.v1.EventTypeProtoR\teventType\x12E\n" +
	"\x11location_estimate\x18\x04 \x01(\v2\x18.lmf.v1.LocationEstimateR\x10locationEstimate\x12*\n" +
	"\x11timestamp_unix_ms\x18\x05 \x01(\x03R\x0ftimestampUnixMs\x12!\n" +
	"\freport_count\x18\x06 \x01(\x05R\vreportCount\"\x9a\x01\n" +
	"\x11LocationUpdateMsg\x12\x12\n" +
	"\x04supi\x18\x01 \x01(\tR\x04supi\x12E\n" +
	"\x11location_estimate\x18\x02 \x01(\v2\x18.lmf.v1.LocationEstimateR\x10locationEstimate\x12*\n" +
	"\x11timestamp_unix_ms\x18\x03 \x01(\x03R\x0ftimestampUnixMs\"\x87\x01\n" +
	"\x13PrivacyCheckRequest\x12\x12\n" +
	"\x04supi\x18\x01 \x01(\tR\x04supi\x12=\n" +
	"\x0flcs_client_type\x18\x02 \x01(\x0e2\x15.lmf.v1.LcsClientTypeR\rlcsClientType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xbd\x01\n" +
	"\x14PrivacyCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x129\n" +
	"\rprivacy_class\x18\x02 \x01(\x0e2\x14.lmf.v1.PrivacyClassR\fprivacyClass\x12+\n" +
	"\x11notification_sent\x18\x03 \x01(\bR\x10notificationSent\x12#\n" +
	"\rdenial_reason\x18\x04 \x01(\tR\fdenialReason\"S\n" +
	"\x14TokenValidateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x0erequired_scope\x18\x02 \x01(\tR\rrequiredScope\"v\n" +
	"\x15TokenValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x17\n" +
	"\aplmn_id\x18\x03 \x01(\tR\x06plmnId\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*\xab\x01\n" +
	"\x0eEventTypeProto\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EVENT_TYPE_PERIODIC\x10\x01\x12\x13\n" +
	"\x0fEVENT_TYPE_AREA\x10\x02\x12\x15\n" +
	"\x11EVENT_TYPE_MOTION\x10\x03\x12\x1b\n" +
	"\x17EVENT_TYPE_MAX_INTERVAL\x10\x04\x12\x1b\n" +
	"\x17EVENT_TYPE_CANCELLATION\x10\x05*j\n" +
	"\rAreaTypeProto\x12\x19\n" +
	"\x15AREA_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fAREA_TYPE_ENTER\x10\x01\x12\x13\n" +
	"\x0fAREA_TYPE_LEAVE\x10\x02\x12\x14\n" +
	"\x10AREA_TYPE_WITHIN\x10\x03*\x81\x01\n" +
	"\fPrivacyClass\x12\x1d\n" +
	"\x19PRIVACY_CLASS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPRIVACY_CLASS_A\x10\x01\x12\x13\n" +
	"\x0fPRIVACY_CLASS_B\x10\x02\x12\x13\n" +
	"\x0fPRIVACY_CLASS_C\x10\x03\x12\x13\n" +
	"\x0fPRIVACY_CLASS_D\x10\x042\x80\x02\n" +
	"\x13EventManagerService\x12P\n" +
	"\tSubscribe\x12 .lmf.v1.EventSubscriptionRequest\x1a!.lmf.v1.EventSubscriptionResponse\x12F\n" +
	"\vUnsubscribe\x12\x1a.lmf.v1.UnsubscribeRequest\x1a\x1b.lmf.v1.UnsubscribeResponse\x12O\n" +
	"\x15ProcessLocationUpdate\x12\x19.lmf.v1.LocationUpdateMsg\x1a\x1b.lmf.v1.UnsubscribeResponse2\xad\x01\n" +
	"\x12PrivacyAuthService\x12I\n" +
	"\fCheckPrivacy\x12\x1b.lmf.v1.PrivacyCheckRequest\x1a\x1c.lmf.v1.PrivacyCheckResponse\x12L\n" +
	"\rValidateToken\x12\x1c.lmf.v1.TokenValidateRequest\x1a\x1d.lmf.v1.TokenValidateResponseB Z\x1egithub.com/5g-lmf/common/pb;pbb\x06proto3"

var (
	file_lmf_events_proto_rawDescOnce sync.Once
	file_lmf_events_proto_rawDescData []byte
)

func file_lmf_events_proto_rawDescGZIP() []byte {
	file_lmf_events_proto_rawDescOnce.Do(func() {
		file_lmf_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lmf_events_proto_rawDesc), len(file_lmf_events_proto_rawDesc)))
	})
	return file_lmf_events_proto_rawDescData
}

var file_lmf_events_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_lmf_events_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_lmf_events_proto_goTypes = []any{
	(EventTypeProto)(0),               // 0: lmf.v1.EventTypeProto
	(AreaTypeProto)(0),                // 1: lmf.v1.AreaTypeProto
	(PrivacyClass)(0),                 // 2: lmf.v1.PrivacyClass
	(*LatLonMsg)(nil),                 // 3: lmf.v1.LatLonMsg
	(*GeographicArea)(nil),            // 4: lmf.v1.GeographicArea
	(*AreaEventInfoMsg)(nil),          // 5: lmf.v1.AreaEventInfoMsg
	(*EventSubscriptionRequest)(nil),  // 6: lmf.v1.EventSubscriptionRequest
	(*EventSubscriptionResponse)(nil), // 7: lmf.v1.EventSubscriptionResponse
	(*UnsubscribeRequest)(nil),        // 8: lmf.v1.UnsubscribeRequest
	(*UnsubscribeResponse)(nil),       // 9: lmf.v1.UnsubscribeResponse
	(*EventNotification)(nil),         // 10: lmf.v1.EventNotification
	(*LocationUpdateMsg)(nil),         // 11: lmf.v1.LocationUpdateMsg
	(*PrivacyCheckRequest)(nil),       // 12: lmf.v1.PrivacyCheckRequest
	(*PrivacyCheckResponse)(nil),      // 13: lmf.v1.PrivacyCheckResponse
	(*TokenValidateRequest)(nil),      // 14: lmf.v1.TokenValidateRequest
	(*TokenValidateResponse)(nil),     // 15: lmf.v1.TokenValidateResponse
	(*LcsQoS)(nil),                    // 16: lmf.v1.LcsQoS
	(*LocationEstimate)(nil),          // 17: lmf.v1.LocationEstimate
	(LcsClientType)(0),                // 18: lmf.v1.LcsClientType
}
var file_lmf_events_proto_depIdxs = []int32{
	3,  // 0: lmf.v1.GeographicArea.points:type_name -> lmf.v1.LatLonMsg
	3,  // 1: lmf.v1.GeographicArea.center:type_name -> lmf.v1.LatLonMsg
	1,  // 2: lmf.v1.AreaEventInfoMsg.area_type:type_name -> lmf.v1.AreaTypeProto
	4,  // 3: lmf.v1.AreaEventInfoMsg.areas:type_name -> lmf.v1.GeographicArea
	0,  // 4: lmf.v1.EventSubscriptionRequest.event_type:type_name -> lmf.v1.EventTypeProto
	5,  // 5: lmf.v1.EventSubscriptionRequest.area_event_info:type_name -> lmf.v1.AreaEventInfoMsg
	16, // 6: lmf.v1.EventSubscriptionRequest.lcs_qos:type_name -> lmf.v1.LcsQoS
	0,  // 7: lmf.v1.EventNotification.event_type:type_name -> lmf.v1.EventTypeProto
	17, // 8: lmf.v1.EventNotification.location_estimate:type_name -> lmf.v1.LocationEstimate
	17, // 9: lmf.v1.LocationUpdateMsg.location_estimate:type_name -> lmf.v1.LocationEstimate
	18, // 10: lmf.v1.PrivacyCheckRequest.lcs_client_type:type_name -> lmf.v1.LcsClientType
	2,  // 11: lmf.v1.PrivacyCheckResponse.privacy_class:type_name -> lmf.v1.PrivacyClass
	6,  // 12: lmf.v1.EventManagerService.Subscribe:input_type -> lmf.v1.EventSubscriptionRequest
	8,  // 13: lmf.v1.EventManagerService.Unsubscribe:input_type -> lmf.v1.UnsubscribeRequest
	11, // 14: lmf.v1.EventManagerService.ProcessLocationUpdate:input_type -> lmf.v1.LocationUpdateMsg
	12, // 15: lmf.v1.PrivacyAuthService.CheckPrivacy:input_type -> lmf.v1.PrivacyCheckRequest
	14, // 16: lmf.v1.PrivacyAuthService.ValidateToken:input_type -> lmf.v1.TokenValidateRequest
	7,  // 17: lmf.v1.EventManagerService.Subscribe:output_type -> lmf.v1.EventSubscriptionResponse
	9,  // 18: lmf.v1.EventManagerService.Unsubscribe:output_type -> lmf.v1.UnsubscribeResponse
	9,  // 19: lmf.v1.EventManagerService.ProcessLocationUpdate:output_type -> lmf.v1.UnsubscribeResponse
	13, // 20: lmf.v1.PrivacyAuthService.CheckPrivacy:output_type -> lmf.v1.PrivacyCheckResponse
	15, // 21: lmf.v1.PrivacyAuthService.ValidateToken:output_type -> lmf.v1.TokenValidateResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_lmf_events_proto_init() }
func file_lmf_events_proto_init() {
	if File_lmf_events_proto != nil {
		return
	}
	file_lmf_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lmf_events_proto_rawDesc), len(file_lmf_events_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_lmf_events_proto_goTypes,
		DependencyIndexes: file_lmf_events_proto_depIdxs,
		EnumInfos:         file_lmf_events_proto_enumTypes,
		MessageInfos:      file_lmf_events_proto_msgTypes,
	}.Build()
	File_lmf_events_proto = out.File
	file_lmf_events_proto_goTypes = nil
	file_lmf_events_proto_depIdxs = nil
}
