// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: lmf_common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PositioningMethod identifies the UE positioning technique
type PositioningMethod int32

const (
	PositioningMethod_POSITIONING_METHOD_UNSPECIFIED  PositioningMethod = 0
	PositioningMethod_POSITIONING_METHOD_AUTO         PositioningMethod = 1
	PositioningMethod_POSITIONING_METHOD_A_GNSS       PositioningMethod = 2
	PositioningMethod_POSITIONING_METHOD_DL_TDOA      PositioningMethod = 3
	PositioningMethod_POSITIONING_METHOD_OTDOA        PositioningMethod = 4
	PositioningMethod_POSITIONING_METHOD_NR_ECID      PositioningMethod = 5
	PositioningMethod_POSITIONING_METHOD_NR_MULTI_RTT PositioningMethod = 6
	PositioningMethod_POSITIONING_METHOD_WLAN         PositioningMethod = 7
	PositioningMethod_POSITIONING_METHOD_BLUETOOTH    PositioningMethod = 8
	PositioningMethod_POSITIONING_METHOD_BAROMETRIC   PositioningMethod = 9
	PositioningMethod_POSITIONING_METHOD_CELL_ID      PositioningMethod = 10
)

// Enum value maps for PositioningMethod.
var (
	PositioningMethod_name = map[int32]string{
		0:  "POSITIONING_METHOD_UNSPECIFIED",
		1:  "POSITIONING_METHOD_AUTO",
		2:  "POSITIONING_METHOD_A_GNSS",
		3:  "POSITIONING_METHOD_DL_TDOA",
		4:  "POSITIONING_METHOD_OTDOA",
		5:  "POSITIONING_METHOD_NR_ECID",
		6:  "POSITIONING_METHOD_NR_MULTI_RTT",
		7:  "POSITIONING_METHOD_WLAN",
		8:  "POSITIONING_METHOD_BLUETOOTH",
		9:  "POSITIONING_METHOD_BAROMETRIC",
		10: "POSITIONING_METHOD_CELL_ID",
	}
	PositioningMethod_value = map[string]int32{
		"POSITIONING_METHOD_UNSPECIFIED":  0,
		"POSITIONING_METHOD_AUTO":         1,
		"POSITIONING_METHOD_A_GNSS":       2,
		"POSITIONING_METHOD_DL_TDOA":      3,
		"POSITIONING_METHOD_OTDOA":        4,
		"POSITIONING_METHOD_NR_ECID":      5,
		"POSITIONING_METHOD_NR_MULTI_RTT": 6,
		"POSITIONING_METHOD_WLAN":         7,
		"POSITIONING_METHOD_BLUETOOTH":    8,
		"POSITIONING_METHOD_BAROMETRIC":   9,
		"POSITIONING_METHOD_CELL_ID":      10,
	}
)

func (x PositioningMethod) Enum() *PositioningMethod {
	p := new(PositioningMethod)
	*p = x
	return p
}

func (x PositioningMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositioningMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_lmf_common_proto_enumTypes[0].Descriptor()
}

func (PositioningMethod) Type() protoreflect.EnumType {
	return &file_lmf_common_proto_enumTypes[0]
}

func (x PositioningMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositioningMethod.Descriptor instead.
func (PositioningMethod) EnumDescriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{0}
}

// ResponseTimeClass defines QoS response time requirements
type ResponseTimeClass int32

const (
	ResponseTimeClass_RESPONSE_TIME_UNSPECIFIED       ResponseTimeClass = 0
	ResponseTimeClass_RESPONSE_TIME_NO_DELAY          ResponseTimeClass = 1
	ResponseTimeClass_RESPONSE_TIME_LOW_DELAY         ResponseTimeClass = 2
	ResponseTimeClass_RESPONSE_TIME_DELAY_TOLERANT    ResponseTimeClass = 3
	ResponseTimeClass_RESPONSE_TIME_DELAY_TOLERANT_V2 ResponseTimeClass = 4
)

// Enum value maps for ResponseTimeClass.
var (
	ResponseTimeClass_name = map[int32]string{
		0: "RESPONSE_TIME_UNSPECIFIED",
		1: "RESPONSE_TIME_NO_DELAY",
		2: "RESPONSE_TIME_LOW_DELAY",
		3: "RESPONSE_TIME_DELAY_TOLERANT",
		4: "RESPONSE_TIME_DELAY_TOLERANT_V2",
	}
	ResponseTimeClass_value = map[string]int32{
		"RESPONSE_TIME_UNSPECIFIED":       0,
		"RESPONSE_TIME_NO_DELAY":          1,
		"RESPONSE_TIME_LOW_DELAY":         2,
		"RESPONSE_TIME_DELAY_TOLERANT":    3,
		"RESPONSE_TIME_DELAY_TOLERANT_V2": 4,
	}
)

func (x ResponseTimeClass) Enum() *ResponseTimeClass {
	p := new(ResponseTimeClass)
	*p = x
	return p
}

func (x ResponseTimeClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseTimeClass) Descriptor() protoreflect.EnumDescriptor {
	return file_lmf_common_proto_enumTypes[1].Descriptor()
}

func (ResponseTimeClass) Type() protoreflect.EnumType {
	return &file_lmf_common_proto_enumTypes[1]
}

func (x ResponseTimeClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseTimeClass.Descriptor instead.
func (ResponseTimeClass) EnumDescriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{1}
}

// AccuracyFulfilmentIndicator indicates whether QoS was met
type AccuracyFulfilmentIndicator int32

const (
	AccuracyFulfilmentIndicator_ACCURACY_FULFILMENT_UNSPECIFIED         AccuracyFulfilmentIndicator = 0
	AccuracyFulfilmentIndicator_ACCURACY_FULFILMENT_REQUESTED_FULFILLED AccuracyFulfilmentIndicator = 1
	AccuracyFulfilmentIndicator_ACCURACY_FULFILMENT_ATTEMPTED_FAILED    AccuracyFulfilmentIndicator = 2
	AccuracyFulfilmentIndicator_ACCURACY_FULFILMENT_NOT_ATTEMPTED       AccuracyFulfilmentIndicator = 3
)

// Enum value maps for AccuracyFulfilmentIndicator.
var (
	AccuracyFulfilmentIndicator_name = map[int32]string{
		0: "ACCURACY_FULFILMENT_UNSPECIFIED",
		1: "ACCURACY_FULFILMENT_REQUESTED_FULFILLED",
		2: "ACCURACY_FULFILMENT_ATTEMPTED_FAILED",
		3: "ACCURACY_FULFILMENT_NOT_ATTEMPTED",
	}
	AccuracyFulfilmentIndicator_value = map[string]int32{
		"ACCURACY_FULFILMENT_UNSPECIFIED":         0,
		"ACCURACY_FULFILMENT_REQUESTED_FULFILLED": 1,
		"ACCURACY_FULFILMENT_ATTEMPTED_FAILED":    2,
		"ACCURACY_FULFILMENT_NOT_ATTEMPTED":       3,
	}
)

func (x AccuracyFulfilmentIndicator) Enum() *AccuracyFulfilmentIndicator {
	p := new(AccuracyFulfilmentIndicator)
	*p = x
	return p
}

func (x AccuracyFulfilmentIndicator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccuracyFulfilmentIndicator) Descriptor() protoreflect.EnumDescriptor {
	return file_lmf_common_proto_enumTypes[2].Descriptor()
}

func (AccuracyFulfilmentIndicator) Type() protoreflect.EnumType {
	return &file_lmf_common_proto_enumTypes[2]
}

func (x AccuracyFulfilmentIndicator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccuracyFulfilmentIndicator.Descriptor instead.
func (AccuracyFulfilmentIndicator) EnumDescriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{2}
}

// SessionStatus tracks LCS session lifecycle
type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED           SessionStatus = 0
	SessionStatus_SESSION_STATUS_INIT                  SessionStatus = 1
	SessionStatus_SESSION_STATUS_PROCESSING            SessionStatus = 2
	SessionStatus_SESSION_STATUS_AWAITING_MEASUREMENTS SessionStatus = 3
	SessionStatus_SESSION_STATUS_COMPUTING             SessionStatus = 4
	SessionStatus_SESSION_STATUS_COMPLETED             SessionStatus = 5
	SessionStatus_SESSION_STATUS_FAILED                SessionStatus = 6
	SessionStatus_SESSION_STATUS_CANCELLED             SessionStatus = 7
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_INIT",
		2: "SESSION_STATUS_PROCESSING",
		3: "SESSION_STATUS_AWAITING_MEASUREMENTS",
		4: "SESSION_STATUS_COMPUTING",
		5: "SESSION_STATUS_COMPLETED",
		6: "SESSION_STATUS_FAILED",
		7: "SESSION_STATUS_CANCELLED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED":           0,
		"SESSION_STATUS_INIT":                  1,
		"SESSION_STATUS_PROCESSING":            2,
		"SESSION_STATUS_AWAITING_MEASUREMENTS": 3,
		"SESSION_STATUS_COMPUTING":             4,
		"SESSION_STATUS_COMPLETED":             5,
		"SESSION_STATUS_FAILED":                6,
		"SESSION_STATUS_CANCELLED":             7,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lmf_common_proto_enumTypes[3].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_lmf_common_proto_enumTypes[3]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{3}
}

// LcsClientType identifies the LCS requesting entity
type LcsClientType int32

const (
	LcsClientType_LCS_CLIENT_TYPE_UNSPECIFIED        LcsClientType = 0
	LcsClientType_LCS_CLIENT_TYPE_EMERGENCY_SERVICES LcsClientType = 1
	LcsClientType_LCS_CLIENT_TYPE_VALUE_ADDED        LcsClientType = 2
	LcsClientType_LCS_CLIENT_TYPE_PLMN_OPERATOR      LcsClientType = 3
	LcsClientType_LCS_CLIENT_TYPE_LAWFUL_INTERCEPT   LcsClientType = 4
	LcsClientType_LCS_CLIENT_TYPE_GMLC               LcsClientType = 5
)

// Enum value maps for LcsClientType.
var (
	LcsClientType_name = map[int32]string{
		0: "LCS_CLIENT_TYPE_UNSPECIFIED",
		1: "LCS_CLIENT_TYPE_EMERGENCY_SERVICES",
		2: "LCS_CLIENT_TYPE_VALUE_ADDED",
		3: "LCS_CLIENT_TYPE_PLMN_OPERATOR",
		4: "LCS_CLIENT_TYPE_LAWFUL_INTERCEPT",
		5: "LCS_CLIENT_TYPE_GMLC",
	}
	LcsClientType_value = map[string]int32{
		"LCS_CLIENT_TYPE_UNSPECIFIED":        0,
		"LCS_CLIENT_TYPE_EMERGENCY_SERVICES": 1,
		"LCS_CLIENT_TYPE_VALUE_ADDED":        2,
		"LCS_CLIENT_TYPE_PLMN_OPERATOR":      3,
		"LCS_CLIENT_TYPE_LAWFUL_INTERCEPT":   4,
		"LCS_CLIENT_TYPE_GMLC":               5,
	}
)

func (x LcsClientType) Enum() *LcsClientType {
	p := new(LcsClientType)
	*p = x
	return p
}

func (x LcsClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LcsClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_lmf_common_proto_enumTypes[4].Descriptor()
}

func (LcsClientType) Type() protoreflect.EnumType {
	return &file_lmf_common_proto_enumTypes[4]
}

func (x LcsClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LcsClientType.Descriptor instead.
func (LcsClientType) EnumDescriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{4}
}

// PlmnId represents a PLMN identifier
type PlmnId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mcc           string                 `protobuf:"bytes,1,opt,name=mcc,proto3" json:"mcc,omitempty"`
	Mnc           string                 `protobuf:"bytes,2,opt,name=mnc,proto3" json:"mnc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlmnId) Reset() {
	*x = PlmnId{}
	mi := &file_lmf_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlmnId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlmnId) ProtoMessage() {}

func (x *PlmnId) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlmnId.ProtoReflect.Descriptor instead.
func (*PlmnId) Descriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{0}
}

func (x *PlmnId) GetMcc() string {
	if x != nil {
		return x.Mcc
	}
	return ""
}

func (x *PlmnId) GetMnc() string {
	if x != nil {
		return x.Mnc
	}
	return ""
}

// LcsQoS defines location QoS requirements
type LcsQoS struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	HorizontalAccuracyMeters int32                  `protobuf:"varint,1,opt,name=horizontal_accuracy_meters,json=horizontalAccuracyMeters,proto3" json:"horizontal_accuracy_meters,omitempty"`
	VerticalAccuracyMeters   int32                  `protobuf:"varint,2,opt,name=vertical_accuracy_meters,json=verticalAccuracyMeters,proto3" json:"vertical_accuracy_meters,omitempty"`
	VerticalCoordRequired    bool                   `protobuf:"varint,3,opt,name=vertical_coord_required,json=verticalCoordRequired,proto3" json:"vertical_coord_required,omitempty"`
	ResponseTime             ResponseTimeClass      `protobuf:"varint,4,opt,name=response_time,json=responseTime,proto3,enum=lmf.v1.ResponseTimeClass" json:"response_time,omitempty"`
	VelocityRequested        bool                   `protobuf:"varint,5,opt,name=velocity_requested,json=velocityRequested,proto3" json:"velocity_requested,omitempty"`
	ConfidencePercent        int32                  `protobuf:"varint,6,opt,name=confidence_percent,json=confidencePercent,proto3" json:"confidence_percent,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LcsQoS) Reset() {
	*x = LcsQoS{}
	mi := &file_lmf_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LcsQoS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LcsQoS) ProtoMessage() {}

func (x *LcsQoS) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LcsQoS.ProtoReflect.Descriptor instead.
func (*LcsQoS) Descriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{1}
}

func (x *LcsQoS) GetHorizontalAccuracyMeters() int32 {
	if x != nil {
		return x.HorizontalAccuracyMeters
	}
	return 0
}

func (x *LcsQoS) GetVerticalAccuracyMeters() int32 {
	if x != nil {
		return x.VerticalAccuracyMeters
	}
	return 0
}

func (x *LcsQoS) GetVerticalCoordRequired() bool {
	if x != nil {
		return x.VerticalCoordRequired
	}
	return false
}

func (x *LcsQoS) GetResponseTime() ResponseTimeClass {
	if x != nil {
		return x.ResponseTime
	}
	return ResponseTimeClass_RESPONSE_TIME_UNSPECIFIED
}

func (x *LcsQoS) GetVelocityRequested() bool {
	if x != nil {
		return x.VelocityRequested
	}
	return false
}

func (x *LcsQoS) GetConfidencePercent() int32 {
	if x != nil {
		return x.ConfidencePercent
	}
	return 0
}

// LocationEstimate carries a UE position result
type LocationEstimate struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Shape                 string                 `protobuf:"bytes,1,opt,name=shape,proto3" json:"shape,omitempty"`
	Latitude              float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude             float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude              float64                `protobuf:"fixed64,4,opt,name=altitude,proto3" json:"altitude,omitempty"`
	HorizontalUncertainty float64                `protobuf:"fixed64,5,opt,name=horizontal_uncertainty,json=horizontalUncertainty,proto3" json:"horizontal_uncertainty,omitempty"`
	UncertaintySemiMajor  float64                `protobuf:"fixed64,6,opt,name=uncertainty_semi_major,json=uncertaintySemiMajor,proto3" json:"uncertainty_semi_major,omitempty"`
	UncertaintySemiMinor  float64                `protobuf:"fixed64,7,opt,name=uncertainty_semi_minor,json=uncertaintySemiMinor,proto3" json:"uncertainty_semi_minor,omitempty"`
	OrientationMajorAxis  int32                  `protobuf:"varint,8,opt,name=orientation_major_axis,json=orientationMajorAxis,proto3" json:"orientation_major_axis,omitempty"`
	VerticalUncertainty   float64                `protobuf:"fixed64,9,opt,name=vertical_uncertainty,json=verticalUncertainty,proto3" json:"vertical_uncertainty,omitempty"`
	Confidence            int32                  `protobuf:"varint,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	TimestampUnixMs       int64                  `protobuf:"varint,11,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LocationEstimate) Reset() {
	*x = LocationEstimate{}
	mi := &file_lmf_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationEstimate) ProtoMessage() {}

func (x *LocationEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationEstimate.ProtoReflect.Descriptor instead.
func (*LocationEstimate) Descriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{2}
}

func (x *LocationEstimate) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *LocationEstimate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationEstimate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationEstimate) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *LocationEstimate) GetHorizontalUncertainty() float64 {
	if x != nil {
		return x.HorizontalUncertainty
	}
	return 0
}

func (x *LocationEstimate) GetUncertaintySemiMajor() float64 {
	if x != nil {
		return x.UncertaintySemiMajor
	}
	return 0
}

func (x *LocationEstimate) GetUncertaintySemiMinor() float64 {
	if x != nil {
		return x.UncertaintySemiMinor
	}
	return 0
}

func (x *LocationEstimate) GetOrientationMajorAxis() int32 {
	if x != nil {
		return x.OrientationMajorAxis
	}
	return 0
}

func (x *LocationEstimate) GetVerticalUncertainty() float64 {
	if x != nil {
		return x.VerticalUncertainty
	}
	return 0
}

func (x *LocationEstimate) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *LocationEstimate) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// VelocityEstimate carries UE velocity
type VelocityEstimate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VelocityType    string                 `protobuf:"bytes,1,opt,name=velocity_type,json=velocityType,proto3" json:"velocity_type,omitempty"`
	HSpeedMps       float64                `protobuf:"fixed64,2,opt,name=h_speed_mps,json=hSpeedMps,proto3" json:"h_speed_mps,omitempty"`
	BearingDegrees  float64                `protobuf:"fixed64,3,opt,name=bearing_degrees,json=bearingDegrees,proto3" json:"bearing_degrees,omitempty"`
	VSpeedMps       float64                `protobuf:"fixed64,4,opt,name=v_speed_mps,json=vSpeedMps,proto3" json:"v_speed_mps,omitempty"`
	VDirection      string                 `protobuf:"bytes,5,opt,name=v_direction,json=vDirection,proto3" json:"v_direction,omitempty"`
	HUncertaintyMps float64                `protobuf:"fixed64,6,opt,name=h_uncertainty_mps,json=hUncertaintyMps,proto3" json:"h_uncertainty_mps,omitempty"`
	VUncertaintyMps float64                `protobuf:"fixed64,7,opt,name=v_uncertainty_mps,json=vUncertaintyMps,proto3" json:"v_uncertainty_mps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VelocityEstimate) Reset() {
	*x = VelocityEstimate{}
	mi := &file_lmf_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VelocityEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VelocityEstimate) ProtoMessage() {}

func (x *VelocityEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VelocityEstimate.ProtoReflect.Descriptor instead.
func (*VelocityEstimate) Descriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{3}
}

func (x *VelocityEstimate) GetVelocityType() string {
	if x != nil {
		return x.VelocityType
	}
	return ""
}

func (x *VelocityEstimate) GetHSpeedMps() float64 {
	if x != nil {
		return x.HSpeedMps
	}
	return 0
}

func (x *VelocityEstimate) GetBearingDegrees() float64 {
	if x != nil {
		return x.BearingDegrees
	}
	return 0
}

func (x *VelocityEstimate) GetVSpeedMps() float64 {
	if x != nil {
		return x.VSpeedMps
	}
	return 0
}

func (x *VelocityEstimate) GetVDirection() string {
	if x != nil {
		return x.VDirection
	}
	return ""
}

func (x *VelocityEstimate) GetHUncertaintyMps() float64 {
	if x != nil {
		return x.HUncertaintyMps
	}
	return 0
}

func (x *VelocityEstimate) GetVUncertaintyMps() float64 {
	if x != nil {
		return x.VUncertaintyMps
	}
	return 0
}

// PositionEstimate is the internal computed position
type PositionEstimate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Latitude        float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude        float64                `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	SigmaLat        float64                `protobuf:"fixed64,4,opt,name=sigma_lat,json=sigmaLat,proto3" json:"sigma_lat,omitempty"`
	SigmaLon        float64                `protobuf:"fixed64,5,opt,name=sigma_lon,json=sigmaLon,proto3" json:"sigma_lon,omitempty"`
	SigmaAlt        float64                `protobuf:"fixed64,6,opt,name=sigma_alt,json=sigmaAlt,proto3" json:"sigma_alt,omitempty"`
	Confidence      int32                  `protobuf:"varint,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Method          PositioningMethod      `protobuf:"varint,8,opt,name=method,proto3,enum=lmf.v1.PositioningMethod" json:"method,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,9,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PositionEstimate) Reset() {
	*x = PositionEstimate{}
	mi := &file_lmf_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionEstimate) ProtoMessage() {}

func (x *PositionEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionEstimate.ProtoReflect.Descriptor instead.
func (*PositionEstimate) Descriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{4}
}

func (x *PositionEstimate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PositionEstimate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PositionEstimate) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *PositionEstimate) GetSigmaLat() float64 {
	if x != nil {
		return x.SigmaLat
	}
	return 0
}

func (x *PositionEstimate) GetSigmaLon() float64 {
	if x != nil {
		return x.SigmaLon
	}
	return 0
}

func (x *PositionEstimate) GetSigmaAlt() float64 {
	if x != nil {
		return x.SigmaAlt
	}
	return 0
}

func (x *PositionEstimate) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PositionEstimate) GetMethod() PositioningMethod {
	if x != nil {
		return x.Method
	}
	return PositioningMethod_POSITIONING_METHOD_UNSPECIFIED
}

func (x *PositionEstimate) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// UeCapabilities holds UE positioning capabilities
type UeCapabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GnssSupported       bool                   `protobuf:"varint,1,opt,name=gnss_supported,json=gnssSupported,proto3" json:"gnss_supported,omitempty"`
	GnssConstellations  []string               `protobuf:"bytes,2,rep,name=gnss_constellations,json=gnssConstellations,proto3" json:"gnss_constellations,omitempty"`
	DlTdoaSupported     bool                   `protobuf:"varint,3,opt,name=dl_tdoa_supported,json=dlTdoaSupported,proto3" json:"dl_tdoa_supported,omitempty"`
	MultiRttSupported   bool                   `protobuf:"varint,4,opt,name=multi_rtt_supported,json=multiRttSupported,proto3" json:"multi_rtt_supported,omitempty"`
	WlanSupported       bool                   `protobuf:"varint,5,opt,name=wlan_supported,json=wlanSupported,proto3" json:"wlan_supported,omitempty"`
	BluetoothSupported  bool                   `protobuf:"varint,6,opt,name=bluetooth_supported,json=bluetoothSupported,proto3" json:"bluetooth_supported,omitempty"`
	BarometricSupported bool                   `protobuf:"varint,7,opt,name=barometric_supported,json=barometricSupported,proto3" json:"barometric_supported,omitempty"`
	EcidSupported       bool                   `protobuf:"varint,8,opt,name=ecid_supported,json=ecidSupported,proto3" json:"ecid_supported,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UeCapabilities) Reset() {
	*x = UeCapabilities{}
	mi := &file_lmf_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UeCapabilities) ProtoMessage() {}

func (x *UeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UeCapabilities.ProtoReflect.Descriptor instead.
func (*UeCapabilities) Descriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{5}
}

func (x *UeCapabilities) GetGnssSupported() bool {
	if x != nil {
		return x.GnssSupported
	}
	return false
}

func (x *UeCapabilities) GetGnssConstellations() []string {
	if x != nil {
		return x.GnssConstellations
	}
	return nil
}

func (x *UeCapabilities) GetDlTdoaSupported() bool {
	if x != nil {
		return x.DlTdoaSupported
	}
	return false
}

func (x *UeCapabilities) GetMultiRttSupported() bool {
	if x != nil {
		return x.MultiRttSupported
	}
	return false
}

func (x *UeCapabilities) GetWlanSupported() bool {
	if x != nil {
		return x.WlanSupported
	}
	return false
}

func (x *UeCapabilities) GetBluetoothSupported() bool {
	if x != nil {
		return x.BluetoothSupported
	}
	return false
}

func (x *UeCapabilities) GetBarometricSupported() bool {
	if x != nil {
		return x.BarometricSupported
	}
	return false
}

func (x *UeCapabilities) GetEcidSupported() bool {
	if x != nil {
		return x.EcidSupported
	}
	return false
}

// PrsConfiguration holds NR PRS configuration per TS 38.305
type PrsConfiguration struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PrsId                int32                  `protobuf:"varint,1,opt,name=prs_id,json=prsId,proto3" json:"prs_id,omitempty"`
	NrofPrsResources     int32                  `protobuf:"varint,2,opt,name=nrof_prs_resources,json=nrofPrsResources,proto3" json:"nrof_prs_resources,omitempty"`
	PrsBandwidthMhz      int32                  `protobuf:"varint,3,opt,name=prs_bandwidth_mhz,json=prsBandwidthMhz,proto3" json:"prs_bandwidth_mhz,omitempty"`
	PrsSubcarrierSpacing int32                  `protobuf:"varint,4,opt,name=prs_subcarrier_spacing,json=prsSubcarrierSpacing,proto3" json:"prs_subcarrier_spacing,omitempty"`
	PrsCombSize          int32                  `protobuf:"varint,5,opt,name=prs_comb_size,json=prsCombSize,proto3" json:"prs_comb_size,omitempty"`
	DlPrsNumSymbols      int32                  `protobuf:"varint,6,opt,name=dl_prs_num_symbols,json=dlPrsNumSymbols,proto3" json:"dl_prs_num_symbols,omitempty"`
	PrsOccasionsDuration int32                  `protobuf:"varint,7,opt,name=prs_occasions_duration,json=prsOccasionsDuration,proto3" json:"prs_occasions_duration,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PrsConfiguration) Reset() {
	*x = PrsConfiguration{}
	mi := &file_lmf_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrsConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrsConfiguration) ProtoMessage() {}

func (x *PrsConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrsConfiguration.ProtoReflect.Descriptor instead.
func (*PrsConfiguration) Descriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{6}
}

func (x *PrsConfiguration) GetPrsId() int32 {
	if x != nil {
		return x.PrsId
	}
	return 0
}

func (x *PrsConfiguration) GetNrofPrsResources() int32 {
	if x != nil {
		return x.NrofPrsResources
	}
	return 0
}

func (x *PrsConfiguration) GetPrsBandwidthMhz() int32 {
	if x != nil {
		return x.PrsBandwidthMhz
	}
	return 0
}

func (x *PrsConfiguration) GetPrsSubcarrierSpacing() int32 {
	if x != nil {
		return x.PrsSubcarrierSpacing
	}
	return 0
}

func (x *PrsConfiguration) GetPrsCombSize() int32 {
	if x != nil {
		return x.PrsCombSize
	}
	return 0
}

func (x *PrsConfiguration) GetDlPrsNumSymbols() int32 {
	if x != nil {
		return x.DlPrsNumSymbols
	}
	return 0
}

func (x *PrsConfiguration) GetPrsOccasionsDuration() int32 {
	if x != nil {
		return x.PrsOccasionsDuration
	}
	return 0
}

// CellGeometry holds physical cell location
type CellGeometry struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Nci                  string                 `protobuf:"bytes,1,opt,name=nci,proto3" json:"nci,omitempty"`
	PlmnMcc              string                 `protobuf:"bytes,2,opt,name=plmn_mcc,json=plmnMcc,proto3" json:"plmn_mcc,omitempty"`
	PlmnMnc              string                 `protobuf:"bytes,3,opt,name=plmn_mnc,json=plmnMnc,proto3" json:"plmn_mnc,omitempty"`
	Latitude             float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude             float64                `protobuf:"fixed64,6,opt,name=altitude,proto3" json:"altitude,omitempty"`
	AntennaSectorAzimuth int32                  `protobuf:"varint,7,opt,name=antenna_sector_azimuth,json=antennaSectorAzimuth,proto3" json:"antenna_sector_azimuth,omitempty"`
	AntennaSectorWidth   int32                  `protobuf:"varint,8,opt,name=antenna_sector_width,json=antennaSectorWidth,proto3" json:"antenna_sector_width,omitempty"`
	SyncOffsetNs         int64                  `protobuf:"varint,9,opt,name=sync_offset_ns,json=syncOffsetNs,proto3" json:"sync_offset_ns,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CellGeometry) Reset() {
	*x = CellGeometry{}
	mi := &file_lmf_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellGeometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellGeometry) ProtoMessage() {}

func (x *CellGeometry) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellGeometry.ProtoReflect.Descriptor instead.
func (*CellGeometry) Descriptor() ([]byte, []int) {
	return file_lmf_common_proto_rawDescGZIP(), []int{7}
}

func (x *CellGeometry) GetNci() string {
	if x != nil {
		return x.Nci
	}
	return ""
}

func (x *CellGeometry) GetPlmnMcc() string {
	if x != nil {
		return x.PlmnMcc
	}
	return ""
}

func (x *CellGeometry) GetPlmnMnc() string {
	if x != nil {
		return x.PlmnMnc
	}
	return ""
}

func (x *CellGeometry) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CellGeometry) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CellGeometry) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *CellGeometry) GetAntennaSectorAzimuth() int32 {
	if x != nil {
		return x.AntennaSectorAzimuth
	}
	return 0
}

func (x *CellGeometry) GetAntennaSectorWidth() int32 {
	if x != nil {
		return x.AntennaSectorWidth
	}
	return 0
}

func (x *CellGeometry) GetSyncOffsetNs() int64 {
	if x != nil {
		return x.SyncOffsetNs
	}
	return 0
}

var File_lmf_common_proto protoreflect.FileDescriptor

const file_lmf_common_proto_rawDesc = "" +
	"\n" +
	"\x10lmf_common.proto\x12\x06lmf.v1\",\n" +
	"\x06PlmnId\x12\x10\n" +
	"\x03mcc\x18\x01 \x01(\tR\x03mcc\x12\x10\n" +
	"\x03mnc\x18\x02 \x01(\tR\x03mnc\"\xd6\x02\n" +
	"\x06LcsQoS\x12<\n" +
	"\x1ahorizontal_accuracy_meters\x18\x01 \x01(\x05R\x18horizontalAccuracyMeters\x128\n" +
	"\x18vertical_accuracy_meters\x18\x02 \x01(\x05R\x16verticalAccuracyMeters\x126\n" +
	"\x17vertical_coord_required\x18\x03 \x01(\bR\x15verticalCoordRequired\x12>\n" +
	"\rresponse_time\x18\x04 \x01(\x0e2\x19.lmf.v1.ResponseTimeClassR\fresponseTime\x12-\n" +
	"\x12velocity_requested\x18\x05 \x01(\bR\x11velocityRequested\x12-\n" +
	"\x12confidence_percent\x18\x06 \x01(\x05R\x11confidencePercent\"\xd6\x03\n" +
	"\x10LocationEstimate\x12\x14\n" +
	"\x05shape\x18\x01 \x01(\tR\x05shape\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x04 \x01(\x01R\baltitude\x125\n" +
	"\x16horizontal_uncertainty\x18\x05 \x01(\x01R\x15horizontalUncertainty\x124\n" +
	"\x16uncertainty_semi_major\x18\x06 \x01(\x01R\x14uncertaintySemiMajor\x124\n" +
	"\x16uncertainty_semi_minor\x18\a \x01(\x01R\x14uncertaintySemiMinor\x124\n" +
	"\x16orientation_major_axis\x18\b \x01(\x05R\x14orientationMajorAxis\x121\n" +
	"\x14vertical_uncertainty\x18\t \x01(\x01R\x13verticalUncertainty\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x05R\n" +
	"confidence\x12*\n" +
	"\x11timestamp_unix_ms\x18\v \x01(\x03R\x0ftimestampUnixMs\"\x99\x02\n" +
	"\x10VelocityEstimate\x12#\n" +
	"\rvelocity_type\x18\x01 \x01(\tR\fvelocityType\x12\x1e\n" +
	"\vh_speed_mps\x18\x02 \x01(\x01R\thSpeedMps\x12'\n" +
	"\x0fbearing_degrees\x18\x03 \x01(\x01R\x0ebearingDegrees\x12\x1e\n" +
	"\vv_speed_mps\x18\x04 \x01(\x01R\tvSpeedMps\x12\x1f\n" +
	"\vv_direction\x18\x05 \x01(\tR\n" +
	"vDirection\x12*\n" +
	"\x11h_uncertainty_mps\x18\x06 \x01(\x01R\x0fhUncertaintyMps\x12*\n" +
	"\x11v_uncertainty_mps\x18\a \x01(\x01R\x0fvUncertaintyMps\"\xbe\x02\n" +
	"\x10PositionEstimate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x03 \x01(\x01R\baltitude\x12\x1b\n" +
	"\tsigma_lat\x18\x04 \x01(\x01R\bsigmaLat\x12\x1b\n" +
	"\tsigma_lon\x18\x05 \x01(\x01R\bsigmaLon\x12\x1b\n" +
	"\tsigma_alt\x18\x06 \x01(\x01R\bsigmaAlt\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x05R\n" +
	"confidence\x121\n" +
	"\x06method\x18\b \x01(\x0e2\x19.lmf.v1.PositioningMethodR\x06method\x12*\n" +
	"\x11timestamp_unix_ms\x18\t \x01(\x03R\x0ftimestampUnixMs\"\xf6\x02\n" +
	"\x0eUeCapabilities\x12%\n" +
	"\x0egnss_supported\x18\x01 \x01(\bR\rgnssSupported\x12/\n" +
	"\x13gnss_constellations\x18\x02 \x03(\tR\x12gnssConstellations\x12*\n" +
	"\x11dl_tdoa_supported\x18\x03 \x01(\bR\x0fdlTdoaSupported\x12.\n" +
	"\x13multi_rtt_supported\x18\x04 \x01(\bR\x11multiRttSupported\x12%\n" +
	"\x0ewlan_supported\x18\x05 \x01(\bR\rwlanSupported\x12/\n" +
	"\x13bluetooth_supported\x18\x06 \x01(\bR\x12bluetoothSupported\x121\n" +
	"\x14barometric_supported\x18\a \x01(\bR\x13barometricSupported\x12%\n" +
	"\x0eecid_supported\x18\b \x01(\bR\recidSupported\"\xc0\x02\n" +
	"\x10PrsConfiguration\x12\x15\n" +
	"\x06prs_id\x18\x01 \x01(\x05R\x05prsId\x12,\n" +
	"\x12nrof_prs_resources\x18\x02 \x01(\x05R\x10nrofPrsResources\x12*\n" +
	"\x11prs_bandwidth_mhz\x18\x03 \x01(\x05R\x0fprsBandwidthMhz\x124\n" +
	"\x16prs_subcarrier_spacing\x18\x04 \x01(\x05R\x14prsSubcarrierSpacing\x12\"\n" +
	"\rprs_comb_size\x18\x05 \x01(\x05R\vprsCombSize\x12+\n" +
	"\x12dl_prs_num_symbols\x18\x06 \x01(\x05R\x0fdlPrsNumSymbols\x124\n" +
	"\x16prs_occasions_duration\x18\a \x01(\x05R\x14prsOccasionsDuration\"\xba\x02\n" +
	"\fCellGeometry\x12\x10\n" +
	"\x03nci\x18\x01 \x01(\tR\x03nci\x12\x19\n" +
	"\bplmn_mcc\x18\x02 \x01(\tR\aplmnMcc\x12\x19\n" +
	"\bplmn_mnc\x18\x03 \x01(\tR\aplmnMnc\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x06 \x01(\x01R\baltitude\x124\n" +
	"\x16antenna_sector_azimuth\x18\a \x01(\x05R\x14antennaSectorAzimuth\x120\n" +
	"\x14antenna_sector_width\x18\b \x01(\x05R\x12antennaSectorWidth\x12$\n" +
	"\x0esync_offset_ns\x18\t \x01(\x03R\fsyncOffsetNs*\xf8\x02\n" +
	"\x11PositioningMethod\x12\"\n" +
	"\x1ePOSITIONING_METHOD_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17POSITIONING_METHOD_AUTO\x10\x01\x12\x1d\n" +
	"\x19POSITIONING_METHOD_A_GNSS\x10\x02\x12\x1e\n" +
	"\x1aPOSITIONING_METHOD_DL_TDOA\x10\x03\x12\x1c\n" +
	"\x18POSITIONING_METHOD_OTDOA\x10\x04\x12\x1e\n" +
	"\x1aPOSITIONING_METHOD_NR_ECID\x10\x05\x12#\n" +
	"\x1fPOSITIONING_METHOD_NR_MULTI_RTT\x10\x06\x12\x1b\n" +
	"\x17POSITIONING_METHOD_WLAN\x10\a\x12 \n" +
	"\x1cPOSITIONING_METHOD_BLUETOOTH\x10\b\x12!\n" +
	"\x1dPOSITIONING_METHOD_BAROMETRIC\x10\t\x12\x1e\n" +
	"\x1aPOSITIONING_METHOD_CELL_ID\x10\n" +
	"*\xb2\x01\n" +
	"\x11ResponseTimeClass\x12\x1d\n" +
	"\x19RESPONSE_TIME_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RESPONSE_TIME_NO_DELAY\x10\x01\x12\x1b\n" +
	"\x17RESPONSE_TIME_LOW_DELAY\x10\x02\x12 \n" +
	"\x1cRESPONSE_TIME_DELAY_TOLERANT\x10\x03\x12#\n" +
	"\x1fRESPONSE_TIME_DELAY_TOLERANT_V2\x10\x04*\xc0\x01\n" +
	"\x1bAccuracyFulfilmentIndicator\x12#\n" +
	"\x1fACCURACY_FULFILMENT_UNSPECIFIED\x10\x00\x12+\n" +
	"'ACCURACY_FULFILMENT_REQUESTED_FULFILLED\x10\x01\x12(\n" +
	"$ACCURACY_FULFILMENT_ATTEMPTED_FAILED\x10\x02\x12%\n" +
	"!ACCURACY_FULFILMENT_NOT_ATTEMPTED\x10\x03*\x86\x02\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SESSION_STATUS_INIT\x10\x01\x12\x1d\n" +
	"\x19SESSION_STATUS_PROCESSING\x10\x02\x12(\n" +
	"$SESSION_STATUS_AWAITING_MEASUREMENTS\x10\x03\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPUTING\x10\x04\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPLETED\x10\x05\x12\x19\n" +
	"\x15SESSION_STATUS_FAILED\x10\x06\x12\x1c\n" +
	"\x18SESSION_STATUS_CANCELLED\x10\a*\xdc\x01\n" +
	"\rLcsClientType\x12\x1f\n" +
	"\x1bLCS_CLIENT_TYPE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"LCS_CLIENT_TYPE_EMERGENCY_SERVICES\x10\x01\x12\x1f\n" +
	"\x1bLCS_CLIENT_TYPE_VALUE_ADDED\x10\x02\x12!\n" +
	"\x1dLCS_CLIENT_TYPE_PLMN_OPERATOR\x10\x03\x12$\n" +
	" LCS_CLIENT_TYPE_LAWFUL_INTERCEPT\x10\x04\x12\x18\n" +
	"\x14LCS_CLIENT_TYPE_GMLC\x10\x05B Z\x1egithub.com/5g-lmf/common/pb;pbb\x06proto3"

var (
	file_lmf_common_proto_rawDescOnce sync.Once
	file_lmf_common_proto_rawDescData []byte
)

func file_lmf_common_proto_rawDescGZIP() []byte {
	file_lmf_common_proto_rawDescOnce.Do(func() {
		file_lmf_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lmf_common_proto_rawDesc), len(file_lmf_common_proto_rawDesc)))
	})
	return file_lmf_common_proto_rawDescData
}

var file_lmf_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_lmf_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lmf_common_proto_goTypes = []any{
	(PositioningMethod)(0),           // 0: lmf.v1.PositioningMethod
	(ResponseTimeClass)(0),           // 1: lmf.v1.ResponseTimeClass
	(AccuracyFulfilmentIndicator)(0), // 2: lmf.v1.AccuracyFulfilmentIndicator
	(SessionStatus)(0),               // 3: lmf.v1.SessionStatus
	(LcsClientType)(0),               // 4: lmf.v1.LcsClientType
	(*PlmnId)(nil),                   // 5: lmf.v1.PlmnId
	(*LcsQoS)(nil),                   // 6: lmf.v1.LcsQoS
	(*LocationEstimate)(nil),         // 7: lmf.v1.LocationEstimate
	(*VelocityEstimate)(nil),         // 8: lmf.v1.VelocityEstimate
	(*PositionEstimate)(nil),         // 9: lmf.v1.PositionEstimate
	(*UeCapabilities)(nil),           // 10: lmf.v1.UeCapabilities
	(*PrsConfiguration)(nil),         // 11: lmf.v1.PrsConfiguration
	(*CellGeometry)(nil),             // 12: lmf.v1.CellGeometry
}
var file_lmf_common_proto_depIdxs = []int32{
	1, // 0: lmf.v1.LcsQoS.response_time:type_name -> lmf.v1.ResponseTimeClass
	0, // 1: lmf.v1.PositionEstimate.method:type_name -> lmf.v1.PositioningMethod
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lmf_common_proto_init() }
func file_lmf_common_proto_init() {
	if File_lmf_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lmf_common_proto_rawDesc), len(file_lmf_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lmf_common_proto_goTypes,
		DependencyIndexes: file_lmf_common_proto_depIdxs,
		EnumInfos:         file_lmf_common_proto_enumTypes,
		MessageInfos:      file_lmf_common_proto_msgTypes,
	}.Build()
	File_lmf_common_proto = out.File
	file_lmf_common_proto_goTypes = nil
	file_lmf_common_proto_depIdxs = nil
}
