// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: lmf_protocol.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProtocolHandlerService_SendLpp_FullMethodName           = "/lmf.v1.ProtocolHandlerService/SendLpp"
	ProtocolHandlerService_SendNrppa_FullMethodName         = "/lmf.v1.ProtocolHandlerService/SendNrppa"
	ProtocolHandlerService_GetUeCapabilities_FullMethodName = "/lmf.v1.ProtocolHandlerService/GetUeCapabilities"
)

// ProtocolHandlerServiceClient is the client API for ProtocolHandlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProtocolHandlerService manages LPP and NRPPa protocol exchanges
type ProtocolHandlerServiceClient interface {
	SendLpp(ctx context.Context, in *SendLppRequest, opts ...grpc.CallOption) (*SendLppResponse, error)
	SendNrppa(ctx context.Context, in *SendNrppaRequest, opts ...grpc.CallOption) (*SendNrppaResponse, error)
	GetUeCapabilities(ctx context.Context, in *GetUeCapabilitiesRequest, opts ...grpc.CallOption) (*GetUeCapabilitiesResponse, error)
}

type protocolHandlerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProtocolHandlerServiceClient(cc grpc.ClientConnInterface) ProtocolHandlerServiceClient {
	return &protocolHandlerServiceClient{cc}
}

func (c *protocolHandlerServiceClient) SendLpp(ctx context.Context, in *SendLppRequest, opts ...grpc.CallOption) (*SendLppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendLppResponse)
	err := c.cc.Invoke(ctx, ProtocolHandlerService_SendLpp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolHandlerServiceClient) SendNrppa(ctx context.Context, in *SendNrppaRequest, opts ...grpc.CallOption) (*SendNrppaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNrppaResponse)
	err := c.cc.Invoke(ctx, ProtocolHandlerService_SendNrppa_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolHandlerServiceClient) GetUeCapabilities(ctx context.Context, in *GetUeCapabilitiesRequest, opts ...grpc.CallOption) (*GetUeCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUeCapabilitiesResponse)
	err := c.cc.Invoke(ctx, ProtocolHandlerService_GetUeCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtocolHandlerServiceServer is the server API for ProtocolHandlerService service.
// All implementations must embed UnimplementedProtocolHandlerServiceServer
// for forward compatibility.
//
// ProtocolHandlerService manages LPP and NRPPa protocol exchanges
type ProtocolHandlerServiceServer interface {
	SendLpp(context.Context, *SendLppRequest) (*SendLppResponse, error)
	SendNrppa(context.Context, *SendNrppaRequest) (*SendNrppaResponse, error)
	GetUeCapabilities(context.Context, *GetUeCapabilitiesRequest) (*GetUeCapabilitiesResponse, error)
	mustEmbedUnimplementedProtocolHandlerServiceServer()
}

// UnimplementedProtocolHandlerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtocolHandlerServiceServer struct{}

func (UnimplementedProtocolHandlerServiceServer) SendLpp(context.Context, *SendLppRequest) (*SendLppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendLpp not implemented")
}
func (UnimplementedProtocolHandlerServiceServer) SendNrppa(context.Context, *SendNrppaRequest) (*SendNrppaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNrppa not implemented")
}
func (UnimplementedProtocolHandlerServiceServer) GetUeCapabilities(context.Context, *GetUeCapabilitiesRequest) (*GetUeCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUeCapabilities not implemented")
}
func (UnimplementedProtocolHandlerServiceServer) mustEmbedUnimplementedProtocolHandlerServiceServer() {
}
func (UnimplementedProtocolHandlerServiceServer) testEmbeddedByValue() {}

// UnsafeProtocolHandlerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtocolHandlerServiceServer will
// result in compilation errors.
type UnsafeProtocolHandlerServiceServer interface {
	mustEmbedUnimplementedProtocolHandlerServiceServer()
}

func RegisterProtocolHandlerServiceServer(s grpc.ServiceRegistrar, srv ProtocolHandlerServiceServer) {
	// If the following call panics, it indicates UnimplementedProtocolHandlerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtocolHandlerService_ServiceDesc, srv)
}

func _ProtocolHandlerService_SendLpp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolHandlerServiceServer).SendLpp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolHandlerService_SendLpp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolHandlerServiceServer).SendLpp(ctx, req.(*SendLppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolHandlerService_SendNrppa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNrppaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolHandlerServiceServer).SendNrppa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolHandlerService_SendNrppa_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolHandlerServiceServer).SendNrppa(ctx, req.(*SendNrppaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolHandlerService_GetUeCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUeCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolHandlerServiceServer).GetUeCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolHandlerService_GetUeCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolHandlerServiceServer).GetUeCapabilities(ctx, req.(*GetUeCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtocolHandlerService_ServiceDesc is the grpc.ServiceDesc for ProtocolHandlerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtocolHandlerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.ProtocolHandlerService",
	HandlerType: (*ProtocolHandlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLpp",
			Handler:    _ProtocolHandlerService_SendLpp_Handler,
		},
		{
			MethodName: "SendNrppa",
			Handler:    _ProtocolHandlerService_SendNrppa_Handler,
		},
		{
			MethodName: "GetUeCapabilities",
			Handler:    _ProtocolHandlerService_GetUeCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_protocol.proto",
}
