// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: lmf_events.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventManagerService_Subscribe_FullMethodName             = "/lmf.v1.EventManagerService/Subscribe"
	EventManagerService_Unsubscribe_FullMethodName           = "/lmf.v1.EventManagerService/Unsubscribe"
	EventManagerService_ProcessLocationUpdate_FullMethodName = "/lmf.v1.EventManagerService/ProcessLocationUpdate"
)

// EventManagerServiceClient is the client API for EventManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definitions
type EventManagerServiceClient interface {
	Subscribe(ctx context.Context, in *EventSubscriptionRequest, opts ...grpc.CallOption) (*EventSubscriptionResponse, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
	ProcessLocationUpdate(ctx context.Context, in *LocationUpdateMsg, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
}

type eventManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventManagerServiceClient(cc grpc.ClientConnInterface) EventManagerServiceClient {
	return &eventManagerServiceClient{cc}
}

func (c *eventManagerServiceClient) Subscribe(ctx context.Context, in *EventSubscriptionRequest, opts ...grpc.CallOption) (*EventSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventSubscriptionResponse)
	err := c.cc.Invoke(ctx, EventManagerService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventManagerServiceClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, EventManagerService_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventManagerServiceClient) ProcessLocationUpdate(ctx context.Context, in *LocationUpdateMsg, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, EventManagerService_ProcessLocationUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventManagerServiceServer is the server API for EventManagerService service.
// All implementations must embed UnimplementedEventManagerServiceServer
// for forward compatibility.
//
// Service definitions
type EventManagerServiceServer interface {
	Subscribe(context.Context, *EventSubscriptionRequest) (*EventSubscriptionResponse, error)
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
	ProcessLocationUpdate(context.Context, *LocationUpdateMsg) (*UnsubscribeResponse, error)
	mustEmbedUnimplementedEventManagerServiceServer()
}

// UnimplementedEventManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventManagerServiceServer struct{}

func (UnimplementedEventManagerServiceServer) Subscribe(context.Context, *EventSubscriptionRequest) (*EventSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedEventManagerServiceServer) Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedEventManagerServiceServer) ProcessLocationUpdate(context.Context, *LocationUpdateMsg) (*UnsubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessLocationUpdate not implemented")
}
func (UnimplementedEventManagerServiceServer) mustEmbedUnimplementedEventManagerServiceServer() {}
func (UnimplementedEventManagerServiceServer) testEmbeddedByValue()                             {}

// UnsafeEventManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventManagerServiceServer will
// result in compilation errors.
type UnsafeEventManagerServiceServer interface {
	mustEmbedUnimplementedEventManagerServiceServer()
}

func RegisterEventManagerServiceServer(s grpc.ServiceRegistrar, srv EventManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedEventManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventManagerService_ServiceDesc, srv)
}

func _EventManagerService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventManagerServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventManagerService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventManagerServiceServer).Subscribe(ctx, req.(*EventSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventManagerService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventManagerServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventManagerService_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventManagerServiceServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventManagerService_ProcessLocationUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationUpdateMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventManagerServiceServer).ProcessLocationUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventManagerService_ProcessLocationUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventManagerServiceServer).ProcessLocationUpdate(ctx, req.(*LocationUpdateMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// EventManagerService_ServiceDesc is the grpc.ServiceDesc for EventManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.EventManagerService",
	HandlerType: (*EventManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _EventManagerService_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _EventManagerService_Unsubscribe_Handler,
		},
		{
			MethodName: "ProcessLocationUpdate",
			Handler:    _EventManagerService_ProcessLocationUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_events.proto",
}

const (
	PrivacyAuthService_CheckPrivacy_FullMethodName  = "/lmf.v1.PrivacyAuthService/CheckPrivacy"
	PrivacyAuthService_ValidateToken_FullMethodName = "/lmf.v1.PrivacyAuthService/ValidateToken"
)

// PrivacyAuthServiceClient is the client API for PrivacyAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrivacyAuthServiceClient interface {
	CheckPrivacy(ctx context.Context, in *PrivacyCheckRequest, opts ...grpc.CallOption) (*PrivacyCheckResponse, error)
	ValidateToken(ctx context.Context, in *TokenValidateRequest, opts ...grpc.CallOption) (*TokenValidateResponse, error)
}

type privacyAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivacyAuthServiceClient(cc grpc.ClientConnInterface) PrivacyAuthServiceClient {
	return &privacyAuthServiceClient{cc}
}

func (c *privacyAuthServiceClient) CheckPrivacy(ctx context.Context, in *PrivacyCheckRequest, opts ...grpc.CallOption) (*PrivacyCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrivacyCheckResponse)
	err := c.cc.Invoke(ctx, PrivacyAuthService_CheckPrivacy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privacyAuthServiceClient) ValidateToken(ctx context.Context, in *TokenValidateRequest, opts ...grpc.CallOption) (*TokenValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenValidateResponse)
	err := c.cc.Invoke(ctx, PrivacyAuthService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivacyAuthServiceServer is the server API for PrivacyAuthService service.
// All implementations must embed UnimplementedPrivacyAuthServiceServer
// for forward compatibility.
type PrivacyAuthServiceServer interface {
	CheckPrivacy(context.Context, *PrivacyCheckRequest) (*PrivacyCheckResponse, error)
	ValidateToken(context.Context, *TokenValidateRequest) (*TokenValidateResponse, error)
	mustEmbedUnimplementedPrivacyAuthServiceServer()
}

// UnimplementedPrivacyAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivacyAuthServiceServer struct{}

func (UnimplementedPrivacyAuthServiceServer) CheckPrivacy(context.Context, *PrivacyCheckRequest) (*PrivacyCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPrivacy not implemented")
}
func (UnimplementedPrivacyAuthServiceServer) ValidateToken(context.Context, *TokenValidateRequest) (*TokenValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedPrivacyAuthServiceServer) mustEmbedUnimplementedPrivacyAuthServiceServer() {}
func (UnimplementedPrivacyAuthServiceServer) testEmbeddedByValue()                            {}

// UnsafePrivacyAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivacyAuthServiceServer will
// result in compilation errors.
type UnsafePrivacyAuthServiceServer interface {
	mustEmbedUnimplementedPrivacyAuthServiceServer()
}

func RegisterPrivacyAuthServiceServer(s grpc.ServiceRegistrar, srv PrivacyAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedPrivacyAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrivacyAuthService_ServiceDesc, srv)
}

func _PrivacyAuthService_CheckPrivacy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivacyCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyAuthServiceServer).CheckPrivacy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyAuthService_CheckPrivacy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyAuthServiceServer).CheckPrivacy(ctx, req.(*PrivacyCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivacyAuthService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyAuthServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyAuthService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyAuthServiceServer).ValidateToken(ctx, req.(*TokenValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrivacyAuthService_ServiceDesc is the grpc.ServiceDesc for PrivacyAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrivacyAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.PrivacyAuthService",
	HandlerType: (*PrivacyAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPrivacy",
			Handler:    _PrivacyAuthService_CheckPrivacy_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _PrivacyAuthService_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_events.proto",
}
