// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: lmf_location.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationRequestService_DetermineLocation_FullMethodName = "/lmf.v1.LocationRequestService/DetermineLocation"
	LocationRequestService_CancelLocation_FullMethodName    = "/lmf.v1.LocationRequestService/CancelLocation"
	LocationRequestService_GetSessionStatus_FullMethodName  = "/lmf.v1.LocationRequestService/GetSessionStatus"
)

// LocationRequestServiceClient is the client API for LocationRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocationRequestService handles location determination requests
type LocationRequestServiceClient interface {
	DetermineLocation(ctx context.Context, in *LocationRequestMsg, opts ...grpc.CallOption) (*LocationResponseMsg, error)
	CancelLocation(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	GetSessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error)
}

type locationRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationRequestServiceClient(cc grpc.ClientConnInterface) LocationRequestServiceClient {
	return &locationRequestServiceClient{cc}
}

func (c *locationRequestServiceClient) DetermineLocation(ctx context.Context, in *LocationRequestMsg, opts ...grpc.CallOption) (*LocationResponseMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocationResponseMsg)
	err := c.cc.Invoke(ctx, LocationRequestService_DetermineLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationRequestServiceClient) CancelLocation(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, LocationRequestService_CancelLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationRequestServiceClient) GetSessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStatusResponse)
	err := c.cc.Invoke(ctx, LocationRequestService_GetSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationRequestServiceServer is the server API for LocationRequestService service.
// All implementations must embed UnimplementedLocationRequestServiceServer
// for forward compatibility.
//
// LocationRequestService handles location determination requests
type LocationRequestServiceServer interface {
	DetermineLocation(context.Context, *LocationRequestMsg) (*LocationResponseMsg, error)
	CancelLocation(context.Context, *CancelRequest) (*CancelResponse, error)
	GetSessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error)
	mustEmbedUnimplementedLocationRequestServiceServer()
}

// UnimplementedLocationRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationRequestServiceServer struct{}

func (UnimplementedLocationRequestServiceServer) DetermineLocation(context.Context, *LocationRequestMsg) (*LocationResponseMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method DetermineLocation not implemented")
}
func (UnimplementedLocationRequestServiceServer) CancelLocation(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelLocation not implemented")
}
func (UnimplementedLocationRequestServiceServer) GetSessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionStatus not implemented")
}
func (UnimplementedLocationRequestServiceServer) mustEmbedUnimplementedLocationRequestServiceServer() {
}
func (UnimplementedLocationRequestServiceServer) testEmbeddedByValue() {}

// UnsafeLocationRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationRequestServiceServer will
// result in compilation errors.
type UnsafeLocationRequestServiceServer interface {
	mustEmbedUnimplementedLocationRequestServiceServer()
}

func RegisterLocationRequestServiceServer(s grpc.ServiceRegistrar, srv LocationRequestServiceServer) {
	// If the following call panics, it indicates UnimplementedLocationRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationRequestService_ServiceDesc, srv)
}

func _LocationRequestService_DetermineLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationRequestServiceServer).DetermineLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationRequestService_DetermineLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationRequestServiceServer).DetermineLocation(ctx, req.(*LocationRequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationRequestService_CancelLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationRequestServiceServer).CancelLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationRequestService_CancelLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationRequestServiceServer).CancelLocation(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationRequestService_GetSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationRequestServiceServer).GetSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationRequestService_GetSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationRequestServiceServer).GetSessionStatus(ctx, req.(*SessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationRequestService_ServiceDesc is the grpc.ServiceDesc for LocationRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.LocationRequestService",
	HandlerType: (*LocationRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetermineLocation",
			Handler:    _LocationRequestService_DetermineLocation_Handler,
		},
		{
			MethodName: "CancelLocation",
			Handler:    _LocationRequestService_CancelLocation_Handler,
		},
		{
			MethodName: "GetSessionStatus",
			Handler:    _LocationRequestService_GetSessionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_location.proto",
}

const (
	SessionManagerService_CreateSession_FullMethodName       = "/lmf.v1.SessionManagerService/CreateSession"
	SessionManagerService_GetSession_FullMethodName          = "/lmf.v1.SessionManagerService/GetSession"
	SessionManagerService_UpdateSessionStatus_FullMethodName = "/lmf.v1.SessionManagerService/UpdateSessionStatus"
	SessionManagerService_DeleteSession_FullMethodName       = "/lmf.v1.SessionManagerService/DeleteSession"
)

// SessionManagerServiceClient is the client API for SessionManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionManagerService handles LCS session lifecycle
type SessionManagerServiceClient interface {
	CreateSession(ctx context.Context, in *SessionCreateRequest, opts ...grpc.CallOption) (*SessionCreateResponse, error)
	GetSession(ctx context.Context, in *SessionGetRequest, opts ...grpc.CallOption) (*SessionGetResponse, error)
	UpdateSessionStatus(ctx context.Context, in *SessionUpdateRequest, opts ...grpc.CallOption) (*SessionUpdateResponse, error)
	DeleteSession(ctx context.Context, in *SessionDeleteRequest, opts ...grpc.CallOption) (*SessionDeleteResponse, error)
}

type sessionManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionManagerServiceClient(cc grpc.ClientConnInterface) SessionManagerServiceClient {
	return &sessionManagerServiceClient{cc}
}

func (c *sessionManagerServiceClient) CreateSession(ctx context.Context, in *SessionCreateRequest, opts ...grpc.CallOption) (*SessionCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionCreateResponse)
	err := c.cc.Invoke(ctx, SessionManagerService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerServiceClient) GetSession(ctx context.Context, in *SessionGetRequest, opts ...grpc.CallOption) (*SessionGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionGetResponse)
	err := c.cc.Invoke(ctx, SessionManagerService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerServiceClient) UpdateSessionStatus(ctx context.Context, in *SessionUpdateRequest, opts ...grpc.CallOption) (*SessionUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionUpdateResponse)
	err := c.cc.Invoke(ctx, SessionManagerService_UpdateSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerServiceClient) DeleteSession(ctx context.Context, in *SessionDeleteRequest, opts ...grpc.CallOption) (*SessionDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionDeleteResponse)
	err := c.cc.Invoke(ctx, SessionManagerService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionManagerServiceServer is the server API for SessionManagerService service.
// All implementations must embed UnimplementedSessionManagerServiceServer
// for forward compatibility.
//
// SessionManagerService handles LCS session lifecycle
type SessionManagerServiceServer interface {
	CreateSession(context.Context, *SessionCreateRequest) (*SessionCreateResponse, error)
	GetSession(context.Context, *SessionGetRequest) (*SessionGetResponse, error)
	UpdateSessionStatus(context.Context, *SessionUpdateRequest) (*SessionUpdateResponse, error)
	DeleteSession(context.Context, *SessionDeleteRequest) (*SessionDeleteResponse, error)
	mustEmbedUnimplementedSessionManagerServiceServer()
}

// UnimplementedSessionManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionManagerServiceServer struct{}

func (UnimplementedSessionManagerServiceServer) CreateSession(context.Context, *SessionCreateRequest) (*SessionCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSessionManagerServiceServer) GetSession(context.Context, *SessionGetRequest) (*SessionGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSessionManagerServiceServer) UpdateSessionStatus(context.Context, *SessionUpdateRequest) (*SessionUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSessionStatus not implemented")
}
func (UnimplementedSessionManagerServiceServer) DeleteSession(context.Context, *SessionDeleteRequest) (*SessionDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedSessionManagerServiceServer) mustEmbedUnimplementedSessionManagerServiceServer() {}
func (UnimplementedSessionManagerServiceServer) testEmbeddedByValue()                               {}

// UnsafeSessionManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionManagerServiceServer will
// result in compilation errors.
type UnsafeSessionManagerServiceServer interface {
	mustEmbedUnimplementedSessionManagerServiceServer()
}

func RegisterSessionManagerServiceServer(s grpc.ServiceRegistrar, srv SessionManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionManagerService_ServiceDesc, srv)
}

func _SessionManagerService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManagerService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServiceServer).CreateSession(ctx, req.(*SessionCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManagerService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManagerService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServiceServer).GetSession(ctx, req.(*SessionGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManagerService_UpdateSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServiceServer).UpdateSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManagerService_UpdateSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServiceServer).UpdateSessionStatus(ctx, req.(*SessionUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManagerService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManagerService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServiceServer).DeleteSession(ctx, req.(*SessionDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionManagerService_ServiceDesc is the grpc.ServiceDesc for SessionManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.SessionManagerService",
	HandlerType: (*SessionManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _SessionManagerService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SessionManagerService_GetSession_Handler,
		},
		{
			MethodName: "UpdateSessionStatus",
			Handler:    _SessionManagerService_UpdateSessionStatus_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _SessionManagerService_DeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_location.proto",
}

const (
	MethodSelectorService_SelectMethod_FullMethodName = "/lmf.v1.MethodSelectorService/SelectMethod"
)

// MethodSelectorServiceClient is the client API for MethodSelectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MethodSelectorService selects optimal positioning method
type MethodSelectorServiceClient interface {
	SelectMethod(ctx context.Context, in *MethodSelectionRequest, opts ...grpc.CallOption) (*MethodSelectionResponse, error)
}

type methodSelectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMethodSelectorServiceClient(cc grpc.ClientConnInterface) MethodSelectorServiceClient {
	return &methodSelectorServiceClient{cc}
}

func (c *methodSelectorServiceClient) SelectMethod(ctx context.Context, in *MethodSelectionRequest, opts ...grpc.CallOption) (*MethodSelectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MethodSelectionResponse)
	err := c.cc.Invoke(ctx, MethodSelectorService_SelectMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MethodSelectorServiceServer is the server API for MethodSelectorService service.
// All implementations must embed UnimplementedMethodSelectorServiceServer
// for forward compatibility.
//
// MethodSelectorService selects optimal positioning method
type MethodSelectorServiceServer interface {
	SelectMethod(context.Context, *MethodSelectionRequest) (*MethodSelectionResponse, error)
	mustEmbedUnimplementedMethodSelectorServiceServer()
}

// UnimplementedMethodSelectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMethodSelectorServiceServer struct{}

func (UnimplementedMethodSelectorServiceServer) SelectMethod(context.Context, *MethodSelectionRequest) (*MethodSelectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectMethod not implemented")
}
func (UnimplementedMethodSelectorServiceServer) mustEmbedUnimplementedMethodSelectorServiceServer() {}
func (UnimplementedMethodSelectorServiceServer) testEmbeddedByValue()                               {}

// UnsafeMethodSelectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MethodSelectorServiceServer will
// result in compilation errors.
type UnsafeMethodSelectorServiceServer interface {
	mustEmbedUnimplementedMethodSelectorServiceServer()
}

func RegisterMethodSelectorServiceServer(s grpc.ServiceRegistrar, srv MethodSelectorServiceServer) {
	// If the following call panics, it indicates UnimplementedMethodSelectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MethodSelectorService_ServiceDesc, srv)
}

func _MethodSelectorService_SelectMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MethodSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MethodSelectorServiceServer).SelectMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MethodSelectorService_SelectMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MethodSelectorServiceServer).SelectMethod(ctx, req.(*MethodSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MethodSelectorService_ServiceDesc is the grpc.ServiceDesc for MethodSelectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MethodSelectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.MethodSelectorService",
	HandlerType: (*MethodSelectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectMethod",
			Handler:    _MethodSelectorService_SelectMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_location.proto",
}

const (
	QosManagerService_EvaluateQoS_FullMethodName = "/lmf.v1.QosManagerService/EvaluateQoS"
)

// QosManagerServiceClient is the client API for QosManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QosManagerService evaluates QoS fulfilment
type QosManagerServiceClient interface {
	EvaluateQoS(ctx context.Context, in *QosEvaluateRequest, opts ...grpc.CallOption) (*QosEvaluateResponse, error)
}

type qosManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQosManagerServiceClient(cc grpc.ClientConnInterface) QosManagerServiceClient {
	return &qosManagerServiceClient{cc}
}

func (c *qosManagerServiceClient) EvaluateQoS(ctx context.Context, in *QosEvaluateRequest, opts ...grpc.CallOption) (*QosEvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QosEvaluateResponse)
	err := c.cc.Invoke(ctx, QosManagerService_EvaluateQoS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QosManagerServiceServer is the server API for QosManagerService service.
// All implementations must embed UnimplementedQosManagerServiceServer
// for forward compatibility.
//
// QosManagerService evaluates QoS fulfilment
type QosManagerServiceServer interface {
	EvaluateQoS(context.Context, *QosEvaluateRequest) (*QosEvaluateResponse, error)
	mustEmbedUnimplementedQosManagerServiceServer()
}

// UnimplementedQosManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQosManagerServiceServer struct{}

func (UnimplementedQosManagerServiceServer) EvaluateQoS(context.Context, *QosEvaluateRequest) (*QosEvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateQoS not implemented")
}
func (UnimplementedQosManagerServiceServer) mustEmbedUnimplementedQosManagerServiceServer() {}
func (UnimplementedQosManagerServiceServer) testEmbeddedByValue()                           {}

// UnsafeQosManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QosManagerServiceServer will
// result in compilation errors.
type UnsafeQosManagerServiceServer interface {
	mustEmbedUnimplementedQosManagerServiceServer()
}

func RegisterQosManagerServiceServer(s grpc.ServiceRegistrar, srv QosManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedQosManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QosManagerService_ServiceDesc, srv)
}

func _QosManagerService_EvaluateQoS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QosEvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QosManagerServiceServer).EvaluateQoS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QosManagerService_EvaluateQoS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QosManagerServiceServer).EvaluateQoS(ctx, req.(*QosEvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QosManagerService_ServiceDesc is the grpc.ServiceDesc for QosManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QosManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmf.v1.QosManagerService",
	HandlerType: (*QosManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateQoS",
			Handler:    _QosManagerService_EvaluateQoS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lmf_location.proto",
}
