// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: lmf_positioning.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GNSS Assistance Data messages
type GnssAssistanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Constellations []string               `protobuf:"bytes,1,rep,name=constellations,proto3" json:"constellations,omitempty"`
	RequestedTypes []string               `protobuf:"bytes,2,rep,name=requested_types,json=requestedTypes,proto3" json:"requested_types,omitempty"` // GnssAssistanceDataType values
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GnssAssistanceRequest) Reset() {
	*x = GnssAssistanceRequest{}
	mi := &file_lmf_positioning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnssAssistanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnssAssistanceRequest) ProtoMessage() {}

func (x *GnssAssistanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnssAssistanceRequest.ProtoReflect.Descriptor instead.
func (*GnssAssistanceRequest) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{0}
}

func (x *GnssAssistanceRequest) GetConstellations() []string {
	if x != nil {
		return x.Constellations
	}
	return nil
}

func (x *GnssAssistanceRequest) GetRequestedTypes() []string {
	if x != nil {
		return x.RequestedTypes
	}
	return nil
}

type GnssEphemerisMsg struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Constellation    string                 `protobuf:"bytes,1,opt,name=constellation,proto3" json:"constellation,omitempty"`
	Svid             int32                  `protobuf:"varint,2,opt,name=svid,proto3" json:"svid,omitempty"`
	Toc              int64                  `protobuf:"varint,3,opt,name=toc,proto3" json:"toc,omitempty"`
	Toe              int64                  `protobuf:"varint,4,opt,name=toe,proto3" json:"toe,omitempty"`
	SqrtA            float64                `protobuf:"fixed64,5,opt,name=sqrt_a,json=sqrtA,proto3" json:"sqrt_a,omitempty"`
	Eccentricity     float64                `protobuf:"fixed64,6,opt,name=eccentricity,proto3" json:"eccentricity,omitempty"`
	Inclination      float64                `protobuf:"fixed64,7,opt,name=inclination,proto3" json:"inclination,omitempty"`
	Raan             float64                `protobuf:"fixed64,8,opt,name=raan,proto3" json:"raan,omitempty"`
	ArgPerigee       float64                `protobuf:"fixed64,9,opt,name=arg_perigee,json=argPerigee,proto3" json:"arg_perigee,omitempty"`
	MeanAnomaly      float64                `protobuf:"fixed64,10,opt,name=mean_anomaly,json=meanAnomaly,proto3" json:"mean_anomaly,omitempty"`
	Af0              float64                `protobuf:"fixed64,11,opt,name=af0,proto3" json:"af0,omitempty"`
	Af1              float64                `protobuf:"fixed64,12,opt,name=af1,proto3" json:"af1,omitempty"`
	Af2              float64                `protobuf:"fixed64,13,opt,name=af2,proto3" json:"af2,omitempty"`
	Ura              float64                `protobuf:"fixed64,14,opt,name=ura,proto3" json:"ura,omitempty"`
	ValidUntilUnixMs int64                  `protobuf:"varint,15,opt,name=valid_until_unix_ms,json=validUntilUnixMs,proto3" json:"valid_until_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GnssEphemerisMsg) Reset() {
	*x = GnssEphemerisMsg{}
	mi := &file_lmf_positioning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnssEphemerisMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnssEphemerisMsg) ProtoMessage() {}

func (x *GnssEphemerisMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnssEphemerisMsg.ProtoReflect.Descriptor instead.
func (*GnssEphemerisMsg) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{1}
}

func (x *GnssEphemerisMsg) GetConstellation() string {
	if x != nil {
		return x.Constellation
	}
	return ""
}

func (x *GnssEphemerisMsg) GetSvid() int32 {
	if x != nil {
		return x.Svid
	}
	return 0
}

func (x *GnssEphemerisMsg) GetToc() int64 {
	if x != nil {
		return x.Toc
	}
	return 0
}

func (x *GnssEphemerisMsg) GetToe() int64 {
	if x != nil {
		return x.Toe
	}
	return 0
}

func (x *GnssEphemerisMsg) GetSqrtA() float64 {
	if x != nil {
		return x.SqrtA
	}
	return 0
}

func (x *GnssEphemerisMsg) GetEccentricity() float64 {
	if x != nil {
		return x.Eccentricity
	}
	return 0
}

func (x *GnssEphemerisMsg) GetInclination() float64 {
	if x != nil {
		return x.Inclination
	}
	return 0
}

func (x *GnssEphemerisMsg) GetRaan() float64 {
	if x != nil {
		return x.Raan
	}
	return 0
}

func (x *GnssEphemerisMsg) GetArgPerigee() float64 {
	if x != nil {
		return x.ArgPerigee
	}
	return 0
}

func (x *GnssEphemerisMsg) GetMeanAnomaly() float64 {
	if x != nil {
		return x.MeanAnomaly
	}
	return 0
}

func (x *GnssEphemerisMsg) GetAf0() float64 {
	if x != nil {
		return x.Af0
	}
	return 0
}

func (x *GnssEphemerisMsg) GetAf1() float64 {
	if x != nil {
		return x.Af1
	}
	return 0
}

func (x *GnssEphemerisMsg) GetAf2() float64 {
	if x != nil {
		return x.Af2
	}
	return 0
}

func (x *GnssEphemerisMsg) GetUra() float64 {
	if x != nil {
		return x.Ura
	}
	return 0
}

func (x *GnssEphemerisMsg) GetValidUntilUnixMs() int64 {
	if x != nil {
		return x.ValidUntilUnixMs
	}
	return 0
}

type GnssAssistanceResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReferenceTimeUnixMs int64                  `protobuf:"varint,1,opt,name=reference_time_unix_ms,json=referenceTimeUnixMs,proto3" json:"reference_time_unix_ms,omitempty"`
	Ephemerides         []*GnssEphemerisMsg    `protobuf:"bytes,2,rep,name=ephemerides,proto3" json:"ephemerides,omitempty"`
	IonoAlpha           []float64              `protobuf:"fixed64,3,rep,packed,name=iono_alpha,json=ionoAlpha,proto3" json:"iono_alpha,omitempty"`
	IonoBeta            []float64              `protobuf:"fixed64,4,rep,packed,name=iono_beta,json=ionoBeta,proto3" json:"iono_beta,omitempty"`
	ValidUntilUnixMs    int64                  `protobuf:"varint,5,opt,name=valid_until_unix_ms,json=validUntilUnixMs,proto3" json:"valid_until_unix_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GnssAssistanceResponse) Reset() {
	*x = GnssAssistanceResponse{}
	mi := &file_lmf_positioning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnssAssistanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnssAssistanceResponse) ProtoMessage() {}

func (x *GnssAssistanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnssAssistanceResponse.ProtoReflect.Descriptor instead.
func (*GnssAssistanceResponse) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{2}
}

func (x *GnssAssistanceResponse) GetReferenceTimeUnixMs() int64 {
	if x != nil {
		return x.ReferenceTimeUnixMs
	}
	return 0
}

func (x *GnssAssistanceResponse) GetEphemerides() []*GnssEphemerisMsg {
	if x != nil {
		return x.Ephemerides
	}
	return nil
}

func (x *GnssAssistanceResponse) GetIonoAlpha() []float64 {
	if x != nil {
		return x.IonoAlpha
	}
	return nil
}

func (x *GnssAssistanceResponse) GetIonoBeta() []float64 {
	if x != nil {
		return x.IonoBeta
	}
	return nil
}

func (x *GnssAssistanceResponse) GetValidUntilUnixMs() int64 {
	if x != nil {
		return x.ValidUntilUnixMs
	}
	return 0
}

// GNSS positioning computation
type GnssSignalMeasurementMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svid          int32                  `protobuf:"varint,1,opt,name=svid,proto3" json:"svid,omitempty"`
	Constellation string                 `protobuf:"bytes,2,opt,name=constellation,proto3" json:"constellation,omitempty"`
	Cnr           float64                `protobuf:"fixed64,3,opt,name=cnr,proto3" json:"cnr,omitempty"`
	Pseudorange   float64                `protobuf:"fixed64,4,opt,name=pseudorange,proto3" json:"pseudorange,omitempty"`
	Doppler       float64                `protobuf:"fixed64,5,opt,name=doppler,proto3" json:"doppler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GnssSignalMeasurementMsg) Reset() {
	*x = GnssSignalMeasurementMsg{}
	mi := &file_lmf_positioning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnssSignalMeasurementMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnssSignalMeasurementMsg) ProtoMessage() {}

func (x *GnssSignalMeasurementMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnssSignalMeasurementMsg.ProtoReflect.Descriptor instead.
func (*GnssSignalMeasurementMsg) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{3}
}

func (x *GnssSignalMeasurementMsg) GetSvid() int32 {
	if x != nil {
		return x.Svid
	}
	return 0
}

func (x *GnssSignalMeasurementMsg) GetConstellation() string {
	if x != nil {
		return x.Constellation
	}
	return ""
}

func (x *GnssSignalMeasurementMsg) GetCnr() float64 {
	if x != nil {
		return x.Cnr
	}
	return 0
}

func (x *GnssSignalMeasurementMsg) GetPseudorange() float64 {
	if x != nil {
		return x.Pseudorange
	}
	return 0
}

func (x *GnssSignalMeasurementMsg) GetDoppler() float64 {
	if x != nil {
		return x.Doppler
	}
	return 0
}

type GnssComputeRequest struct {
	state                 protoimpl.MessageState      `protogen:"open.v1"`
	Signals               []*GnssSignalMeasurementMsg `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	Ephemerides           []*GnssEphemerisMsg         `protobuf:"bytes,2,rep,name=ephemerides,proto3" json:"ephemerides,omitempty"`
	MeasurementTimeUnixMs int64                       `protobuf:"varint,3,opt,name=measurement_time_unix_ms,json=measurementTimeUnixMs,proto3" json:"measurement_time_unix_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GnssComputeRequest) Reset() {
	*x = GnssComputeRequest{}
	mi := &file_lmf_positioning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnssComputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnssComputeRequest) ProtoMessage() {}

func (x *GnssComputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnssComputeRequest.ProtoReflect.Descriptor instead.
func (*GnssComputeRequest) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{4}
}

func (x *GnssComputeRequest) GetSignals() []*GnssSignalMeasurementMsg {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *GnssComputeRequest) GetEphemerides() []*GnssEphemerisMsg {
	if x != nil {
		return x.Ephemerides
	}
	return nil
}

func (x *GnssComputeRequest) GetMeasurementTimeUnixMs() int64 {
	if x != nil {
		return x.MeasurementTimeUnixMs
	}
	return 0
}

type GnssComputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estimate      *PositionEstimate      `protobuf:"bytes,1,opt,name=estimate,proto3" json:"estimate,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GnssComputeResponse) Reset() {
	*x = GnssComputeResponse{}
	mi := &file_lmf_positioning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnssComputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnssComputeResponse) ProtoMessage() {}

func (x *GnssComputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnssComputeResponse.ProtoReflect.Descriptor instead.
func (*GnssComputeResponse) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{5}
}

func (x *GnssComputeResponse) GetEstimate() *PositionEstimate {
	if x != nil {
		return x.Estimate
	}
	return nil
}

func (x *GnssComputeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DL-TDOA messages
type RstdMeasurementMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RefCellNci      string                 `protobuf:"bytes,1,opt,name=ref_cell_nci,json=refCellNci,proto3" json:"ref_cell_nci,omitempty"`
	NeighborCellNci string                 `protobuf:"bytes,2,opt,name=neighbor_cell_nci,json=neighborCellNci,proto3" json:"neighbor_cell_nci,omitempty"`
	Rstd            float64                `protobuf:"fixed64,3,opt,name=rstd,proto3" json:"rstd,omitempty"` // Ts units
	RstdUncertainty float64                `protobuf:"fixed64,4,opt,name=rstd_uncertainty,json=rstdUncertainty,proto3" json:"rstd_uncertainty,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RstdMeasurementMsg) Reset() {
	*x = RstdMeasurementMsg{}
	mi := &file_lmf_positioning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RstdMeasurementMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RstdMeasurementMsg) ProtoMessage() {}

func (x *RstdMeasurementMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RstdMeasurementMsg.ProtoReflect.Descriptor instead.
func (*RstdMeasurementMsg) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{6}
}

func (x *RstdMeasurementMsg) GetRefCellNci() string {
	if x != nil {
		return x.RefCellNci
	}
	return ""
}

func (x *RstdMeasurementMsg) GetNeighborCellNci() string {
	if x != nil {
		return x.NeighborCellNci
	}
	return ""
}

func (x *RstdMeasurementMsg) GetRstd() float64 {
	if x != nil {
		return x.Rstd
	}
	return 0
}

func (x *RstdMeasurementMsg) GetRstdUncertainty() float64 {
	if x != nil {
		return x.RstdUncertainty
	}
	return 0
}

type DlTdoaRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RefGnb                string                 `protobuf:"bytes,1,opt,name=ref_gnb,json=refGnb,proto3" json:"ref_gnb,omitempty"`
	Measurements          []*RstdMeasurementMsg  `protobuf:"bytes,2,rep,name=measurements,proto3" json:"measurements,omitempty"`
	CellGeometry          []*CellGeometry        `protobuf:"bytes,3,rep,name=cell_geometry,json=cellGeometry,proto3" json:"cell_geometry,omitempty"`
	MeasurementTimeUnixMs int64                  `protobuf:"varint,4,opt,name=measurement_time_unix_ms,json=measurementTimeUnixMs,proto3" json:"measurement_time_unix_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DlTdoaRequest) Reset() {
	*x = DlTdoaRequest{}
	mi := &file_lmf_positioning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlTdoaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlTdoaRequest) ProtoMessage() {}

func (x *DlTdoaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlTdoaRequest.ProtoReflect.Descriptor instead.
func (*DlTdoaRequest) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{7}
}

func (x *DlTdoaRequest) GetRefGnb() string {
	if x != nil {
		return x.RefGnb
	}
	return ""
}

func (x *DlTdoaRequest) GetMeasurements() []*RstdMeasurementMsg {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *DlTdoaRequest) GetCellGeometry() []*CellGeometry {
	if x != nil {
		return x.CellGeometry
	}
	return nil
}

func (x *DlTdoaRequest) GetMeasurementTimeUnixMs() int64 {
	if x != nil {
		return x.MeasurementTimeUnixMs
	}
	return 0
}

type DlTdoaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estimate      *PositionEstimate      `protobuf:"bytes,1,opt,name=estimate,proto3" json:"estimate,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlTdoaResponse) Reset() {
	*x = DlTdoaResponse{}
	mi := &file_lmf_positioning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlTdoaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlTdoaResponse) ProtoMessage() {}

func (x *DlTdoaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlTdoaResponse.ProtoReflect.Descriptor instead.
func (*DlTdoaResponse) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{8}
}

func (x *DlTdoaResponse) GetEstimate() *PositionEstimate {
	if x != nil {
		return x.Estimate
	}
	return nil
}

func (x *DlTdoaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// E-CID messages
type RsrpEntryMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellNci       string                 `protobuf:"bytes,1,opt,name=cell_nci,json=cellNci,proto3" json:"cell_nci,omitempty"`
	Rsrp          float64                `protobuf:"fixed64,2,opt,name=rsrp,proto3" json:"rsrp,omitempty"`
	Rsrq          float64                `protobuf:"fixed64,3,opt,name=rsrq,proto3" json:"rsrq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RsrpEntryMsg) Reset() {
	*x = RsrpEntryMsg{}
	mi := &file_lmf_positioning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RsrpEntryMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsrpEntryMsg) ProtoMessage() {}

func (x *RsrpEntryMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsrpEntryMsg.ProtoReflect.Descriptor instead.
func (*RsrpEntryMsg) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{9}
}

func (x *RsrpEntryMsg) GetCellNci() string {
	if x != nil {
		return x.CellNci
	}
	return ""
}

func (x *RsrpEntryMsg) GetRsrp() float64 {
	if x != nil {
		return x.Rsrp
	}
	return 0
}

func (x *RsrpEntryMsg) GetRsrq() float64 {
	if x != nil {
		return x.Rsrq
	}
	return 0
}

type EcidRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServingCellNci       string                 `protobuf:"bytes,1,opt,name=serving_cell_nci,json=servingCellNci,proto3" json:"serving_cell_nci,omitempty"`
	TimingAdvance        int32                  `protobuf:"varint,2,opt,name=timing_advance,json=timingAdvance,proto3" json:"timing_advance,omitempty"`
	UeRxTxDiff           float64                `protobuf:"fixed64,3,opt,name=ue_rx_tx_diff,json=ueRxTxDiff,proto3" json:"ue_rx_tx_diff,omitempty"`
	GnbRxTxDiff          float64                `protobuf:"fixed64,4,opt,name=gnb_rx_tx_diff,json=gnbRxTxDiff,proto3" json:"gnb_rx_tx_diff,omitempty"`
	RsrpMeasurements     []*RsrpEntryMsg        `protobuf:"bytes,5,rep,name=rsrp_measurements,json=rsrpMeasurements,proto3" json:"rsrp_measurements,omitempty"`
	ServingCellGeometry  *CellGeometry          `protobuf:"bytes,6,opt,name=serving_cell_geometry,json=servingCellGeometry,proto3" json:"serving_cell_geometry,omitempty"`
	NeighborCellGeometry []*CellGeometry        `protobuf:"bytes,7,rep,name=neighbor_cell_geometry,json=neighborCellGeometry,proto3" json:"neighbor_cell_geometry,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EcidRequest) Reset() {
	*x = EcidRequest{}
	mi := &file_lmf_positioning_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcidRequest) ProtoMessage() {}

func (x *EcidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcidRequest.ProtoReflect.Descriptor instead.
func (*EcidRequest) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{10}
}

func (x *EcidRequest) GetServingCellNci() string {
	if x != nil {
		return x.ServingCellNci
	}
	return ""
}

func (x *EcidRequest) GetTimingAdvance() int32 {
	if x != nil {
		return x.TimingAdvance
	}
	return 0
}

func (x *EcidRequest) GetUeRxTxDiff() float64 {
	if x != nil {
		return x.UeRxTxDiff
	}
	return 0
}

func (x *EcidRequest) GetGnbRxTxDiff() float64 {
	if x != nil {
		return x.GnbRxTxDiff
	}
	return 0
}

func (x *EcidRequest) GetRsrpMeasurements() []*RsrpEntryMsg {
	if x != nil {
		return x.RsrpMeasurements
	}
	return nil
}

func (x *EcidRequest) GetServingCellGeometry() *CellGeometry {
	if x != nil {
		return x.ServingCellGeometry
	}
	return nil
}

func (x *EcidRequest) GetNeighborCellGeometry() []*CellGeometry {
	if x != nil {
		return x.NeighborCellGeometry
	}
	return nil
}

type EcidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estimate      *PositionEstimate      `protobuf:"bytes,1,opt,name=estimate,proto3" json:"estimate,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcidResponse) Reset() {
	*x = EcidResponse{}
	mi := &file_lmf_positioning_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcidResponse) ProtoMessage() {}

func (x *EcidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcidResponse.ProtoReflect.Descriptor instead.
func (*EcidResponse) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{11}
}

func (x *EcidResponse) GetEstimate() *PositionEstimate {
	if x != nil {
		return x.Estimate
	}
	return nil
}

func (x *EcidResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Multi-RTT messages
type RttEntryMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellNci       string                 `protobuf:"bytes,1,opt,name=cell_nci,json=cellNci,proto3" json:"cell_nci,omitempty"`
	UeRxTx        float64                `protobuf:"fixed64,2,opt,name=ue_rx_tx,json=ueRxTx,proto3" json:"ue_rx_tx,omitempty"`
	GnbRxTx       float64                `protobuf:"fixed64,3,opt,name=gnb_rx_tx,json=gnbRxTx,proto3" json:"gnb_rx_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RttEntryMsg) Reset() {
	*x = RttEntryMsg{}
	mi := &file_lmf_positioning_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RttEntryMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RttEntryMsg) ProtoMessage() {}

func (x *RttEntryMsg) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RttEntryMsg.ProtoReflect.Descriptor instead.
func (*RttEntryMsg) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{12}
}

func (x *RttEntryMsg) GetCellNci() string {
	if x != nil {
		return x.CellNci
	}
	return ""
}

func (x *RttEntryMsg) GetUeRxTx() float64 {
	if x != nil {
		return x.UeRxTx
	}
	return 0
}

func (x *RttEntryMsg) GetGnbRxTx() float64 {
	if x != nil {
		return x.GnbRxTx
	}
	return 0
}

type MultiRttRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Entries               []*RttEntryMsg         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	CellGeometry          []*CellGeometry        `protobuf:"bytes,2,rep,name=cell_geometry,json=cellGeometry,proto3" json:"cell_geometry,omitempty"`
	MeasurementTimeUnixMs int64                  `protobuf:"varint,3,opt,name=measurement_time_unix_ms,json=measurementTimeUnixMs,proto3" json:"measurement_time_unix_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MultiRttRequest) Reset() {
	*x = MultiRttRequest{}
	mi := &file_lmf_positioning_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiRttRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRttRequest) ProtoMessage() {}

func (x *MultiRttRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRttRequest.ProtoReflect.Descriptor instead.
func (*MultiRttRequest) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{13}
}

func (x *MultiRttRequest) GetEntries() []*RttEntryMsg {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *MultiRttRequest) GetCellGeometry() []*CellGeometry {
	if x != nil {
		return x.CellGeometry
	}
	return nil
}

func (x *MultiRttRequest) GetMeasurementTimeUnixMs() int64 {
	if x != nil {
		return x.MeasurementTimeUnixMs
	}
	return 0
}

type MultiRttResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estimate      *PositionEstimate      `protobuf:"bytes,1,opt,name=estimate,proto3" json:"estimate,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiRttResponse) Reset() {
	*x = MultiRttResponse{}
	mi := &file_lmf_positioning_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiRttResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRttResponse) ProtoMessage() {}

func (x *MultiRttResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRttResponse.ProtoReflect.Descriptor instead.
func (*MultiRttResponse) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{14}
}

func (x *MultiRttResponse) GetEstimate() *PositionEstimate {
	if x != nil {
		return x.Estimate
	}
	return nil
}

func (x *MultiRttResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Fusion messages
type FusionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Estimates     []*PositionEstimate    `protobuf:"bytes,2,rep,name=estimates,proto3" json:"estimates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FusionRequest) Reset() {
	*x = FusionRequest{}
	mi := &file_lmf_positioning_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FusionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FusionRequest) ProtoMessage() {}

func (x *FusionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FusionRequest.ProtoReflect.Descriptor instead.
func (*FusionRequest) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{15}
}

func (x *FusionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FusionRequest) GetEstimates() []*PositionEstimate {
	if x != nil {
		return x.Estimates
	}
	return nil
}

type FusionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FusedEstimate *PositionEstimate      `protobuf:"bytes,1,opt,name=fused_estimate,json=fusedEstimate,proto3" json:"fused_estimate,omitempty"`
	QualityIndex  int32                  `protobuf:"varint,2,opt,name=quality_index,json=qualityIndex,proto3" json:"quality_index,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FusionResponse) Reset() {
	*x = FusionResponse{}
	mi := &file_lmf_positioning_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FusionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FusionResponse) ProtoMessage() {}

func (x *FusionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lmf_positioning_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FusionResponse.ProtoReflect.Descriptor instead.
func (*FusionResponse) Descriptor() ([]byte, []int) {
	return file_lmf_positioning_proto_rawDescGZIP(), []int{16}
}

func (x *FusionResponse) GetFusedEstimate() *PositionEstimate {
	if x != nil {
		return x.FusedEstimate
	}
	return nil
}

func (x *FusionResponse) GetQualityIndex() int32 {
	if x != nil {
		return x.QualityIndex
	}
	return 0
}

func (x *FusionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_lmf_positioning_proto protoreflect.FileDescriptor

const file_lmf_positioning_proto_rawDesc = "" +
	"\n" +
	"\x15lmf_positioning.proto\x12\x06lmf.v1\x1a\x10lmf_common.proto\"h\n" +
	"\x15GnssAssistanceRequest\x12&\n" +
	"\x0econstellations\x18\x01 \x03(\tR\x0econstellations\x12'\n" +
	"\x0frequested_types\x18\x02 \x03(\tR\x0erequestedTypes\"\x9c\x03\n" +
	"\x10GnssEphemerisMsg\x12$\n" +
	"\rconstellation\x18\x01 \x01(\tR\rconstellation\x12\x12\n" +
	"\x04svid\x18\x02 \x01(\x05R\x04svid\x12\x10\n" +
	"\x03toc\x18\x03 \x01(\x03R\x03toc\x12\x10\n" +
	"\x03toe\x18\x04 \x01(\x03R\x03toe\x12\x15\n" +
	"\x06sqrt_a\x18\x05 \x01(\x01R\x05sqrtA\x12\"\n" +
	"\feccentricity\x18\x06 \x01(\x01R\feccentricity\x12 \n" +
	"\vinclination\x18\a \x01(\x01R\vinclination\x12\x12\n" +
	"\x04raan\x18\b \x01(\x01R\x04raan\x12\x1f\n" +
	"\varg_perigee\x18\t \x01(\x01R\n" +
	"argPerigee\x12!\n" +
	"\fmean_anomaly\x18\n" +
	" \x01(\x01R\vmeanAnomaly\x12\x10\n" +
	"\x03af0\x18\v \x01(\x01R\x03af0\x12\x10\n" +
	"\x03af1\x18\f \x01(\x01R\x03af1\x12\x10\n" +
	"\x03af2\x18\r \x01(\x01R\x03af2\x12\x10\n" +
	"\x03ura\x18\x0e \x01(\x01R\x03ura\x12-\n" +
	"\x13valid_until_unix_ms\x18\x0f \x01(\x03R\x10validUntilUnixMs\"\xf4\x01\n" +
	"\x16GnssAssistanceResponse\x123\n" +
	"\x16reference_time_unix_ms\x18\x01 \x01(\x03R\x13referenceTimeUnixMs\x12:\n" +
	"\vephemerides\x18\x02 \x03(\v2\x18.lmf.v1.GnssEphemerisMsgR\vephemerides\x12\x1d\n" +
	"\n" +
	"iono_alpha\x18\x03 \x03(\x01R\tionoAlpha\x12\x1b\n" +
	"\tiono_beta\x18\x04 \x03(\x01R\bionoBeta\x12-\n" +
	"\x13valid_until_unix_ms\x18\x05 \x01(\x03R\x10validUntilUnixMs\"\xa2\x01\n" +
	"\x18GnssSignalMeasurementMsg\x12\x12\n" +
	"\x04svid\x18\x01 \x01(\x05R\x04svid\x12$\n" +
	"\rconstellation\x18\x02 \x01(\tR\rconstellation\x12\x10\n" +
	"\x03cnr\x18\x03 \x01(\x01R\x03cnr\x12 \n" +
	"\vpseudorange\x18\x04 \x01(\x01R\vpseudorange\x12\x18\n" +
	"\adoppler\x18\x05 \x01(\x01R\adoppler\"\xc5\x01\n" +
	"\x12GnssComputeRequest\x12:\n" +
	"\asignals\x18\x01 \x03(\v2 .lmf.v1.GnssSignalMeasurementMsgR\asignals\x12:\n" +
	"\vephemerides\x18\x02 \x03(\v2\x18.lmf.v1.GnssEphemerisMsgR\vephemerides\x127\n" +
	"\x18measurement_time_unix_ms\x18\x03 \x01(\x03R\x15measurementTimeUnixMs\"a\n" +
	"\x13GnssComputeResponse\x124\n" +
	"\bestimate\x18\x01 \x01(\v2\x18.lmf.v1.PositionEstimateR\bestimate\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa1\x01\n" +
	"\x12RstdMeasurementMsg\x12 \n" +
	"\fref_cell_nci\x18\x01 \x01(\tR\n" +
	"refCellNci\x12*\n" +
	"\x11neighbor_cell_nci\x18\x02 \x01(\tR\x0fneighborCellNci\x12\x12\n" +
	"\x04rstd\x18\x03 \x01(\x01R\x04rstd\x12)\n" +
	"\x10rstd_uncertainty\x18\x04 \x01(\x01R\x0frstdUncertainty\"\xdc\x01\n" +
	"\rDlTdoaRequest\x12\x17\n" +
	"\aref_gnb\x18\x01 \x01(\tR\x06refGnb\x12>\n" +
	"\fmeasurements\x18\x02 \x03(\v2\x1a.lmf.v1.RstdMeasurementMsgR\fmeasurements\x129\n" +
	"\rcell_geometry\x18\x03 \x03(\v2\x14.lmf.v1.CellGeometryR\fcellGeometry\x127\n" +
	"\x18measurement_time_unix_ms\x18\x04 \x01(\x03R\x15measurementTimeUnixMs\"\\\n" +
	"\x0eDlTdoaResponse\x124\n" +
	"\bestimate\x18\x01 \x01(\v2\x18.lmf.v1.PositionEstimateR\bestimate\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Q\n" +
	"\fRsrpEntryMsg\x12\x19\n" +
	"\bcell_nci\x18\x01 \x01(\tR\acellNci\x12\x12\n" +
	"\x04rsrp\x18\x02 \x01(\x01R\x04rsrp\x12\x12\n" +
	"\x04rsrq\x18\x03 \x01(\x01R\x04rsrq\"\xff\x02\n" +
	"\vEcidRequest\x12(\n" +
	"\x10serving_cell_nci\x18\x01 \x01(\tR\x0eservingCellNci\x12%\n" +
	"\x0etiming_advance\x18\x02 \x01(\x05R\rtimingAdvance\x12!\n" +
	"\rue_rx_tx_diff\x18\x03 \x01(\x01R\n" +
	"ueRxTxDiff\x12#\n" +
	"\x0egnb_rx_tx_diff\x18\x04 \x01(\x01R\vgnbRxTxDiff\x12A\n" +
	"\x11rsrp_measurements\x18\x05 \x03(\v2\x14.lmf.v1.RsrpEntryMsgR\x10rsrpMeasurements\x12H\n" +
	"\x15serving_cell_geometry\x18\x06 \x01(\v2\x14.lmf.v1.CellGeometryR\x13servingCellGeometry\x12J\n" +
	"\x16neighbor_cell_geometry\x18\a \x03(\v2\x14.lmf.v1.CellGeometryR\x14neighborCellGeometry\"Z\n" +
	"\fEcidResponse\x124\n" +
	"\bestimate\x18\x01 \x01(\v2\x18.lmf.v1.PositionEstimateR\bestimate\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"^\n" +
	"\vRttEntryMsg\x12\x19\n" +
	"\bcell_nci\x18\x01 \x01(\tR\acellNci\x12\x18\n" +
	"\bue_rx_tx\x18\x02 \x01(\x01R\x06ueRxTx\x12\x1a\n" +
	"\tgnb_rx_tx\x18\x03 \x01(\x01R\agnbRxTx\"\xb4\x01\n" +
	"\x0fMultiRttRequest\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.lmf.v1.RttEntryMsgR\aentries\x129\n" +
	"\rcell_geometry\x18\x02 \x03(\v2\x14.lmf.v1.CellGeometryR\fcellGeometry\x127\n" +
	"\x18measurement_time_unix_ms\x18\x03 \x01(\x03R\x15measurementTimeUnixMs\"^\n" +
	"\x10MultiRttResponse\x124\n" +
	"\bestimate\x18\x01 \x01(\v2\x18.lmf.v1.PositionEstimateR\bestimate\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"f\n" +
	"\rFusionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x126\n" +
	"\testimates\x18\x02 \x03(\v2\x18.lmf.v1.PositionEstimateR\testimates\"\x8c\x01\n" +
	"\x0eFusionResponse\x12?\n" +
	"\x0efused_estimate\x18\x01 \x01(\v2\x18.lmf.v1.PositionEstimateR\rfusedEstimate\x12#\n" +
	"\rquality_index\x18\x02 \x01(\x05R\fqualityIndex\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xb3\x01\n" +
	"\x11GnssEngineService\x12R\n" +
	"\x11GetAssistanceData\x12\x1d.lmf.v1.GnssAssistanceRequest\x1a\x1e.lmf.v1.GnssAssistanceResponse\x12J\n" +
	"\x0fComputePosition\x12\x1a.lmf.v1.GnssComputeRequest\x1a\x1b.lmf.v1.GnssComputeResponse2U\n" +
	"\x11TdoaEngineService\x12@\n" +
	"\x0fComputePosition\x12\x15.lmf.v1.DlTdoaRequest\x1a\x16.lmf.v1.DlTdoaResponse2Q\n" +
	"\x11EcidEngineService\x12<\n" +
	"\x0fComputePosition\x12\x13.lmf.v1.EcidRequest\x1a\x14.lmf.v1.EcidResponse2X\n" +
	"\x10RttEngineService\x12D\n" +
	"\x0fComputePosition\x12\x17.lmf.v1.MultiRttRequest\x1a\x18.lmf.v1.MultiRttResponse2U\n" +
	"\x13FusionEngineService\x12>\n" +
	"\rFusePositions\x12\x15.lmf.v1.FusionRequest\x1a\x16.lmf.v1.FusionResponseB Z\x1egithub.com/5g-lmf/common/pb;pbb\x06proto3"

var (
	file_lmf_positioning_proto_rawDescOnce sync.Once
	file_lmf_positioning_proto_rawDescData []byte
)

func file_lmf_positioning_proto_rawDescGZIP() []byte {
	file_lmf_positioning_proto_rawDescOnce.Do(func() {
		file_lmf_positioning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lmf_positioning_proto_rawDesc), len(file_lmf_positioning_proto_rawDesc)))
	})
	return file_lmf_positioning_proto_rawDescData
}

var file_lmf_positioning_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_lmf_positioning_proto_goTypes = []any{
	(*GnssAssistanceRequest)(nil),    // 0: lmf.v1.GnssAssistanceRequest
	(*GnssEphemerisMsg)(nil),         // 1: lmf.v1.GnssEphemerisMsg
	(*GnssAssistanceResponse)(nil),   // 2: lmf.v1.GnssAssistanceResponse
	(*GnssSignalMeasurementMsg)(nil), // 3: lmf.v1.GnssSignalMeasurementMsg
	(*GnssComputeRequest)(nil),       // 4: lmf.v1.GnssComputeRequest
	(*GnssComputeResponse)(nil),      // 5: lmf.v1.GnssComputeResponse
	(*RstdMeasurementMsg)(nil),       // 6: lmf.v1.RstdMeasurementMsg
	(*DlTdoaRequest)(nil),            // 7: lmf.v1.DlTdoaRequest
	(*DlTdoaResponse)(nil),           // 8: lmf.v1.DlTdoaResponse
	(*RsrpEntryMsg)(nil),             // 9: lmf.v1.RsrpEntryMsg
	(*EcidRequest)(nil),              // 10: lmf.v1.EcidRequest
	(*EcidResponse)(nil),             // 11: lmf.v1.EcidResponse
	(*RttEntryMsg)(nil),              // 12: lmf.v1.RttEntryMsg
	(*MultiRttRequest)(nil),          // 13: lmf.v1.MultiRttRequest
	(*MultiRttResponse)(nil),         // 14: lmf.v1.MultiRttResponse
	(*FusionRequest)(nil),            // 15: lmf.v1.FusionRequest
	(*FusionResponse)(nil),           // 16: lmf.v1.FusionResponse
	(*PositionEstimate)(nil),         // 17: lmf.v1.PositionEstimate
	(*CellGeometry)(nil),             // 18: lmf.v1.CellGeometry
}
var file_lmf_positioning_proto_depIdxs = []int32{
	1,  // 0: lmf.v1.GnssAssistanceResponse.ephemerides:type_name -> lmf.v1.GnssEphemerisMsg
	3,  // 1: lmf.v1.GnssComputeRequest.signals:type_name -> lmf.v1.GnssSignalMeasurementMsg
	1,  // 2: lmf.v1.GnssComputeRequest.ephemerides:type_name -> lmf.v1.GnssEphemerisMsg
	17, // 3: lmf.v1.GnssComputeResponse.estimate:type_name -> lmf.v1.PositionEstimate
	6,  // 4: lmf.v1.DlTdoaRequest.measurements:type_name -> lmf.v1.RstdMeasurementMsg
	18, // 5: lmf.v1.DlTdoaRequest.cell_geometry:type_name -> lmf.v1.CellGeometry
	17, // 6: lmf.v1.DlTdoaResponse.estimate:type_name -> lmf.v1.PositionEstimate
	9,  // 7: lmf.v1.EcidRequest.rsrp_measurements:type_name -> lmf.v1.RsrpEntryMsg
	18, // 8: lmf.v1.EcidRequest.serving_cell_geometry:type_name -> lmf.v1.CellGeometry
	18, // 9: lmf.v1.EcidRequest.neighbor_cell_geometry:type_name -> lmf.v1.CellGeometry
	17, // 10: lmf.v1.EcidResponse.estimate:type_name -> lmf.v1.PositionEstimate
	12, // 11: lmf.v1.MultiRttRequest.entries:type_name -> lmf.v1.RttEntryMsg
	18, // 12: lmf.v1.MultiRttRequest.cell_geometry:type_name -> lmf.v1.CellGeometry
	17, // 13: lmf.v1.MultiRttResponse.estimate:type_name -> lmf.v1.PositionEstimate
	17, // 14: lmf.v1.FusionRequest.estimates:type_name -> lmf.v1.PositionEstimate
	17, // 15: lmf.v1.FusionResponse.fused_estimate:type_name -> lmf.v1.PositionEstimate
	0,  // 16: lmf.v1.GnssEngineService.GetAssistanceData:input_type -> lmf.v1.GnssAssistanceRequest
	4,  // 17: lmf.v1.GnssEngineService.ComputePosition:input_type -> lmf.v1.GnssComputeRequest
	7,  // 18: lmf.v1.TdoaEngineService.ComputePosition:input_type -> lmf.v1.DlTdoaRequest
	10, // 19: lmf.v1.EcidEngineService.ComputePosition:input_type -> lmf.v1.EcidRequest
	13, // 20: lmf.v1.RttEngineService.ComputePosition:input_type -> lmf.v1.MultiRttRequest
	15, // 21: lmf.v1.FusionEngineService.FusePositions:input_type -> lmf.v1.FusionRequest
	2,  // 22: lmf.v1.GnssEngineService.GetAssistanceData:output_type -> lmf.v1.GnssAssistanceResponse
	5,  // 23: lmf.v1.GnssEngineService.ComputePosition:output_type -> lmf.v1.GnssComputeResponse
	8,  // 24: lmf.v1.TdoaEngineService.ComputePosition:output_type -> lmf.v1.DlTdoaResponse
	11, // 25: lmf.v1.EcidEngineService.ComputePosition:output_type -> lmf.v1.EcidResponse
	14, // 26: lmf.v1.RttEngineService.ComputePosition:output_type -> lmf.v1.MultiRttResponse
	16, // 27: lmf.v1.FusionEngineService.FusePositions:output_type -> lmf.v1.FusionResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_lmf_positioning_proto_init() }
func file_lmf_positioning_proto_init() {
	if File_lmf_positioning_proto != nil {
		return
	}
	file_lmf_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lmf_positioning_proto_rawDesc), len(file_lmf_positioning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_lmf_positioning_proto_goTypes,
		DependencyIndexes: file_lmf_positioning_proto_depIdxs,
		MessageInfos:      file_lmf_positioning_proto_msgTypes,
	}.Build()
	File_lmf_positioning_proto = out.File
	file_lmf_positioning_proto_goTypes = nil
	file_lmf_positioning_proto_depIdxs = nil
}
