// Package server implements the GnssEngineService gRPC server.
package server

import (
	"context"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/5g-lmf/gnss-engine/internal/assistance"
	"github.com/5g-lmf/gnss-engine/internal/positioning"
)

// Prometheus metrics.
var (
	methodAttempts = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: "gnss_engine",
		Name:      "method_attempts_total",
		Help:      "Total gRPC method invocations by method and status.",
	}, []string{"method", "status"})

	methodLatency = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: "gnss_engine",
		Name:      "method_latency_seconds",
		Help:      "gRPC method latency in seconds.",
		Buckets:   prometheus.DefBuckets,
	}, []string{"method"})

	accuracyAchieved = promauto.NewHistogram(prometheus.HistogramOpts{
		Namespace: "gnss_engine",
		Name:      "accuracy_achieved_meters",
		Help:      "Achieved horizontal accuracy per fix in metres.",
		Buckets:   []float64{1, 2, 5, 10, 20, 50, 100, 200, 500},
	})

	satellitesUsed = promauto.NewHistogram(prometheus.HistogramOpts{
		Namespace: "gnss_engine",
		Name:      "satellites_used",
		Help:      "Number of satellites used per position fix.",
		Buckets:   []float64{4, 5, 6, 7, 8, 10, 12, 15, 20},
	})
)

// AssistanceDataType enumerates the assistance data categories supported.
type AssistanceDataType int

const (
	AssistanceDataEphemeris   AssistanceDataType = 0
	AssistanceDataIonospheric AssistanceDataType = 1
	AssistanceDataRefTime     AssistanceDataType = 2
)

// ---------------------------------------------------------------------------
// Request / response types
// In production these would be generated from .proto files. They are defined
// inline here to keep the service self-contained while retaining the correct
// field semantics.
// ---------------------------------------------------------------------------

// GnssAssistanceRequest is the inbound request for assistance data.
type GnssAssistanceRequest struct {
	SessionID      string
	Constellations []assistance.GnssConstellation
	DataTypes      []AssistanceDataType
}

// GnssAssistanceResponse carries the requested assistance data.
type GnssAssistanceResponse struct {
	SessionID     string
	Ephemerides   []assistance.GnssEphemeris
	Ionospheric   *assistance.KlobucharModel
	ReferenceTime time.Time
	GPSWeek       int32
	GPSTOW        float64
}

// GnssComputeRequest carries UE measurements for position computation.
type GnssComputeRequest struct {
	SessionID     string
	Measurements  []positioning.GnssSignalMeasurement
	Ephemerides   []assistance.GnssEphemeris
	ReferenceTime time.Time // zero → use server time
}

// GnssComputeResponse is the position fix response.
type GnssComputeResponse struct {
	SessionID string
	Position  *positioning.PositionEstimate
}

// GnssEngineServiceServer is the interface fulfilled by GnssServer.
// In a real gRPC deployment this would be the generated pb.GnssEngineServiceServer.
type GnssEngineServiceServer interface {
	GetAssistanceData(ctx context.Context, req *GnssAssistanceRequest) (*GnssAssistanceResponse, error)
	ComputePosition(ctx context.Context, req *GnssComputeRequest) (*GnssComputeResponse, error)
}

// RegisterGnssEngineServiceServer registers the server with a gRPC server.
// In production this is generated by protoc-gen-go-grpc.
func RegisterGnssEngineServiceServer(s *grpc.Server, srv GnssEngineServiceServer) {
	// NOTE: registration via grpc.Server.RegisterService would be added here
	// once .proto-generated code is available. For now this function acts as
	// a compile-time check that GnssServer satisfies the interface.
	_ = s
	_ = srv
}

// ---------------------------------------------------------------------------
// GnssServer implementation
// ---------------------------------------------------------------------------

// GnssServer implements GnssEngineServiceServer.
type GnssServer struct {
	provider *assistance.AssistanceDataProvider
	solver   *positioning.GnssSolver
	logger   *zap.Logger
}

// NewGnssServer creates a new server instance.
func NewGnssServer(
	provider *assistance.AssistanceDataProvider,
	solver *positioning.GnssSolver,
	logger *zap.Logger,
) *GnssServer {
	return &GnssServer{
		provider: provider,
		solver:   solver,
		logger:   logger,
	}
}

// GetAssistanceData serves GNSS assistance data.
// It first checks the Redis cache; missing types are fetched from the provider
// and stored in the cache before being returned.
func (s *GnssServer) GetAssistanceData(
	ctx context.Context,
	req *GnssAssistanceRequest,
) (*GnssAssistanceResponse, error) {
	start := time.Now()
	methodAttempts.WithLabelValues("GetAssistanceData", "attempt").Inc()
	defer func() {
		methodLatency.WithLabelValues("GetAssistanceData").Observe(time.Since(start).Seconds())
	}()

	resp := &GnssAssistanceResponse{SessionID: req.SessionID}
	cache := s.provider.Cache()

	for _, dt := range req.DataTypes {
		switch dt {

		case AssistanceDataEphemeris:
			var cached []assistance.GnssEphemeris
			if ok, _ := cache.Get(ctx, "ephemeris", &cached); ok && len(cached) > 0 {
				resp.Ephemerides = cached
			} else {
				ephs, err := s.provider.FetchEphemeris(ctx, req.Constellations)
				if err != nil {
					methodAttempts.WithLabelValues("GetAssistanceData", "error").Inc()
					return nil, status.Errorf(codes.Internal, "fetch ephemeris: %v", err)
				}
				resp.Ephemerides = ephs
			}

		case AssistanceDataIonospheric:
			var cached assistance.KlobucharModel
			if ok, _ := cache.Get(ctx, "ionospheric", &cached); ok {
				resp.Ionospheric = &cached
			} else {
				model, err := s.provider.FetchIonosphericModel(ctx)
				if err != nil {
					methodAttempts.WithLabelValues("GetAssistanceData", "error").Inc()
					return nil, status.Errorf(codes.Internal, "fetch ionospheric model: %v", err)
				}
				resp.Ionospheric = model
			}

		case AssistanceDataRefTime:
			t, gps, err := s.provider.FetchReferenceTime(ctx)
			if err != nil {
				methodAttempts.WithLabelValues("GetAssistanceData", "error").Inc()
				return nil, status.Errorf(codes.Internal, "fetch reference time: %v", err)
			}
			resp.ReferenceTime = t
			resp.GPSWeek = int32(gps.Week)  //nolint:gosec
			resp.GPSTOW = gps.Seconds
		}
	}

	methodAttempts.WithLabelValues("GetAssistanceData", "success").Inc()
	s.logger.Debug("assistance data served",
		zap.String("session", req.SessionID),
		zap.Int("types", len(req.DataTypes)),
		zap.Int("ephemerides", len(resp.Ephemerides)),
	)
	return resp, nil
}

// ComputePosition processes UE GNSS measurements and returns a position fix.
func (s *GnssServer) ComputePosition(
	ctx context.Context,
	req *GnssComputeRequest,
) (*GnssComputeResponse, error) {
	start := time.Now()
	methodAttempts.WithLabelValues("ComputePosition", "attempt").Inc()
	defer func() {
		methodLatency.WithLabelValues("ComputePosition").Observe(time.Since(start).Seconds())
	}()

	if len(req.Measurements) < 4 {
		methodAttempts.WithLabelValues("ComputePosition", "error").Inc()
		return nil, status.Errorf(codes.InvalidArgument,
			"need at least 4 GNSS measurements, got %d", len(req.Measurements))
	}

	refTime := req.ReferenceTime
	if refTime.IsZero() {
		refTime = time.Now().UTC()
	}

	pos, err := s.solver.ComputePosition(req.Measurements, req.Ephemerides, refTime)
	if err != nil {
		methodAttempts.WithLabelValues("ComputePosition", "error").Inc()
		s.logger.Error("GNSS position computation failed",
			zap.String("session", req.SessionID),
			zap.Int("measurements", len(req.Measurements)),
			zap.Error(err),
		)
		return nil, status.Errorf(codes.Internal, "compute position: %v", err)
	}

	// Record observability metrics.
	accuracyAchieved.Observe(pos.HorizontalAccuracy)
	satellitesUsed.Observe(float64(pos.NumSatellites))
	methodAttempts.WithLabelValues("ComputePosition", "success").Inc()

	s.logger.Info("GNSS position computed",
		zap.String("session", req.SessionID),
		zap.Float64("lat", pos.Latitude),
		zap.Float64("lon", pos.Longitude),
		zap.Float64("alt_m", pos.Altitude),
		zap.Float64("h_acc_m", pos.HorizontalAccuracy),
		zap.Float64("hdop", pos.HDOP),
		zap.Int("sats", pos.NumSatellites),
		zap.Duration("compute_time", time.Since(start)),
	)

	return &GnssComputeResponse{
		SessionID: req.SessionID,
		Position:  pos,
	}, nil
}
